(function(g){var window=this;'use strict';var UX=function(L){L.publish("cardstatechange",L.JY()&&L.Tu()?1:0)},Bc=function(L,m){var n=g.Zo(m),C=n?m:arguments;
for(n=n?0:1;n<C.length;n++){if(L==null)return;L=L[C[n]]}return L},lmZ=function(L){var m=g.L6(L);
L=g.C6(L);return new g.H0(m.x,m.y,L.width,L.height)},RQZ=function(L,m,n){var C=C===void 0?{}:C;
var Z;return Z=g.ge(L,m,function(){g.MP(Z);n.apply(L,arguments)},C)},QN=function(L){L=g.Er(L);
delete Pc[L];g.$T(Pc)&&sX&&sX.stop()},eQw=function(){sX||(sX=new g.jW(function(){wAl()},20));
var L=sX;L.isActive()||L.start()},wAl=function(){var L=g.$_();
g.cz(Pc,function(m){gkf(m,L)});
g.$T(Pc)||eQw()},pY=function(L,m,n,C){g.iz.call(this);
if(!Array.isArray(L)||!Array.isArray(m))throw Error("Start and end parameters must be arrays");if(L.length!=m.length)throw Error("Start and end points must be the same length");this.J=L;this.B=m;this.duration=n;this.K=C;this.coords=[];this.progress=this.S=0;this.L=null},gkf=function(L,m){m<L.startTime&&(L.endTime=m+L.endTime-L.startTime,L.startTime=m);
L.progress=(m-L.startTime)/(L.endTime-L.startTime);L.progress>1&&(L.progress=1);L.S=1E3/(m-L.L);L.L=m;MQr(L,L.progress);L.progress==1?(L.W=0,QN(L),L.onFinish(),L.nD()):L.isPlaying()&&L.d8()},MQr=function(L,m){typeof L.K==="function"&&(m=L.K(m));
L.coords=Array(L.J.length);for(var n=0;n<L.J.length;n++)L.coords[n]=(L.B[n]-L.J[n])*m+L.J[n]},SLw=function(L,m){g.Kq.call(this,L);
this.coords=m.coords;this.x=m.coords[0];this.y=m.coords[1];this.z=m.coords[2];this.duration=m.duration;this.progress=m.progress;this.fps=m.S;this.state=m.W},Fh=function(L,m,n,C,Z){pY.call(this,m,n,C,Z);
this.element=L},Iml=function(L,m,n,C,Z){if(m.length!=2||n.length!=2)throw Error("Start and end points must be 2D");
Fh.call(this,L,m,n,C,Z)},JnD=function(L){return Math.pow(L,3)},Anw=function(L){return 3*L*L-2*L*L*L},blz=function(L){g.u.call(this);
this.J=L||window;this.W=[]},uW=function(L){return L.baseUrl||null},hz=function(L,m){return g.f7(g.lu(L,m),function(n){return!!n})},tQJ=function(L,m,n){function C(N3){var ZF=N3.hovercardButton;
if(!ZF)return null;ZF=ZF.subscribeButtonRenderer;if(!ZF)return null;var $P=z(ZF.unsubscribedButtonText),mZ=z(ZF.subscribedButtonText);if(ZF.subscribed){var J_=z(ZF.subscriberCountWithUnsubscribeText);var xP=z(ZF.subscriberCountText)}else J_=z(ZF.subscriberCountText),xP=z(ZF.subscriberCountWithSubscribeText);var Vw=null;if(N3.signinEndpoint){Vw=Bc(N3,"signinEndpoint","webNavigationEndpointData","url");if(!Vw){var T0,h_;Vw=(h_=g.k((T0=ZF.signInEndpoint)==null?void 0:T0.commandMetadata,g.SC))==null?
void 0:h_.url}if(!Vw)return null}return $P&&(mZ||Vw)?{subscribed:ZF.subscribed,subscribeText:$P,subscribeCount:J_,unsubscribeText:mZ,unsubscribeCount:xP,enabled:ZF.enabled,signinUrl:Vw,classic:N3.useClassicSubscribeButton}:null}
function Z(N3){if(N3){var ZF=[],$P=N3.videoId;$P&&ZF.push("v="+$P);($P=N3.playlistId)&&ZF.push("list="+$P);(N3=N3.startTimeSeconds)&&ZF.push("t="+N3);return"/watch?"+ZF.join("&")}}
function z(N3){if(!N3)return null;var ZF=N3.simpleText;return ZF?ZF:N3.runs?g.lu(N3.runs,function($P){return $P.text}).join(""):null}
m=m.endscreenElementRenderer;if(!m)return null;var v=m.style,X=m.endpoint||{},N=null,T=null,V=!1,a=null,q=null,D=null,O=null,e=!1,I=null,t=null,b=null,P=null,F=null,r=null;if(v==="VIDEO")g.k(X,g.pD)?N=g.k(X,g.pD).url:(r=g.k(X,g.t1),N=Z(r)),T=!1,a=L,m.thumbnailOverlays?(V=m.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,q=z(V.text),V=V.style==="LIVE"):q=z(m.videoDuration);else if(v==="PLAYLIST")g.k(X,g.pD)?N=g.k(X,g.pD).url:(r=g.k(X,g.t1),N=Z(r)),T=!1,a=L,D=z(m.playlistLength);else if(v===
"CHANNEL"){if(e=Bc(X,"browseEndpoint","browseId"))O=e,N="/channel/"+O;T=!1;a="new";(e=!!m.isSubscribe)?I=C(m):t=z(m.subscribersText)}else v==="WEBSITE"?((b=Bc(X,"urlEndpoint","url"))&&(N=b),T=!0,a="new",b=m.icon.thumbnails[0].url):v==="CREATOR_MERCHANDISE"&&(m.productPrice&&(P=z(m.productPrice)),m.additionalFeesText&&(F=z(m.additionalFeesText)),(T=Bc(X,"urlEndpoint","url"))&&(N=T),T=!0,a="new");L=Bc(m,"title","accessibility","accessibilityData","label");var x=m.endpoint?m.endpoint.clickTrackingParams:
null,Y="";if(m.metadata){var Ed=z(m.metadata);Ed&&(Y=Ed)}return{id:"element-"+n,type:v,title:z(m.title),metadata:Y,callToAction:z(m.callToAction),N9:m.image,iconUrl:b,left:Number(m.left),width:Number(m.width),top:Number(m.top),aspectRatio:Number(m.aspectRatio),startMs:Math.floor(Number(m.startMs)),endMs:Math.floor(Number(m.endMs)),videoDuration:q,oH:V,playlistLength:D,channelId:O,subscribeButton:I,subscribersText:t,isSubscribe:e,targetUrl:N||null,Jel:T,sessionData:x?{itct:x}:null,k5v:a,yR:L?L:null,
isPlaceholder:m.isPlaceholder,impressionUrls:hz(m.impressionUrls||[],uW),DQ:hz(m.hovercardShowUrls||[],uW),clickUrls:hz(X.loggingUrls||[],uW),visualElement:g.Rh(m.trackingParams),productPrice:P,additionalFeesText:F,watchEndpoint:r||null}},fmp=function(L,m){var n={startMs:Math.floor(Number(L.startMs)),
impressionUrls:hz(L.impressionUrls||[],uW),elements:hz(L.elements||[],function(C,Z){return tQJ(m,C,Z)})};
L.trackingParams&&(n.visualElement=g.Rh(L.trackingParams));return n},UQl=function(L){g.S2.call(this,L);
this.L=this.endscreen=null;this.J={};this.S={};this.K=this.G=null;this.C=[];this.W=null;this.wd=!0;this.B=0;L=L.D();this.X=g.$w(L)||g.qM(L);this.events=new g.tC(this);g.h(this,this.events);this.events.j(this.player,g.La("creatorendscreen"),this.onCueRangeEnter);this.events.j(this.player,g.mM("creatorendscreen"),this.onCueRangeExit);this.events.j(this.player,"resize",this.VH);this.events.j(window,"focus",this.kZd);this.load();var m=g.q4("STYLE");(g.v0("HEAD")[0]||document.body).appendChild(m);this.addOnDisposeCallback(function(){g.wr(m)});
m.sheet&&(m.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),m.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},BdF=function(L){return L.player.getVideoData().IL?"current":L.X?"new":"current"},rv=function(L){return L.player.D().playerStyle==="creator-endscreen-editor"},PcH=function(L){var m=L.player.getVideoData(),n=m.videoId;
L.L&&L.L.abort();n={method:"POST",onFinish:function(Z){var z=L.L=null;Z.status===200&&(Z=Z.responseText,Z.substring(0,3)===")]}"&&(Z=Z.substring(3),z=JSON.parse(Z),z=fmp(z,BdF(L))));kn(L,z)},
urlParams:{v:n},withCredentials:!0};L.X&&(n.urlParams.ptype="embedded");var C=m.Bo;C&&(n.postParams={ad_tracking:C});if(m=g.mmx(m))if(m=g.Ni(m),m=g.vr(m))L.L=g.IT(m,n)},kn=function(L,m,n){n=n===void 0?!0:n;
L.player.H0("creatorendscreen");L.G&&(L.G.dispose(),L.G=null,L.K.dispose(),L.K=null);for(var C=g.M(Object.values(L.J)),Z=C.next();!Z.done;Z=C.next())Z.value.dispose();L.J={};L.S={};L.C.length>0&&(L.C.forEach(function(X){X.dispose()}),L.C.length=0);
L.W&&(g.N8(L.W,"ytp-ce-element-show"),L.W.setAttribute("aria-hidden","true"));L.B=0;if((L.endscreen=m)&&m.elements){n&&s3F(L);n=[];C=new g.oD(m.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});n.push(C);L.player.D().J||(L.G=new g.H({Z:"div",T:"ytp-ce-shadow"}),g.Zq(L.player,L.G.element,4),L.K=new g.mL(L.G,200));for(C=0;C<m.elements.length;++C){Z=m.elements[C];var z=Q3o(L,Z);if(z){L.J[Z.id]=z;L.S[Z.id]=Z;g.Zq(L.player,z.element,4);var v=new g.oD(Z.startMs,Z.endMs,{id:"ytp-ce-element-"+
Z.id,namespace:"creatorendscreen"});n.push(v);pAF(L,z,Z)}else g.U$(new g.YZ("buildEndscreenElement null",Z))}L.player.Aw(n);L.VH()}},s3F=function(L){var m=g.eB(),n=g.gC();
n&&m&&L.endscreen.visualElement&&g.jb(g.YF)(void 0,n,m,L.endscreen.visualElement)},Q3o=function(L,m){var n=null;
switch(m.type){case "VIDEO":L={Z:"div",xU:["ytp-ce-element","ytp-ce-video"],Y:{tabindex:"0","aria-label":m.yR||"","aria-hidden":"true"},V:[{Z:"div",T:"ytp-ce-element-shadow"},{Z:"div",T:"ytp-ce-covering-image",Y:Hc(m)},{Z:"div",T:"ytp-ce-covering-shadow-top"},{Z:"a",T:"ytp-ce-covering-overlay",Y:{href:Yn(L,m.targetUrl),tabindex:"-1"},V:[{Z:"div",xU:["ytp-ce-video-title","ytp-webkit-ellipsis"],Y:{dir:g.Oi(m.title||"")},zo:m.title},{Z:"div",T:m.oH?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
zo:m.videoDuration||void 0}]}]};n=new g.H(L);break;case "PLAYLIST":L={Z:"div",xU:["ytp-ce-element","ytp-ce-playlist"],Y:{tabindex:"0","aria-label":m.yR||"","aria-hidden":"true"},V:[{Z:"div",T:"ytp-ce-element-shadow"},{Z:"div",T:"ytp-ce-covering-image",Y:Hc(m)},{Z:"div",T:"ytp-ce-covering-shadow-top"},{Z:"a",T:"ytp-ce-covering-overlay",Y:{href:Yn(L,m.targetUrl),tabindex:"-1"},V:[{Z:"div",xU:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],Y:{dir:g.Oi(m.title||"")},zo:m.title},{Z:"div",T:"ytp-ce-playlist-count",
V:[{Z:"div",T:"ytp-ce-playlist-icon"},{Z:"div",T:"ytp-ce-playlist-count-text",zo:m.playlistLength||void 0}]}]}]};n=new g.H(L);break;case "CHANNEL":n={Z:"div",xU:["ytp-ce-element","ytp-ce-channel",m.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],Y:{tabindex:"0","aria-label":m.yR||"","aria-hidden":"true"},V:[{Z:"div",T:"ytp-ce-element-shadow"},{Z:"div",T:"ytp-ce-expanding-overlay",V:[{Z:"div",T:"ytp-ce-expanding-overlay-hider"},{Z:"div",T:"ytp-ce-expanding-overlay-background"},{Z:"div",T:"ytp-ce-expanding-overlay-content",
V:[{Z:"div",T:"ytp-ce-expanding-overlay-body",V:[{Z:"div",T:"ytp-ce-expanding-overlay-body-padding",V:[{Z:"a",xU:["ytp-ce-channel-title","ytp-ce-link"],Y:{href:Yn(L,m.targetUrl),target:"_blank",tabindex:"-1",dir:g.Oi(m.title||"")},zo:m.title},m.subscribeButton?{Z:"div",T:"ytp-ce-subscribe-container",V:[{Z:"div",T:"ytp-ce-channel-subscribe"}]}:"",m.subscribersText?{Z:"div",T:"ytp-ce-channel-subscribers-text",zo:m.subscribersText}:"",m.metadata?{Z:"div",xU:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],zo:m.metadata}:""]}]}]}]},{Z:"div",T:"ytp-ce-expanding-image",Y:Hc(m)}]};n=new g.H(n);var C=g.XE(document,"div","ytp-ce-channel-subscribe",n.element)[0];if(m.subscribeButton&&m.channelId){g.Ei(C,"ytp-ce-subscribe-button");if(L.player.D().J){var Z=null;var z=m.sessionData.itct}else Z="endscreen",z=null;Z=new g.zm(m.subscribeButton.subscribeText,m.subscribeButton.subscribeCount,m.subscribeButton.unsubscribeText,m.subscribeButton.unsubscribeCount,!!m.subscribeButton.enabled,!!m.subscribeButton.classic,
m.channelId,!!m.subscribeButton.subscribed,Z,z,L.player,!1);C.appendChild(Z.element);L.C.push(Z)}break;case "WEBSITE":L={Z:"div",xU:["ytp-ce-element","ytp-ce-website"],Y:{tabindex:"0","aria-label":m.yR||"","aria-hidden":"true"},V:[{Z:"div",T:"ytp-ce-element-shadow"},{Z:"div",T:"ytp-ce-expanding-overlay",V:[{Z:"div",T:"ytp-ce-expanding-overlay-hider"},{Z:"div",T:"ytp-ce-expanding-overlay-background"},{Z:"div",T:"ytp-ce-expanding-overlay-content",V:[{Z:"div",T:"ytp-ce-expanding-overlay-body",V:[{Z:"div",
T:"ytp-ce-expanding-overlay-body-padding",V:[{Z:"div",T:"ytp-ce-website-title",Y:{dir:g.Oi(m.title||"")},zo:m.title},{Z:"div",T:"ytp-ce-website-metadata",zo:m.metadata},{Z:"a",xU:["ytp-ce-website-goto","ytp-ce-link"],Y:{href:Yn(L,m.targetUrl),target:"_blank",tabindex:"-1"},zo:m.callToAction}]}]}]}]},{Z:"div",T:"ytp-ce-expanding-image",Y:Hc(m)},{Z:"div",T:"ytp-ce-expanding-icon",Y:Fkw(m.iconUrl)}]};n=new g.H(L);break;case "CREATOR_MERCHANDISE":n="",m.productPrice&&(n={Z:"div",T:"ytp-ce-merchandise-price-container",
V:[{Z:"div",T:"ytp-ce-merchandise-price",zo:m.productPrice}]},m.additionalFeesText&&n.V.push({Z:"div",T:"ytp-ce-merchandise-additional-fees",zo:m.additionalFeesText})),L={Z:"div",xU:["ytp-ce-element","ytp-ce-merchandise"],Y:{tabindex:"0","aria-label":m.yR||"","aria-hidden":"true"},V:[{Z:"div",T:"ytp-ce-element-shadow"},{Z:"div",T:"ytp-ce-expanding-overlay",V:[{Z:"div",T:"ytp-ce-expanding-overlay-hider"},{Z:"div",T:"ytp-ce-expanding-overlay-background"},{Z:"div",T:"ytp-ce-expanding-overlay-content",
V:[{Z:"div",T:"ytp-ce-expanding-overlay-body",V:[{Z:"div",T:"ytp-ce-expanding-overlay-body-padding",V:[{Z:"div",T:"ytp-ce-merchandise-title",Y:{dir:g.Oi(m.title||"")},zo:m.title},n,{Z:"div",T:"ytp-ce-merchandise-metadata",zo:m.metadata},{Z:"a",xU:["ytp-ce-merchandise-goto","ytp-ce-link"],Y:{href:Yn(L,m.targetUrl),target:"_blank",tabindex:"-1"},zo:m.callToAction}]}]}]}]},{Z:"div",T:"ytp-ce-expanding-image",Y:Hc(m)},{Z:"div",T:"ytp-ce-merchandise-invideo-cta-container",V:[{Z:"div",T:"ytp-ce-merchandise-invideo-cta",
zo:m.callToAction||void 0}]}]},n=new g.H(L)}m.isPlaceholder&&g.Ei(n.element,"ytp-ce-placeholder");return n},Hc=function(L){if(L.N9)var m=L.N9.thumbnails;
return Fkw(m?m[m.length-1].url:null)},Fkw=function(L){return L?{style:"background-image: url("+L+")"}:{}},pAF=function(L,m,n){function C(N){N&&(m.listen("blur",function(){N.style.display!="none"&&L.wd&&N.focus()}),m.j(N,"focus",z),m.j(N,"blur",v))}
function Z(N){L.B+=N;L.B>0?(g.Ei(m.element,"ytp-ce-force-expand"),Wc(L,n.id,!0)):(g.N8(m.element,"ytp-ce-force-expand"),g.N8(m.element,"ytp-ce-element-hover"),Wc(L,n.id,!1))}
function z(){Z(1)}
function v(){Z(-1)}
m.listen("mouseenter",function(){uAF(L,m,n)});
m.listen("mouseleave",function(){hQp(L,m,n)});
L.player.D().J||m.listen("click",function(){g.Ei(m.element,"ytp-ce-element-hover")});
m.listen("click",function(N){rnr(L,n,N)});
m.listen("keypress",function(N){rnr(L,n,N)});
m.listen("focus",function(){uAF(L,m,n)});
m.listen("blur",function(){hQp(L,m,n)});
m.listen("touchstart",function(){uAF(L,m,n)});
var X=g.N4("ytp-ce-expanding-overlay-hider",m.element);X&&m.j(X,"touchstart",function(N){N.stopPropagation();g.N8(m.element,"ytp-ce-element-hover");g.N8(m.element,"ytp-ce-force-expand")});
m.listen("keydown",function(N){L.wd=N.keyCode===9&&!N.shiftKey});
C(g.N4("ytp-sb-subscribe",m.element));C(g.N4("ytp-sb-unsubscribe",m.element));m.listen("focus",z);m.listen("blur",v)},rnr=function(L,m,n){if(m.targetUrl&&(!n||n.type!=="keypress"||n.keyCode===13)){for(var C=n.target;C&&!g.vu(C,"ytp-ce-element");){g.vu(C,"subscribe-label")&&kRD(L,m);
if(g.vu(C,"ytp-ce-channel-subscribe"))return;C=C.parentElement||null}if(!C||g.vu(C,"ytp-ce-element-hover")){n.preventDefault();n.stopPropagation();if(C=L.J[m.id])hQp(L,C,m),C.element.blur();if(n.ctrlKey||n.metaKey||m.k5v==="new")kRD(L,m),L.player.sendVideoStatsEngageEvent(17,void 0),L.player.pauseVideo(),n=g.Ni(Yn(L,m.targetUrl)),n=g.vr(n),g.Y7(n,void 0,m.sessionData);else{var Z=g.bB(L.player.D())||L.player.getVideoData().IL,z=function(){var v=Yn(L,m.targetUrl),X=m.sessionData,N=m.watchEndpoint,T=
g.Ci(v);Z&&T&&(T.v||T.list)?L.player.CF(T.v,X,T.list,!1,void 0,N||void 0):g.HC(v,X)};
kRD(L,m,function(){L.player.sendVideoStatsEngageEvent(17,z)})}}}},Yn=function(L,m){L=L.player.D();
if(m){if(m.startsWith("//"))return L.protocol+":"+m;if(m.startsWith("/"))return g.p4(L)+m}else return"";return m},uAF=function(L,m,n){g.vu(m.element,"ytp-ce-element-hover")||(n.type==="VIDEO"||n.type==="PLAYLIST"?g.Ei(m.element,"ytp-ce-element-hover"):L.player.D().J?(new g.jW(function(){g.Ei(m.element,"ytp-ce-element-hover")},200)).start():g.Ei(m.element,"ytp-ce-element-hover"),GX(L,n.DQ),Wc(L,n.id,!0))},hQp=function(L,m,n){g.N8(m.element,"ytp-ce-element-hover");
g.N8(m.element,"ytp-ce-force-expand");Wc(L,n.id,!1)},Wc=function(L,m,n){L.G&&(n?L.K.show():L.K.hide());
for(var C=g.M(Object.keys(L.J)),Z=C.next();!Z.done;Z=C.next())Z=Z.value,Z!==m&&g.VR(L.J[Z].element,"ytp-ce-element-shadow-show",n)},GX=function(L,m,n){function C(){z||(Z++,Z===m.length&&(v.stop(),n&&n()))}
if(!m||m.length===0||rv(L))n&&n();else{m=Hl1(L,m);var Z=0,z=!1,v=new g.jW(function(){z=!0;n&&n()},1E3,L);
v.start();for(L=0;L<m.length;L++)g.s0(m[L],C)}},kRD=function(L,m,n){GX(L,m.clickUrls,n);
(L=g.gC())&&m.Jel&&g.mT(L,m.visualElement)},Hl1=function(L,m){var n=L.player.getVideoData().clientPlaybackNonce;
L=L.player.getCurrentTime().toFixed(2);n={CPN:n,AD_CPN:n,MT:L};L=[];for(var C=0;C<m.length;C++)L.push(YLw(m[C],n));return L},YLw=function(L,m){return L.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(n){var C=unescape(n);
C=C.substring(1,C.length-1);return m[C]?escape(m[C]):n})},WkF=function(L){return typeof L==="string"?L:""},dv=function(L,m,n){for(var C in m)if(m[C]===L)return L;
return n},GR1=function(L,m,n,C){this.value=L;
this.target=m;this.showLinkIcon=n;this.W=C},KY=function(L){return L.value?L.value:null},xn=function(L){if(!L)return null;
var m=g.Ni(WkF(L.value));m=g.vr(m);if(!m)return null;var n=dv(L.target,dQz,"current");if(n==null)L=null;else{var C=L.show_link_icon;L=new GR1(m,n,C==="true"||C==="false"?C==="true":!0,L.pause_on_navigation!=null?L.pause_on_navigation:!0)}return L},KkJ=function(L,m,n){this.type=L;
this.trigger=m;this.url=n},j3H=function(L){if(!L)return null;
var m=dv(L.type,xQr),n=dv(L.trigger,ynH);L=L.url;L=Array.isArray(L)&&L.length?L[0]:L;L=xn(L?L:null);return m?new KkJ(m,n,L):null},ok_=function(L,m,n,C,Z){this.id=L;
this.type=m;this.style=n;this.data=Z;this.action=C||[]},cn_=function(L,m){return g.wH(L.action,m)},L6f=function(L,m){this.context=L;
this.W=m},mJ0=function(L){return L.customMessage?yN("div","iv-card-message",L.customMessage):""},jM=function(L,m){L="background-image: url("+L+");";
var n=[];m&&n.push(m);return{Z:"div",T:"iv-card-image",Y:{style:L},V:n}},nRF=function(L){if(!L.metaInfo||L.metaInfo.length===0)return"";
var m=[];L=g.M(L.metaInfo);for(var n=L.next();!n.done;n=L.next())m.push(yN("li","",n.value));return{Z:"ul",T:"iv-card-meta-info",V:m}},yN=function(L,m,n){m?typeof m==="string"?m={"class":m}:Array.isArray(m)&&(m={"class":m.join(" ")}):m={};
m.dir=g.Oi(n);return{Z:L,Y:m,zo:n}},CNp=function(L){if(!L.customMessage)return"";
var m=["iv-card-action","iv-card-primary-link"],n={};L.RZ&&(m.push("iv-card-action-icon"),n.style="background-image: url("+L.RZ+");");n.dir=g.Oi(L.customMessage);var C=[{Z:"span",zo:L.customMessage}];L.showLinkIcon&&(C.push("\u00a0"),C.push({Z:"span",T:"iv-card-link-icon"}));return{Z:"div",xU:m,Y:n,V:C}},oq=function(L,m,n,C){if(C){m=g.M(m);
for(var Z=m.next();!Z.done;Z=m.next())L.W(Z.value,C,n.id,n.sessionData,n.zJ.click,5)}},ZS0=function(L,m){this.merchant=L;
this.price=m},z1F=function(L){var m;
(m=L)&&!(m=L.length>1?L.charAt(0)==="/"&&L.charAt(1)!=="/":L==="/")&&(m=L.replace(/^(https?:)?\/\//,"").split("/",1),m=!m||m.length<1||!m[0]?[]:m[0].toLowerCase().split(".").reverse(),m=m[0]==="com"&&m[1]==="youtube"||m[0]==="be"&&m[1]==="youtu");return m?L.indexOf("/redirect?")===-1:!1},vRr=function(L,m){return m?m:z1F(L)?"current":"new"},cc=function(L,m){g.u.call(this);
var n=this;this.element=L;this.context=m;this.WD=!1;this.YU=new Map;this.pI=new Map;this.context.U.addEventListener(g.La("annotations_module"),function(C){(C=n.YU.get(C))&&C.apply(n)});
this.context.U.addEventListener(g.mM("annotations_module"),function(C){(C=n.pI.get(C))&&C.apply(n)})},Lo=function(L,m,n,C,Z,z,v){L.context.W.listen(m,"click",function(X){L.qB(n,C,Z,z||[],v||0,X)});
L.context.W.listen(m,"touchstart",function(){L.WD=!1});
L.context.W.listen(m,"touchmove",function(){L.WD=!0})},ERD=function(L){var m;
return((m=g.k(L,g.pD))==null?0:m.url)?g.k(L,g.pD).url:(L=g.k(L,g.t1))&&L.videoId?(m="/watch?v="+L.videoId,L.playlistId&&(m+="&list="+L.playlistId),L.index&&(m+="&index="+L.index),L.startTimeSeconds&&(m+="&t="+L.startTimeSeconds),m):null},mm=function(L,m,n){return{O3:(L.impressionLoggingUrlsV2s||[]).map(function(C){return C.baseUrl||""}),
click:(n.loggingUrls||[]).map(function(C){return C.baseUrl||""}),
close:(m.dismissLoggingUrlsV2s||[]).map(function(C){return C.baseUrl||""}),
We:(m.impressionLoggingUrlsV2s||[]).map(function(C){return C.baseUrl||""}),
Zu:(m.clickLoggingUrlsV2s||[]).map(function(C){return C.baseUrl||""})}},XxF=function(L,m,n){cc.call(this,m,n);
var C=this;this.U=L;this.eventId=null;this.Lu=this.rd=this.cD=this.G=this.isInitialized=!1;this.cards=[];this.wx=this.K=this.SD=this.S=this.Hv=this.W=null;this.wd=[];this.Je=this.C=this.IU=this.KI=null;this.B=0;this.aj=new g.jW(function(){},n.yd.yS?4E3:3E3);
g.h(this,this.aj);this.CI=new g.jW(function(){});
g.h(this,this.CI);this.LI=new L6f(n,function(Z,z,v,X,N,T){Lo(C,Z,z,v,X,N,T)});
this.X=new g.H({Z:"div",T:"iv-drawer",Y:{id:"iv-drawer"},V:[{Z:"div",T:"iv-drawer-header",Y:{"aria-role":"heading"},V:[{Z:"span",T:"iv-drawer-header-text"},{Z:"button",xU:["iv-drawer-close-button","ytp-button"],Y:{"aria-label":"Hide cards",tabindex:"0"}}]},{Z:"div",T:"iv-drawer-content"}]});g.h(this,this.X);this.L=this.X.element;this.fI=new g.mL(this.X,330);g.h(this,this.fI);this.bj=g.N4("iv-drawer-header-text",this.L);this.J=g.N4("iv-drawer-content",this.L);this.addCueRange(0,n.videoData.lengthSeconds*
1E3,"",function(){C.cD&&no(C,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(C.cD=C.G)&&Co(C)});
this.Qd=new g.tC(this);g.h(this,this.Qd);this.U.addEventListener("videodatachange",this.U1.bind(this))},NX$=function(L,m){m=m.data;
m.autoOpenMs&&L.addCueRange(m.autoOpenMs,0x8000000000000,"",function(){no(L,"YOUTUBE_DRAWER_AUTO_OPEN")});
m.autoCloseMs&&L.addCueRange(m.autoCloseMs,0x8000000000000,"",function(){Co(L)});
var n=m.headerText;g.IL(L.bj,n);L.K&&(L.U.N("player_tooltip_data_title_killswitch")?L.K.setAttribute("title",n):L.K.setAttribute("data-tooltip-title",n));m.eventId&&(L.eventId=m.eventId);L.KI=g.Rh(m.trackingParams);L.C=g.Rh(m.closeTrackingParams);L.IU=g.Rh(m.iconTrackingParams)},TXf=function(L,m){var n=m.cardId?m.cardId:"cr:"+L.B,C=L.U.D().experiments.qb("enable_error_corrections_infocard_web_client");
if(!m.content&&m.teaser.simpleCardTeaserRenderer&&C){var Z=m.teaser.simpleCardTeaserRenderer,z=m.icon?m.icon.infoCardIconRenderer:null;if(Z.channelAvatar&&Z.channelAvatar.thumbnails&&Z.channelAvatar.thumbnails.length>0)var v=Zi(Z.channelAvatar.thumbnails,22,22).url;m={id:n,timestamp:L.B,type:"simple",teaserText:g.$5(Z.message),teaserDurationMs:Number(m.cueRanges[0].teaserDurationMs),startMs:Number(m.cueRanges[0].startCardActiveMs),autoOpen:!!m.autoOpen,sessionData:{},sponsored:!1,zJ:{},Hh:null,VY:Z.trackingParams?
g.Rh(Z.trackingParams):null,IU:z&&z.trackingParams?g.Rh(z.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,RZ:null,title:"",customMessage:"",url:null,onClickCommand:Z.onTapCommand||null,RM:v};z_(L,m)}else{var X;if((X=m.content)==null?0:X.simpleCardContentRenderer){if(!m.cueRanges.length)return;v=(Z=m.content)==null?void 0:Z.simpleCardContentRenderer;Z=m.teaser.simpleCardTeaserRenderer;z=m.icon?m.icon.infoCardIconRenderer:null;m={id:n,timestamp:L.B,type:"simple",teaserText:g.$5(Z.message),
teaserDurationMs:Number(m.cueRanges[0].teaserDurationMs),startMs:Number(m.cueRanges[0].startCardActiveMs),autoOpen:!!m.autoOpen,sessionData:vs(L,n,m,v),sponsored:!1,zJ:mm(v,Z,v.command),Hh:v.trackingParams?g.Rh(v.trackingParams):null,VY:Z.trackingParams?g.Rh(Z.trackingParams):null,IU:z&&z.trackingParams?g.Rh(z.trackingParams):null,imageUrl:Zi(v.image.thumbnails,290,290).url,displayDomain:v.displayDomain?g.$5(v.displayDomain):null,showLinkIcon:!!v.showLinkIcon,RZ:null,title:v.title?g.$5(v.title):"",
customMessage:v.callToAction?g.$5(v.callToAction):"",url:g.k(v.command,g.pD).url?xn({pause_on_navigation:!L.context.videoData.isLivePlayback,target:"new",value:g.k(v.command,g.pD).url}):null,onClickCommand:null};z_(L,m)}else{var N;if((N=m.content)==null?0:N.collaboratorInfoCardContentRenderer){if(!m.cueRanges.length)return;v=(z=m.content)==null?void 0:z.collaboratorInfoCardContentRenderer;Z=m.teaser.simpleCardTeaserRenderer;z=m.icon?m.icon.infoCardIconRenderer:null;m={id:n,timestamp:L.B,type:"collaborator",
teaserText:g.$5(Z.message),teaserDurationMs:Number(m.cueRanges[0].teaserDurationMs),startMs:Number(m.cueRanges[0].startCardActiveMs),autoOpen:!!m.autoOpen,sessionData:vs(L,n,m,v),sponsored:!1,zJ:mm(v,Z,v.endpoint),Hh:v.trackingParams?g.Rh(v.trackingParams):null,VY:Z.trackingParams?g.Rh(Z.trackingParams):null,IU:z&&z.trackingParams?g.Rh(z.trackingParams):null,channelId:g.k(v.endpoint,g.nK).browseId,customMessage:v.customText?g.$5(v.customText):null,profileImageUrl:Zi(v.channelAvatar.thumbnails,290,
290).url,title:v.channelName?g.$5(v.channelName):"",metaInfo:[v.subscriberCountText?g.$5(v.subscriberCountText):""],url:xn({pause_on_navigation:!L.context.videoData.isLivePlayback,target:"new",value:g.k(v.endpoint,g.nK).canonicalBaseUrl?g.k(v.endpoint,g.nK).canonicalBaseUrl:"/channel/"+g.k(v.endpoint,g.nK).browseId}),onClickCommand:null};z_(L,m)}else{var T;if((T=m.content)==null?0:T.playlistInfoCardContentRenderer){if(!m.cueRanges.length)return;var V;v=(V=m.content)==null?void 0:V.playlistInfoCardContentRenderer;
Z=m.teaser.simpleCardTeaserRenderer;z=m.icon?m.icon.infoCardIconRenderer:null;m={id:n,timestamp:L.B,type:"playlist",teaserText:g.$5(Z.message),teaserDurationMs:Number(m.cueRanges[0].teaserDurationMs),startMs:Number(m.cueRanges[0].startCardActiveMs),autoOpen:!!m.autoOpen,sessionData:vs(L,n,m,v),sponsored:!1,zJ:mm(v,Z,v.action),Hh:v.trackingParams?g.Rh(v.trackingParams):null,VY:Z.trackingParams?g.Rh(Z.trackingParams):null,IU:z&&z.trackingParams?g.Rh(z.trackingParams):null,ZR:Zi(v.playlistThumbnail.thumbnails,
258,290).url,customMessage:v.customMessage?g.$5(v.customMessage):null,playlistVideoCount:g.$5(v.playlistVideoCount),title:v.playlistTitle?g.$5(v.playlistTitle):"",metaInfo:[v.channelName?g.$5(v.channelName):"",v.videoCountText?g.$5(v.videoCountText):""],url:xn({pause_on_navigation:!L.context.videoData.isLivePlayback,target:"new",value:ERD(v.action)}),onClickCommand:null};z_(L,m)}else{var a;if((a=m.content)==null?0:a.videoInfoCardContentRenderer){if(!m.cueRanges.length)return;var q;v=(q=m.content)==
null?void 0:q.videoInfoCardContentRenderer;Z=m.teaser.simpleCardTeaserRenderer;z=m.icon?m.icon.infoCardIconRenderer:null;m={id:n,timestamp:L.B,type:"video",teaserText:g.$5(Z.message),teaserDurationMs:Number(m.cueRanges[0].teaserDurationMs),startMs:Number(m.cueRanges[0].startCardActiveMs),autoOpen:!!m.autoOpen,sessionData:vs(L,n,m,v),sponsored:!1,zJ:mm(v,Z,v.action),Hh:v.trackingParams?g.Rh(v.trackingParams):null,VY:Z.trackingParams?g.Rh(Z.trackingParams):null,IU:z&&z.trackingParams?g.Rh(z.trackingParams):
null,ZR:Zi(v.videoThumbnail.thumbnails,258,290).url,videoDuration:v.lengthString?g.$5(v.lengthString):null,customMessage:v.customMessage?g.$5(v.customMessage):null,title:v.videoTitle?g.$5(v.videoTitle):"",metaInfo:[v.channelName?g.$5(v.channelName):"",v.viewCountText?g.$5(v.viewCountText):""],isLiveNow:!!v.badge,url:xn({pause_on_navigation:!L.context.videoData.isLivePlayback,target:"new",value:ERD(v.action)}),onClickCommand:null};z_(L,m)}}}}}L.B++},Zi=function(L,m,n){for(var C=-1,Z=-1,z=0;z<L.length;z++){if(L[z].height===
m||L[z].width===n)return L[z];
((L[z].height||0)<m||(L[z].width||0)<n)&&(C<0||(L[C].height||0)<(L[z].height||0)||(L[C].width||0)<(L[z].width||0))?C=z:((L[z].height||0)>=m||(L[z].width||0)>=n)&&(Z<0||(L[Z].height||0)>(L[z].height||0)||(L[Z].width||0)>(L[z].width||0))&&(Z=z)}return L[Z>=0?Z:C]},vs=function(L,m,n,C){return{feature:n.feature?n.feature:"cards",
src_vid:L.context.videoData.videoId,annotation_id:m,ei:L.context.videoData.eventId||"",itct:C.trackingParams||""}},iSJ=function(L,m){if(m=VX_(L,m))m===L.W&&(L.W=null),L.U.removeCueRange(m.fX.id),g.wr(m.LC),g.SZ(L.cards,m),L.oK(),Ea(L)},no=function(L,m,n){if(!L.G){L.fI.show();
L.Hv=new g.jW(function(){g.Ei(L.context.U.getRootNode(),g.J3.IV_DRAWER_OPEN)},0);
L.Hv.start();L.Qd.j(L.J,"mousewheel",function(v){L.aj.start();v.preventDefault();v=v||window.event;var X=0;v.type=="MozMousePixelScroll"?X=0==(v.axis==v.HORIZONTAL_AXIS)?v.detail:0:window.opera?X=v.detail:X=v.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?v.wheelDeltaY/-30:v.wheelDeltaY/-1.2:v.wheelDelta/-1.6:v.wheelDeltaY/-3;if(v=X)L.J.scrollTop+=v});
L.G=!0;var C=g.gC();C&&L.KI&&L.C&&g.cb(C,[L.KI,L.C]);m={TRIGGER_TYPE:m};for(var Z=g.M(L.cards),z=Z.next();!z.done;z=Z.next())z=z.value,z.uc||(z.uc=!0,$JJ(L.context.logger,z.fX.zJ.O3,m)),C&&g.cb(C,[z.fX.Hh]);UX(L.U);n&&(L.S=new g.jW(function(){L.SD=L.K;L.wx.focus()},330),L.S.start())}},Co=function(L){L.G&&(L.fI.hide(),g.tT(L.Qd),g.N8(L.context.U.getRootNode(),g.J3.IV_DRAWER_OPEN),L.G=!1,UX(L.U),L.S&&L.S.stop(),L.S=new g.jW(function(){L.SD&&(L.SD.focus(),L.SD=null)},330),L.S.start())},aYp=function(L){g.XX(L.Z0(),
[g.J3.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.Zq(L.U,L.L,5);L.Nq();L.K=g.N4("ytp-cards-button",L.U.getRootNode());L.wx=g.N4("iv-drawer-close-button",L.L);L.isInitialized=!0},qp1=function(L){L.wd.push(g.ci("iv-teaser-shown",L.Gl,L));
L.wd.push(g.ci("iv-teaser-hidden",L.MDd,L));L.wd.push(g.ci("iv-teaser-clicked",L.zl,L));L.Lu=!0},DJr=function(L,m){var n;
return m.onClickCommand&&((n=g.k(m.onClickCommand,g.Hu0))==null?void 0:n.targetId)==="engagement-panel-error-corrections"?(L.Je=m,!0):!1},OSr=function(L,m){L.Je=m;
var n=L.U.getVideoData();if(!n)return!1;n=g.vH(n);if(n==null?0:n.markersMap)for(var C,Z=0;((C=n)==null?void 0:C.markersMap.length)>Z;Z++){var z=void 0,v=(z=n)==null?void 0:z.markersMap[Z];if(v.key==="ERROR_CORRECTION_MARKERS"&&(z=void 0,(v=(z=v.value)==null?void 0:z.markers)&&v.length>0))return C=void 0,m.startMs=((C=g.k(v[0],g.Ved))==null?void 0:C.timeRangeStartMillis)||0,L.Je=null,!0}return!1},z_=function(L,m){if(!DJr(L,m)||OSr(L,m)){var n=lY$(L,m);
if(n){var C={fX:m,LC:n.element,uc:!1};if(m.onClickCommand)L.U.N("web_infocards_teaser_show_logging_fix")&&(L.Lu||qp1(L),iSJ(L,m.id),n=L.findLastIndex(C),g.rH(L.cards,n,0,C));else{L.isInitialized||aYp(L);iSJ(L,m.id);var Z=L.findLastIndex(C);g.rH(L.cards,Z,0,C);n.sN(L.J,Z);L.oK()}m.autoOpen?L.addCueRange(m.startMs,0x8000000000000,m.id,function(){L.G||(L.W=C,Ea(L),R1z(L,C),no(L,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(n=L.context.U.getCurrentTime()*1E3,n<5E3&&n>m.startMs&&wxz(L,C),L.addCueRange(m.startMs,
m.startMs+1,m.id,function(){wxz(L,C)}),Ea(L))}}},lY$=function(L,m){switch(m.type){case "simple":L=L.LI;
var n=m.displayDomain?{Z:"div",T:"iv-card-image-text",zo:m.displayDomain}:void 0;var C=CNp(m);n={Z:"div",xU:["iv-card"],V:[{Z:"a",T:"iv-click-target",Y:{href:m.url?KY(m.url)||"":""},V:[jM(m.imageUrl,n),{Z:"div",T:"iv-card-content",V:[yN("h2",void 0,m.title),C]}]}]};n=new g.H(n);oq(L,g.EY("iv-click-target",n.element),m,m.url);m=n;break;case "collaborator":L=L.LI;n={Z:"div",xU:["iv-card","iv-card-channel"],V:[{Z:"a",xU:["iv-click-target"],Y:{href:KY(m.url)||"","data-ytid":m.channelId},V:[jM(m.profileImageUrl),
{Z:"div",T:"iv-card-content",V:[mJ0(m),{Z:"h2",T:"iv-card-primary-link",zo:m.title},nRF(m)]}]}]};n=new g.H(n);oq(L,g.EY("iv-click-target",n.element),m,m.url);m=n;break;case "playlist":L=L.LI;n={Z:"div",xU:["iv-card","iv-card-playlist"],V:[{Z:"a",T:"iv-click-target",Y:{href:KY(m.url)||""},V:[jM(m.ZR,{Z:"div",T:"iv-card-image-overlay",V:[{Z:"span",T:"iv-card-playlist-video-count",zo:m.playlistVideoCount}]}),{Z:"div",T:"iv-card-content",V:[mJ0(m),yN("h2","iv-card-primary-link",m.title),nRF(m)]}]}]};
n=new g.H(n);oq(L,g.EY("iv-click-target",n.element),m,m.url);m=n;break;case "productListing":L=L.LI;var Z=m.offers.length!=0;n=["iv-card"];C="";var z=CNp(m);Z&&(n.push("iv-card-product-listing"),C="iv-card-primary-link",z=m.offers[0],Z=[],z.price&&Z.push({Z:"div",T:"iv-card-offer-price",zo:z.price}),z.merchant&&Z.push({Z:"div",T:"iv-card-offer-merchant",zo:z.merchant}),z={Z:"div",V:Z});Z=m.url?KY(m.url)||"":"";n={Z:"div",xU:n,Y:{tabindex:"0"},V:[{Z:"a",xU:["iv-card-image","iv-click-target"],Y:{style:"background-image: url("+
m.imageUrl+");",href:Z,"aria-hidden":"true",tabindex:"-1"}},{Z:"div",T:"iv-card-content",V:[m.sponsored?{Z:"div",T:"iv-card-sponsored",V:["Sponsored",{Z:"div",T:"iv-ad-info-container",V:[{Z:"div",T:"iv-ad-info",zo:"{{adInfo}}"},{Z:"div",T:"iv-ad-info-icon-container",V:[{Z:"div",T:"iv-ad-info-icon"},{Z:"div",T:"iv-ad-info-callout"}]}]}]}:"",{Z:"a",T:"iv-click-target",Y:{href:Z},V:[yN("h2",C,m.title),z]}]}]};n=new g.H(n);C=g.q4("span");g.IL(C,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
n.YD(C,"adInfo");oq(L,g.EY("iv-click-target",n.element),m,m.url);m=n;break;case "video":L=L.LI;C=m.videoDuration?{Z:"span",T:"iv-card-video-duration",zo:m.videoDuration}:void 0;z=m.isLiveNow?{Z:"span",xU:["yt-badge","yt-badge-live"],zo:"LIVE NOW"}:null;Z={Z:"div",xU:["iv-card","iv-card-video"],V:[{Z:"a",T:"iv-click-target",Y:{href:((n=m.url)==null?void 0:KY(n))||""},V:[jM(m.ZR,C),{Z:"div",T:"iv-card-content",V:[mJ0(m),yN("h2","iv-card-primary-link",m.title),nRF(m),z]}]}]};n=new g.H(Z);oq(L,g.EY("iv-click-target",
n.element),m,m.url);m=n;break;default:return null}return m},e11=function(L){if(L.W)return L.W.fX.type==="productListing";
if(L.U.N("enable_wn_infocards")){var m;return!((m=L.cards)==null||!m.length)&&g.Rg(L.cards,function(n){return n.fX.type==="productListing"})}return g.Rg(L.cards,function(n){return n.fX.type==="productListing"})},Ea=function(L){g.VR(L.U.getRootNode(),"ytp-cards-shopping-active",e11(L))},wxz=function(L,m){if(!g.vu(L.U.getRootNode(),"ytp-cards-teaser-shown")){if(L.W!==m){var n=g.gC(),C=L.W?L.W.fX.IU:L.IU;
n&&C&&g.LD(n,[C]);L.W=m;Ea(L)}(n=L.isInitialized&&L.Z0().style.display=="none")||(n=L.context.U.getPlayerState(),C=n===0&&L.context.U.getCurrentTime()===0,n=!(n===1||n===3||C));if(!n&&m.fX.teaserDurationMs){var Z;n={teaserText:m.fX.teaserText,durationMs:m.fX.teaserDurationMs,onClickCommand:m.fX.onClickCommand,RM:(Z=m.fX.RM)!=null?Z:null};L.U.JW(!0,n)}L.CI.isActive()||((!L.G||!L.aj.isActive()&&L.rd)&&R1z(L,m),L.CI.start(910+m.fX.teaserDurationMs))}},R1z=function(L,m){L.X.ij?(m=new pY([0,
L.J.scrollTop],[0,m.LC.offsetTop],600,Anw),L.context.G.listen(m,"animate",function(n){L.J.scrollTop=n.y}),L.context.G.listen(m,"finish",function(n){L.J.scrollTop=n.y}),m.play()):(L.X.fu(!0),L.J.scrollTop=m.LC.offsetTop,L.X.fu(!1))},X5=function(L){return L.W&&L.W.fX?L.W.fX:L.cards[0]&&L.cards[0].fX?L.cards[0].fX:null},VX_=function(L,m){return g.wH(L.cards,function(n){return n.fX.id===m})},NS=function(L,m,n){cc.call(this,L,m);
this.annotation=n;this.isActive=!1},gR0=function(L){var m=L.annotation.data;
"start_ms"in m&&"end_ms"in m&&L.addCueRange(Number(m.start_ms),Number(m.end_ms),L.annotation.id,function(){L.show()},function(){L.hide()})},T_=function(L,m,n){NS.call(this,L,m,n);
this.J=null;this.B=!1;this.G=null;this.L=!1;this.W=this.S=this.K=null},MXD=function(L,m){var n=n===void 0?0:n;
var C=lmZ(m).width;g.oL(m,C);n=new Iml(m,[C,m.offsetTop],[C-C-n,m.offsetTop],200,JnD);g.h(L,n);L.context.G.listen(n,"begin",function(){g.ZZ(m,!0)});
n.play()},JY0=function(L,m){if(m.channel_name){var n=L.createElement({Z:"div",
xU:["iv-branding-context-name"],zo:m.channel_name}),C=L.createElement({Z:"div",xU:["iv-branding-context-subscribe"]}),Z=m.standalone_subscribe_button_data;Z&&(L.W=new g.zm(Z.subscribeText,Z.subscribeCount,Z.unsubscribeText,Z.unsubscribeCount,!!Z.enabled,!!Z.classic,m.channel_id,!!Z.subscribed,Z.feature,m.session_data.itct,L.context.U,!1),L.W.sN(C));var z=L.createElement({Z:"div",xU:["iv-branding-context-subscribe-caret"]}),v=L.createElement({Z:"div",xU:["branding-context-container-inner"]});v.appendChild(z);
v.appendChild(n);v.appendChild(C);g.ZZ(v,!1);var X=L.createElement({Z:"div",xU:["branding-context-container-outer"]});X.appendChild(v);g.GB(X,"right",m.image_width+"px");g.OY(L.Z0(),X);L.G=new g.jW(function(){Spw(L,v,X)},500);
g.h(L,L.G);L.context.W.listen(L.Z0(),"mouseover",function(){IYJ(L,v,X,z,m.image_height)});
L.context.W.listen(L.Z0(),"mouseout",function(){L.G.start()})}},IYJ=function(L,m,n,C,Z){L.G.stop();
if(!L.L){var z=g.C6(m);L.W||(m.style.width=g.jy(z.width,!0),n.style.width=g.jy(z.width,!0));g.GB(C,"top",z.height-Math.max(Math.min(z.height,Z)/2+10,20)+"px");g.GB(C,"right","1px");L.L=!0;g.ZZ(m,!0);L.K=new g.jW(function(){g.Ei(this.Z0(),"iv-branding-active")},0,L);
L.K.start()}},Spw=function(L,m,n){g.N8(L.Z0(),"iv-branding-active");
L.S=new g.jW(function(){g.ZZ(m,!1);L.W||(n.style.width=g.jy(0,!0))},250);
L.S.start();L.L=!1},AYp=function(L,m,n,C,Z,z,v){this.W=L;
this.G=m;this.yd=n;this.videoData=C;this.logger=Z;this.U=z;this.J=v},bSD=function(L,m,n){NS.call(this,L,m,n);
var C=this;this.C=this.isCollapsed=this.X=!1;this.S=5E3;this.J=this.G=this.W=this.L=null;this.B=this.createElement({Z:"div",xU:["iv-promo-contents"]});this.K=new g.jW(function(){C.W.setAttribute("aria-hidden","true");g.ZZ(C.G,!1);g.ZZ(C.J,!0)},700,this);
g.h(this,this.K)},fY$=function(L){var m=L.annotation.data;
if(L.annotation.style==="cta")var n=6;else if(L.annotation.style==="video"||L.annotation.style==="playlist")n=7;L.S=m.collapsedelay_ms||L.S;var C=["iv-promo","iv-promo-inactive"];L.Z0().setAttribute("aria-hidden","true");L.Z0().setAttribute("aria-label","Promotion");L.Z0().tabIndex=0;var Z=L.annotation.xO(),z=m.image_url;if(z){var v=L.createElement({Z:"div",xU:["iv-promo-img","iv-click-target"]});z=L.createElement({Z:"img",Y:{src:z,"aria-hidden":"true"}});v.appendChild(z);m.video_duration&&!m.is_live?
(z=L.createElement({Z:"span",T:"iv-promo-video-duration",zo:m.video_duration}),v.appendChild(z)):m.playlist_length&&(z=L.createElement({Z:"span",T:"iv-promo-playlist-length",zo:m.playlist_length.toString()}),v.appendChild(z));Z&&Lo(L,v,Z,L.annotation.id,m.session_data,void 0,n)}Z?(z=L.createElement({Z:"a",T:"iv-promo-txt"}),g.VU(z,KY(Z)),L.W=z):L.W=L.createElement({Z:"div",T:"iv-promo-txt"});switch(L.annotation.style){case "cta":case "website":var X=L.createElement({Z:"p",V:[{Z:"strong",zo:m.text_line_1}]});
var N=L.createElement({Z:"p",V:[{Z:"span",T:"iv-promo-link",zo:m.text_line_2}]});if(z=m.text_line_3){C.push("iv-promo-website-card-cta-redesign");var T=L.createElement({Z:"button",xU:["iv-promo-round-expand-icon","ytp-button"]});z=L.createElement({Z:"button",xU:["iv-button","iv-promo-button"],V:[{Z:"span",T:"iv-button-content",zo:z}]});var V=L.createElement({Z:"div",T:"iv-promo-button-container"});V.appendChild(z);Z&&Lo(L,L.Z0(),Z,L.annotation.id,m.session_data,void 0,n)}g.Ei(L.W,"iv-click-target");
Z&&Lo(L,L.W,Z,L.annotation.id,m.session_data,void 0,n);break;case "playlist":case "video":X=L.createElement({Z:"p",V:[{Z:"span",zo:m.text_line_1}]}),N=L.createElement({Z:"p",V:[{Z:"strong",zo:m.text_line_2}]}),m.is_live&&(X=N,N=L.createElement({Z:"span",xU:["yt-badge","iv-promo-badge-live"],zo:"LIVE NOW"})),g.Ei(L.W,"iv-click-target"),Z&&Lo(L,L.W,Z,L.annotation.id,m.session_data,void 0,n),C.push("iv-promo-video")}X&&L.W.appendChild(X);N&&L.W.appendChild(N);L.B.appendChild(L.W);V&&L.B.appendChild(V);
n=L.createElement({Z:"div",T:"iv-promo-actions"});L.J=L.createElement({Z:"button",xU:["iv-promo-expand","ytp-button"]});L.J.title="Expand";L.context.W.listen(L.J,"click",function(a){tXZ(L,5E3,a)});
n.appendChild(L.J);g.ZZ(L.J,!1);L.context.W.listen(L.Z0(),"mouseover",L.Kl,L);L.context.W.listen(L.Z0(),"mouseout",L.ZQ,L);L.context.W.listen(L.Z0(),"touchend",function(a){tXZ(L,5E3,a)});
L.G=L.createElement({Z:"button",xU:["iv-promo-close","ytp-button"]});L.G.title="Close";L.context.W.listen(L.G,"click",L.annotation.style==="cta"&&m.text_line_3?L.Ll:L.bB,L);n.appendChild(L.G);g.XX(L.Z0(),C);v&&(g.OY(L.Z0(),v),T&&v.appendChild(T));g.OY(L.Z0(),L.B);g.OY(L.Z0(),n)},tXZ=function(L,m,n){n.stopPropagation();
UJl(L);BXF(L,m);L.W.focus()},PNZ=function(L){L.isCollapsed||L.C||L.L||(g.Ei(L.Z0(),"iv-promo-collapsed"),L.isCollapsed=!0,L.K.start())},UJl=function(L){L.K.stop();
L.isCollapsed&&(g.T2(L.Z0(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),L.isCollapsed=!1,L.W&&L.W.removeAttribute("aria-hidden"),g.ZZ(L.J,!1),g.ZZ(L.G,!0))},BXF=function(L,m){L.L||(L.L=g.uS(function(){sf_(this);
PNZ(this)},m,L))},sf_=function(L){L.L&&(g.oU.clearTimeout(L.L),L.L=null)},Qfo=function(L){this.U=L},$JJ=function(L,m,n){m&&(n?Vo(L,m.map(function(C){return g.t9(C,n)})):Vo(L,m))},Vo=function(L,m,n,C){var Z=1,z=void 0,v=-1;
if(n){var X=!1;z=function(){Z--;Z||X||(clearTimeout(v),X=!0,n())};
v=setTimeout(function(){X=!0;n()},1E3)}m=g.M(m||[]);
for(var N=m.next();!N.done;N=m.next())N=N.value,Z++,g.s0(N,z);C&&(Z++,C!==0&&L.U.sendVideoStatsEngageEvent(C,z))},uSF=function(L){g.S2.call(this,L);
var m=this;this.wd=this.C=!1;this.loadNumber=0;this.S={};this.logger=new Qfo(this.player);this.L=new g.tC(this);this.K=this.B=null;this.events=new g.tC(this);this.jo=this.X=this.W=null;this.Je=[];g.h(this,this.L);this.L.j(this.player,"onVideoAreaChange",function(){m.publish("onVideoAreaChange")});
this.L.j(this.player,"onHideControls",function(){m.publish("onHideControls")});
this.L.j(this.player,"onShowControls",function(){m.publish("onShowControls")});
this.L.j(this.player,"resize",function(z){m.publish("resize",z)});
this.L.j(this.player,"presentingplayerstatechange",function(z){m.publish("presentingplayerstatechange",z)});
this.subscribe("presentingplayerstatechange",this.bd,this);this.subscribe("resize",this.h2,this);this.player.D().rd.subscribe("vast_info_card_add",this.cJ,this);g.h(this,this.events);this.LI=this.createElement({Z:"div",T:"video-custom-annotations"});this.J=new g.H({Z:"div",xU:["ytp-player-content","ytp-iv-player-content"]});g.h(this,this.J);g.Zq(this.player,this.J.element,4);this.J.hide();this.G=new g.H({Z:"div",xU:["ytp-iv-video-content"]});g.h(this,this.G);L=this.createElement({Z:"div",T:"video-annotations"});
L.appendChild(this.LI);this.G.element.appendChild(L);this.fF()&&this.load();var n=this.createElement({Z:"style"});(g.v0("HEAD")[0]||document.body).appendChild(n);this.addOnDisposeCallback(function(){g.wr(n)});
if(L=n.sheet){for(var C=g.M(pxl),Z=C.next();!Z.done;Z=C.next())L.insertRule(Z.value,0);C=g.M(F6$);for(Z=C.next();!Z.done;Z=C.next())L.insertRule(Z.value,0)}},h1p=function(L){L=L.createElement({Z:"div",
xU:["annotation","annotation-type-custom"]});g.ZZ(L,!1);return L},GvZ=function(L,m){function n(v){var X=L.loadNumber;
L.K=null;L.loaded&&L.loadNumber===X&&L.player.getVideoData().videoId===C&&(v=g.$r(v)&&v.responseXML?v.responseXML:null)&&(rYH(L,v),g.Ei(L.player.getRootNode(),"iv-module-loaded"))}
var C=m.videoId;g.o4()&&(n=kvf(L,n));var Z={format:"XML",onFinish:n,onError:function(){L.K=null},
urlParams:{}};m.isPharma&&(Z.urlParams.pharma="1");Z.method="POST";Z.withCredentials=!0;var z=L.player.D().rd.get(C);z&&(Math.random()<g.Ee(L.player.D().experiments,"annotation_module_vast_cards_load_logging_fraction")&&g.U$(new g.YZ("Unexpected call to loadVastInfoCards; VastInfoCard exists.")),HS1(Z,z));z=z&&(z.nC||z.Vl);if(!m.n2||z)m.Qd?(Math.random()<g.Ee(L.player.D().experiments,"annotation_module_vast_cards_load_logging_fraction")&&g.U$(new g.YZ("Unexpected call to loadVastInfoCards; Attempting to load annotations via invideo URL.")),
Ypr(L,m.Qd,Z)):(L.B=function(){if(!L.C)L.onVideoDataChange(Z);var v=L.player.getVideoData();(v==null?0:g.Ns(v))&&!L.wd&&W6F(L,v)},L.player.addEventListener("videodatachange",L.B))},dJZ=function(L,m){m=!m.isCued()&&!g.d(m,1024);
L.J.fu(m);L.G.fu(m)},Ypr=function(L,m,n){L.C=!0;
L.K=g.IT(m,n)},K6$=function(L,m){for(var n={},C=g.M(m.attributes),Z=C.next();!Z.done;Z=C.next())Z=Z.value,n[Z.name]=Z.nodeValue;
for(C=0;C<m.childNodes.length;C++)if(Z=m.childNodes[C],g.z0(Z)&&Z.nodeType==1){if(n[Z.tagName])var z=n[Z.tagName];else if(Z.tagName==="data"){Z.childNodes.length>0&&(z=Z.childNodes[0].nodeValue,n[Z.tagName]=typeof z==="string"?z.trim():z);continue}else z=[],n[Z.tagName]=z;Z&&Z.tagName==="TEXT"?Z.childNodes.length===1&&Z.childNodes[0].nodeType===3?z.push(Z.childNodes[0].nodeValue):z.push(""):Z&&z.push(K6$(L,Z))}return n},xJ0=function(L){var m=L.player.getVideoData();
if(m.Qd){var n=L.player.D().rd.get(m.videoId);if(n){var C={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(Z,z,v){Z=L.loadNumber;z=m.videoId;L.loaded&&L.loadNumber===Z&&L.player.getVideoData().videoId===z&&(v=g.$r(v)&&v.responseXML?v.responseXML:null)&&rYH(L,v)}};
g.o4()&&(C.onFinish=kvf(L,C.onFinish));C.postParams={ic_only:"1"};HS1(C,n);L.C=!0;g.IT(m.Qd,C)}}},HS1=function(L,m){L.method="POST";
L.postParams=L.postParams||{};m.Vl&&(L.postParams.ic_coll=m.Vl);m.nC&&(L.postParams.ic_xml=m.nC);m.xB&&(L.postParams.ic_track=m.xB)},yYo=function(L){var m=new g.H({Z:"div"});
g.ZZ(m.element,!1);var n=new XxF(L.player,m.element,iG(L));g.h(n,m);m.sN(L.J.element);n.dG();return n},W6F=function(L,m){var n,C;
if(m=(n=m.getWatchNextResponse())==null?void 0:(C=n.cards)==null?void 0:C.cardCollectionRenderer)L.wd=!0,jfr(L,m),m.headerText&&L.jo&&(n=g.$5(m.headerText),L.player.N("player_tooltip_data_title_killswitch")?L.jo.setAttribute("title",n):L.jo.setAttribute("data-tooltip-title",n))},iG=function(L){if(!L.X){var m=new blz(L);
g.h(L,m);var n=new g.DK(L);g.h(L,n);L.X=new AYp(m,n,L.player.D(),L.player.getVideoData(),L.logger,L.player,L.J4)}return L.X},rYH=function(L,m){var n=!1,C=m.getElementsByTagName("annotations");
if(C&&!(C.length<1)&&(C=C[0].getAttribute("itct"))){var Z=g.gC();if(Z){var z=g.eB();z&&g.jb(g.Hb)(void 0,Z,z,[g.Rh(C)])}}m=m.getElementsByTagName("annotation");for(C=0;C<m.length;C++){z=K6$(L,m[C]);Z=null;try{if(z){var v=z.id,X=/.+/;var N=typeof v==="string"&&X!=null&&v!=null&&v.match(X)?v:"";var T=dv(z.type,oRF),V=dv(z.style,cYl),a=WkF(z.data),q=a.length!==0?JSON.parse(a):{};var D=z.action;z=j3H;if(D==null)var O=null;else if(g.Zo(D)){X=[];for(var e=g.M(D),I=e.next();!I.done;I=e.next()){var t=z(I.value);
t&&X.push(t)}O=X}else{var b=z(D);O=b?[b]:[]}Z=N&&T?new ok_(N,T,V,O,q):null}else Z=null}catch(Ed){}if(Z)if(Z.type==="branding"||Z.type==="promotion"){z=L;X=Z;var P=h1p(z),F=null;switch(X.type){case "branding":if(z.player.D().Bc)break;z.player.N("web_player_overlay_positioned_layout")?(P.setAttribute("data-overlay-order","11"),z.player.gq(P,4,!0)):z.J.element.appendChild(P);F=new T_(P,iG(z),X);break;case "promotion":g.Zq(z.player,P,4),F=new bSD(P,iG(z),X)}F&&F.dG();if(z=F)g.h(L,z),L.S[Z.id]=z}else if(Z.type===
"card"||Z.type==="drawer"){L.W||(L.W=yYo(L),g.h(L,L.W));if(Z.type==="card"){P=L.W;var r=(n=Z)&&n.data&&n.data.card_type;Z=n.data;if(r)switch(z=Z.tracking||{},z={O3:z.impression,click:z.click,close:z.close,We:z.teaser_impression,Zu:z.teaser_click},X=Z.tracking_params||{},F=null,r){case "collaborator":n={id:n.id,timestamp:Z.timestamp||0,type:Z.card_type,teaserText:Z.teaser_text,teaserDurationMs:Z.teaser_duration_ms,startMs:Z.start_ms,autoOpen:Z.auto_open||!1,sessionData:Z.session_data||{},sponsored:Z.sponsored||
!1,zJ:z,Hh:X.card?g.Rh(X.card):null,VY:X.teaser?g.Rh(X.teaser):null,IU:X.icon?g.Rh(X.icon):null,channelId:Z.channel_id,customMessage:Z.custom_message?Z.custom_message:null,profileImageUrl:Z.image_url,title:Z.title,metaInfo:Z.meta_info,url:xn({pause_on_navigation:Z.pause_on_navigation,target:Z.target||"new",value:Z.url}),onClickCommand:null};z_(P,n);break;case "playlist":n={id:n.id,timestamp:Z.timestamp||0,type:Z.card_type,teaserText:Z.teaser_text,teaserDurationMs:Z.teaser_duration_ms,startMs:Z.start_ms,
autoOpen:Z.auto_open||!1,sessionData:Z.session_data||{},sponsored:Z.sponsored||!1,zJ:z,Hh:X.card?g.Rh(X.card):null,VY:X.teaser?g.Rh(X.teaser):null,IU:X.icon?g.Rh(X.icon):null,ZR:Z.image_url,playlistVideoCount:Z.playlist_video_count,customMessage:Z.custom_message?Z.custom_message:null,title:Z.title,metaInfo:Z.meta_info,url:xn({pause_on_navigation:Z.pause_on_navigation,target:Z.target||"new",value:Z.url}),onClickCommand:null};z_(P,n);break;case "productListing":Z.signin_url&&(F=xn({target:"current",
value:Z.signin_url}));r=[];for(var x=Z.offers||[],Y=0;Y<x.length;Y++)r.push(new ZS0(g.Br(x[Y].merchant),g.Br(x[Y].price)));n={id:n.id,timestamp:Z.timestamp||0,type:Z.card_type,teaserText:Z.teaser_text,teaserDurationMs:Z.teaser_duration_ms,startMs:Z.start_ms,autoOpen:Z.auto_open||!1,sessionData:Z.session_data||{},sponsored:Z.sponsored||!1,zJ:z,Hh:X.card?g.Rh(X.card):null,VY:X.teaser?g.Rh(X.teaser):null,IU:X.icon?g.Rh(X.icon):null,imageUrl:Z.image_url,displayDomain:Z.display_domain?Z.display_domain:
null,showLinkIcon:!!Z.show_link_icon,RZ:Z.button_icon_url?Z.button_icon_url:null,title:Z.title,customMessage:Z.custom_message?Z.custom_message:null,url:xn({pause_on_navigation:Z.pause_on_navigation,target:Z.target||"new",value:Z.url}),GzK:F,zNo:Z.signin_title?Z.signin_title:void 0,JgN:Z.signin_message?Z.signin_message:void 0,offers:r,onClickCommand:null};z_(P,n);break;case "simple":n={id:n.id,timestamp:Z.timestamp||0,type:Z.card_type,teaserText:Z.teaser_text,teaserDurationMs:Z.teaser_duration_ms,
startMs:Z.start_ms,autoOpen:Z.auto_open||!1,sessionData:Z.session_data||{},sponsored:Z.sponsored||!1,zJ:z,Hh:X.card?g.Rh(X.card):null,VY:X.teaser?g.Rh(X.teaser):null,IU:X.icon?g.Rh(X.icon):null,imageUrl:Z.image_url,displayDomain:Z.display_domain?Z.display_domain:null,showLinkIcon:!!Z.show_link_icon,RZ:Z.button_icon_url?Z.button_icon_url:null,title:Z.title,customMessage:Z.custom_message?Z.custom_message:null,url:xn({pause_on_navigation:Z.pause_on_navigation,target:Z.target||"new",value:Z.url}),onClickCommand:null};
z_(P,n);break;case "video":n={id:n.id,timestamp:Z.timestamp||0,type:Z.card_type,teaserText:Z.teaser_text,teaserDurationMs:Z.teaser_duration_ms,startMs:Z.start_ms,autoOpen:Z.auto_open||!1,sessionData:Z.session_data||{},sponsored:Z.sponsored||!1,zJ:z,Hh:X.card?g.Rh(X.card):null,VY:X.teaser?g.Rh(X.teaser):null,IU:X.icon?g.Rh(X.icon):null,ZR:Z.image_url,videoDuration:Z.video_duration||null,customMessage:Z.custom_message?Z.custom_message:null,title:Z.title,metaInfo:Z.meta_info,isLiveNow:!!Z.is_live_now,
url:xn({pause_on_navigation:Z.pause_on_navigation,target:Z.target||"new",value:Z.url}),onClickCommand:null},z_(P,n)}}else NX$(L.W,Z);n=!0}}n&&(UX(L.player),L.h2())},jfr=function(L,m){var n=!1;
L.W||(L.W=yYo(L),g.h(L,L.W));for(var C=g.M(m.cards||[]),Z=C.next();!Z.done;Z=C.next())Z=Z.value,Z.cardRenderer&&(TXf(L.W,Z.cardRenderer),n=!0);if(n){var z;(z=L.player.getVideoData())!=null&&g.Ns(z)||(n=L.W,C=m.headerText?g.$5(m.headerText):"",g.IL(n.bj,C),n.K&&(n.U.N("player_tooltip_data_title_killswitch")?n.K.setAttribute("title",C):n.K.setAttribute("data-tooltip-title",C)),n.context.videoData.eventId&&(n.eventId=n.context.videoData.eventId),n.KI=m.trackingParams?g.Rh(m.trackingParams):null,n.C=
m.closeButton.infoCardIconRenderer.trackingParams?g.Rh(m.closeButton.infoCardIconRenderer.trackingParams):null,n.IU=m.icon.infoCardIconRenderer.trackingParams?g.Rh(m.icon.infoCardIconRenderer.trackingParams):null,L.h2());UX(L.player)}},kvf=function(L,m){return function(){var n=g.ug.apply(0,arguments);
L.FK()||L.Je.push(g.Ya.PR(function(){m.apply(null,g.q3(n))}))}},Lvf=function(L){return L==="annotation-editor"||L==="live-dashboard"};
g.yE.prototype.JW=g.za(39,function(L,m){var n=g.py(this.UK());n&&n.JW(L,m)});
var Pc={},sX=null;g.ql(pY,g.iz);g.l=pY.prototype;g.l.getDuration=function(){return this.duration};
g.l.play=function(L){if(L||this.W==0)this.progress=0,this.coords=this.J;else if(this.isPlaying())return!1;QN(this);this.startTime=L=g.$_();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.L=this.startTime;this.progress||this.xq();this.gr("play");this.isPaused()&&this.gr("resume");this.W=1;var m=g.Er(this);m in Pc||(Pc[m]=this);eQw();gkf(this,L);return!0};
g.l.stop=function(L){QN(this);this.W=0;L&&(this.progress=1);MQr(this,this.progress);this.onStop();this.nD()};
g.l.pause=function(){this.isPlaying()&&(QN(this),this.W=-1,this.gr("pause"))};
g.l.Go=function(){this.W==0||this.stop(!1);this.gr("destroy");pY.w$.Go.call(this)};
g.l.destroy=function(){this.dispose()};
g.l.d8=function(){this.gr("animate")};
g.l.gr=function(L){this.dispatchEvent(new SLw(L,this))};
g.ql(SLw,g.Kq);g.ql(Fh,pY);Fh.prototype.G=function(){};
Fh.prototype.d8=function(){this.G();Fh.w$.d8.call(this)};
Fh.prototype.nD=function(){this.G();Fh.w$.nD.call(this)};
Fh.prototype.xq=function(){this.G();Fh.w$.xq.call(this)};
g.ql(Iml,Fh);Iml.prototype.G=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.R(blz,g.u);g.l=blz.prototype;g.l.listen=function(L,m,n,C){n=(0,g.Nl)(n,C||this.J);L=g.ge(L,m,n);this.W.push(L);return L};
g.l.GP=function(L,m,n,C){n=(0,g.Nl)(n,C||this.J);L=RQZ(L,m,n);this.W.push(L);return L};
g.l.rV=function(L){g.MP(L);g.SZ(this.W,L)};
g.l.removeAll=function(){g.MP(this.W);this.W.length=0};
g.l.Go=function(){this.removeAll();g.u.prototype.Go.call(this)};g.R(UQl,g.S2);g.l=UQl.prototype;g.l.load=function(){g.S2.prototype.load.call(this);if(!rv(this)){var L=g.n3P(this.player.getVideoData());L?(L=fmp(L,BdF(this)),kn(this,L,!1)):PcH(this)}};
g.l.unload=function(){kn(this,null);this.L&&(this.L.abort(),this.L=null);g.S2.prototype.unload.call(this)};
g.l.Ch=function(L,m){return rv(this)?L==="loadCustomEndscreenRenderer"?(L=fmp(m,"new"),kn(this,L),!0):null:null};
g.l.getOptions=function(){return rv(this)?["loadCustomEndscreenRenderer"]:[]};
g.l.VH=function(){if(this.endscreen&&this.endscreen.elements){var L=this.player.getVideoContentRect();if(L&&L.width!==0&&L.height!==0){var m=this.player.getPlayerSize();if(m&&m.width!==0&&m.height!==0){var n=L.width/L.height;var C=0;for(var Z=-1,z=0;z<mn$.length;z++){var v=Math.abs(m.width-mn$[z]);if(Z===-1||C>=v)Z=z,C=v}C=nX1[Z];this.G&&g.GB(this.G.element,"outline-width",Math.max(m.width,m.height)+"px");for(m=0;m<this.endscreen.elements.length;++m)if(z=this.endscreen.elements[m].id,Z=this.J[z],
v=this.S[z],Z&&v){var X=v.width*n/v.aspectRatio,N=Math.round(v.width*L.width);z=Math.round(X*L.height);var T=L.left+Math.round(v.left*L.width),V=L.top+Math.round(v.top*L.height);g.n6(Z.element,N,z);g.oL(Z.element,T,V);g.T2(Z.element,C0p);N>256||z>256?g.Ei(Z.element,"ytp-ce-large-round"):N>96||z>96?g.Ei(Z.element,"ytp-ce-medium-round"):g.Ei(Z.element,"ytp-ce-small-round");g.T2(Z.element,Ztz);N=v.left+v.width/2;v=v.top+X/2;g.Ei(Z.element,N<=.5&&v<=.5?"ytp-ce-top-left-quad":N>.5&&v<=.5?"ytp-ce-top-right-quad":
N<=.5&&v>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.T2(Z.element,nX1);g.Ei(Z.element,C);(Z=g.XE(document,"div","ytp-ce-expanding-overlay-body",Z.element)[0])&&g.GB(Z,"height",z+"px")}}}}};
g.l.onCueRangeEnter=function(L){if(this.endscreen)if(L.getId()==="ytp-ce-in-endscreen")GX(this,this.endscreen.impressionUrls),(L=g.gC())&&this.endscreen.visualElement&&g.oh(L,this.endscreen.visualElement),this.W&&(g.Ei(this.W,"ytp-ce-element-show"),this.W.removeAttribute("aria-hidden"),this.player.JY()?g.Ei(this.W,"ytp-ce-hide-button-lower"):g.N8(this.W,"ytp-ce-hide-button-lower"));else{L=L.getId().substring(15);var m=this.J[L],n=this.S[L];g.Ei(m.element,"ytp-ce-element-show");m.element.removeAttribute("aria-hidden");
m=this.player.getRootNode();g.Ei(m,"ytp-ce-shown");GX(this,n.impressionUrls);(m=g.gC())&&g.oh(m,n.visualElement);this.player.D().C&&this.player.Vd("endscreenelementshown",L)}};
g.l.onCueRangeExit=function(L){if(L.getId()==="ytp-ce-in-endscreen")this.W&&(g.N8(this.W,"ytp-ce-element-show"),this.W.setAttribute("aria-hidden","true"));else{L=L.getId().substring(15);var m=this.J[L];g.N8(m.element,"ytp-ce-element-show");m.element.setAttribute("aria-hidden","true");m=this.player.getRootNode();g.N8(m,"ytp-ce-shown");this.player.D().C&&this.player.Vd("endscreenelementhidden",L)}};
g.l.kZd=function(L){var m=this;L.target===window&&(new g.jW(function(){for(var n=g.M(Object.values(m.J)),C=n.next();!C.done;C=n.next())g.T2(C.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.l.fu=function(L){for(var m=g.M(Object.values(this.J)),n=m.next();!n.done;n=m.next())n=n.value,L?n.element.setAttribute("hidden",""):n.element.removeAttribute("hidden")};
g.l.QJN=function(L){this.W&&this.player.getRootNode().removeChild(this.W);L&&(g.Ei(L,"ytp-ce-hide-button-container"),this.W=L,g.Zq(this.player,this.W,4))};
var mn$=[346,426,470,506,570,640,853,1280,1920],nX1="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Ztz=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],C0p=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var dQz={DTU:"current",rzN:"new"};var xQr={CLOSE:"close",MbD:"openUrl",SUBSCRIBE:"subscribe"},ynH={S5U:"click",CLOSE:"close",VlD:"hidden",e9I:"rollOut",A1l:"rollOver",d8e:"shown"};ok_.prototype.xO=function(){var L=cn_(this,function(m){return m.type==="openUrl"&&m.url!=null});
return L?L.url:null};
var cYl={H4I:"anchored",Fz:"branding",CHANNEL:"channel",Y5v:"cta",qWD:"highlightText",ARZ:"label",PLAYLIST:"playlist",POPUP:"popup",whD:"speech",SUBSCRIBE:"subscribe",ZTD:"title",VIDEO:"video",I9U:"website"},oRF={Fz:"branding",aNv:"card",wFv:"drawer",dgN:"highlight",WZZ:"marker",IxU:"promotion",TEXT:"text",Tle:"widget"};var pxl=[".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}"],
F6$=[".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}"];g.R(cc,g.u);g.l=cc.prototype;g.l.addCueRange=function(L,m,n,C,Z){L=new g.oD(L,m,{id:n,namespace:"annotations_module"});C&&this.YU.set(L,C);Z&&this.pI.set(L,Z);this.context.U.Aw([L],1)};
g.l.dG=function(){this.context.J.subscribe("resize",this.oK,this)};
g.l.Z0=function(){return this.element};
g.l.qB=function(L,m,n,C,Z,z){if(this.WD)return!1;z&&(z.stopPropagation(),z.preventDefault());this.navigate(L,n,C,Z);return!1};
g.l.show=function(){};
g.l.hide=function(){};
g.l.destroy=function(){g.wr(this.Z0())};
g.l.oK=function(){};
g.l.navigate=function(L,m,n,C){var Z=this,z=KY(L);if(z){var v=vRr(z,L.target),X=function(){L.W&&Z.context.U.pauseVideo();var N=Z.context.videoData.IL||!1,T=g.Ci(z||"");N&&T&&(T.v||T.list)?Z.context.U.CF(T.v,m,T.list,!1):g.Y7(z||"",v==="current"?"_top":void 0,m)};
v==="new"&&(X(),X=null);Vo(this.context.logger,n,X,C);z1F(z)||(n=g.gC(),C=m.itct,n&&C&&g.mT(n,g.Rh(C)))}};
g.l.Go=function(){this.YU.clear();this.pI.clear();g.u.prototype.Go.call(this)};
g.l.createElement=function(L){L=new g.H(L);g.h(this,L);return L.element};g.R(XxF,cc);g.l=XxF.prototype;g.l.U1=function(){this.Je&&z_(this,this.Je)};
g.l.isAvailable=function(){var L;if(L=!!this.cards.length)(L=this.U.getRootNode())?(L=g.C6(L),L=173<L.width&&173<L.height):L=!1;return L};
g.l.oK=function(){var L=this.isAvailable();g.ZZ(this.Z0(),L);g.VR(this.context.U.getRootNode(),g.J3.IV_DRAWER_ENABLED,L);UX(this.U)};
g.l.destroy=function(){this.U.JW(!1);try{this.U.getRootNode().removeChild(this.L)}catch(L){}g.Z_(this.wd);g.tT(this.Qd);this.Hv&&this.Hv.dispose();this.S&&this.S.dispose();cc.prototype.destroy.call(this)};
g.l.Nq=function(){var L=this;this.context.W.listen(g.N4("iv-drawer-close-button",this.L),"click",this.iR,this);this.context.W.listen(this.J,"touchend",function(){L.aj.start()});
this.context.W.listen(this.J,"scroll",this.ew,this);this.context.J.subscribe("onHideControls",function(){L.rd=!0});
this.context.J.subscribe("onShowControls",function(){L.rd=!1});
this.context.J.subscribe("onVideoAreaChange",function(){L.rd=g.vu(L.U.getRootNode(),"ytp-autohide")});
this.wd.push(g.ci("iv-button-shown",this.Tdd,this));this.wd.push(g.ci("iv-button-hidden",this.Qjv,this));qp1(this)};
g.l.findLastIndex=function(L){if(this.cards.length===0)return 0;var m=g.eZ(this.cards,function(n){return L.fX.startMs>n.fX.startMs||L.fX.startMs===n.fX.startMs&&L.fX.timestamp>=n.fX.timestamp?!0:!1});
return m===-1?0:m+1};
g.l.iR=function(){if(this.G){Vo(this.context.logger,X5(this).zJ.close);var L=g.gC();L&&this.C&&g.mT(L,this.C);Co(this)}};
g.l.ew=function(){g.VR(this.L,"iv-drawer-scrolled",this.J.scrollTop>0)};
g.l.Tdd=function(){var L=g.gC(),m=X5(this);m=m?m.IU:this.IU;L&&m&&g.cb(L,[m])};
g.l.Qjv=function(){var L=g.gC(),m=X5(this);m=m?m.IU:this.IU;L&&m&&g.LD(L,[m])};
g.l.Gl=function(){var L=X5(this);Vo(this.context.logger,L.zJ.We);var m=g.gC();if(m&&L)if(this.U.N("web_infocards_teaser_show_logging_fix")){var n=[];L.VY&&n.push(L.VY);L.IU&&n.push(L.IU);n.length>0&&g.cb(m,n)}else g.cb(m,[L.VY,L.IU])};
g.l.MDd=function(){var L=g.gC(),m=X5(this);L&&m&&g.LD(L,[m.VY])};
g.l.zl=function(L){var m=X5(this),n=g.gC();this.W?L?(L=this.context.logger,Vo(L,m.zJ.Zu),L.U.sendVideoStatsEngageEvent(4,void 0),n&&m.VY&&g.mT(n,m.VY)):(L=this.context.logger,Vo(L,m.zJ.Zu),L.U.sendVideoStatsEngageEvent(4,void 0),n&&m.IU&&g.mT(n,m.IU)):(L=this.context.logger,Vo(L,m.zJ.Zu),L.U.sendVideoStatsEngageEvent(4,void 0),n&&this.IU&&g.mT(n,this.IU))};g.R(NS,cc);NS.prototype.dG=function(){cc.prototype.dG.call(this);gR0(this)};
NS.prototype.show=function(){cc.prototype.show.call(this);var L=g.gC(),m=this.annotation.data;L&&m&&(m=m.session_data)&&g.cb(L,[g.Rh(m.itct)])};
NS.prototype.hide=function(){cc.prototype.hide.call(this);var L=g.gC(),m=this.annotation.data;L&&m&&(m=m.session_data)&&g.LD(L,[g.Rh(m.itct)])};g.R(T_,NS);
T_.prototype.show=function(){if(!this.isActive){NS.prototype.show.call(this);if(!this.B){g.Ei(this.Z0(),"iv-branding");var L=this.annotation.data;this.J=this.createElement({Z:"img",xU:["branding-img","iv-click-target"],Y:{"aria-label":"Channel watermark",src:L.image_url,width:L.image_width,height:L.image_height}});g.ZZ(this.J,!1);var m=this.createElement({Z:"button",xU:["branding-img-container","ytp-button"]});m.appendChild(this.J);this.Z0().appendChild(m);var n=this.annotation.xO();n&&Lo(this,m,
n,this.annotation.id,L.session_data);this.context.U.N("disable_branding_context")||JY0(this,L);this.B=!0}g.ZZ(this.Z0(),!0);this.isActive=!0;if(this.J){try{MXD(this,this.J)}catch(C){}g.Ei(this.context.U.getRootNode(),"ytp-branding-shown");this.context.U.getRootNode().style.setProperty("--branding-image-width",this.J.getAttribute("width")+"px")}}};
T_.prototype.hide=function(){this.isActive&&(NS.prototype.hide.call(this),g.ZZ(this.Z0(),!1),this.isActive=!1,g.N8(this.context.U.getRootNode(),"ytp-branding-shown"))};
T_.prototype.destroy=function(){this.W&&(this.W.dispose(),this.W=null);g.N8(this.context.U.getRootNode(),"ytp-branding-shown");NS.prototype.destroy.call(this)};g.R(bSD,NS);g.l=bSD.prototype;g.l.show=function(){this.isActive||(NS.prototype.show.call(this),this.X||(fY$(this),this.X=!0),g.ZZ(this.Z0(),!0),g.uS(function(){g.N8(this.Z0(),"iv-promo-inactive")},100,this),this.Z0().removeAttribute("aria-hidden"),this.isActive=!0,sf_(this),UJl(this),BXF(this,this.S))};
g.l.hide=function(){this.isActive&&(g.Ei(this.Z0(),"iv-promo-inactive"),this.isActive=!1,this.Z0().setAttribute("aria-hidden","true"))};
g.l.qB=function(L,m,n,C,Z,z){return this.isCollapsed?!1:NS.prototype.qB.call(this,L,m,n,C,Z,z)};
g.l.Kl=function(L){this.C=!0;tXZ(this,500,L)};
g.l.ZQ=function(){this.C=!1;PNZ(this)};
g.l.bB=function(L){L.stopPropagation();this.hide()};
g.l.Ll=function(L){L.stopPropagation();sf_(this);this.isCollapsed=!0;g.Ei(this.Z0(),"iv-promo-collapsed-no-delay");this.K.start()};
g.l.destroy=function(){this.K.dispose();NS.prototype.destroy.call(this)};g.R(uSF,g.S2);g.l=uSF.prototype;g.l.Ch=function(L,m){if(!Lvf(this.player.D().playerStyle))return null;switch(L){case "loadCustomAnnotationsXml":return(L=g.cB(m))&&rYH(this,L),!0;case "removeCustomAnnotationById":return m&&this.W&&(iSJ(this.W,m),UX(this.player)),!0}return null};
g.l.getOptions=function(){return Lvf(this.player.D().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.l.fF=function(){var L=this.player.D(),m=this.player.getVideoData(),n=L.annotationsLoadPolicy||m.annotationsLoadPolicy;return m.IL||this.player.isMutedByEmbedsMutedAutoplay()?!1:n===1&&!m.QC||L.rd.get(m.videoId)||g.Td(m)||g.VE(m)?!0:!1};
g.l.h2=function(){if(this.G){var L=this.player.u1().getVideoContentRect(!0);g.n6(this.G.element,L.width,L.height);g.oL(this.G.element,L.left,L.top)}if(this.W){var m=this.player.s1();L=this.W;m=m.width;g.VR(L.L,"iv-drawer-small",m<=426);g.VR(L.L,"iv-drawer-big",m>=1280)}};
g.l.bd=function(L){dJZ(this,L.state);g.d(L.state,2)&&(this.JY()&&this.Tu()&&this.player.getPresentingPlayerType()!==2&&this.zW(!1),this.JW(!1))};
g.l.load=function(){g.S2.prototype.load.call(this);dJZ(this,this.player.getPlayerStateObject());this.loadNumber++;var L=this.player.getVideoData();GvZ(this,L);g.Zq(this.player,this.G.element,4);this.h2();var m=g.Td(L);m&&jfr(this,m);if((m=g.VE(L))&&m.featuredChannel){var n=m.featuredChannel;m=m.annotationId||"branding";var C=L.videoId||null,Z=L.eventId||null;if(!this.player.D().Bc){var z=[];n.navigationEndpoint&&g.k(n.navigationEndpoint,g.nK)&&g.k(n.navigationEndpoint,g.nK).browseId&&z.push(new KkJ("openUrl",
"click",new GR1("/channel/"+g.k(n.navigationEndpoint,g.nK).browseId,"new",!0,!0)));var v=n.watermark.thumbnails[0];C={channel_name:n.channelName,end_ms:n.endTimeMs,image_height:v.height,image_type:1,image_url:v.url,image_width:v.width,is_mobile:!1,session_data:{annotation_id:m,ei:Z,feature:"iv",itct:n.trackingParams,src_vid:C},start_ms:n.startTimeMs};if(n.subscribeButton&&g.k(n.subscribeButton,g.CK)){C.channel_id=g.k(n.subscribeButton,g.CK).channelId;var X;n=g.k(n.subscribeButton,g.CK);v=Z=null;n.subscribed?
(n.subscriberCountWithUnsubscribeText&&(Z=g.$5(n.subscriberCountWithUnsubscribeText)),n.subscriberCountText&&(v=g.$5(n.subscriberCountText))):(n.subscriberCountText&&(Z=g.$5(n.subscriberCountText)),n.subscriberCountWithSubscribeText&&(v=g.$5(n.subscriberCountWithSubscribeText)));var N,T=((N=g.k((X=n.signInEndpoint)==null?void 0:X.commandMetadata,g.SC))==null?void 0:N.url)||"";X={subscribeText:g.$5(n.unsubscribedButtonText),subscribeCount:Z||"",unsubscribeText:g.$5(n.subscribedButtonText),unsubscribeCount:v||
"",enabled:n.enabled||!1,classic:!1,subscribed:n.subscribed||!1,feature:"iv",signInUrl:T};C.standalone_subscribe_button_data=X}X=new ok_(m,"branding","branding",z,C);N=h1p(this);this.player.N("web_player_overlay_positioned_layout")?(N.setAttribute("data-overlay-order","11"),this.player.gq(N,4,!0)):this.J.element.appendChild(N);X=new T_(N,iG(this),X);X.dG();g.h(X,X);this.S[m]=X}}this.jo=g.N4("ytp-cards-button",this.player.getRootNode());g.Ns(L)&&W6F(this,L)};
g.l.onVideoDataChange=function(L){var m=this.player.getVideoData();m.Qd&&Ypr(this,m.Qd,L)};
g.l.unload=function(){this.player.H0("annotations_module");for(var L=g.M(Object.keys(this.S)),m=L.next();!m.done;m=L.next())this.S[m.value].destroy();this.X=null;this.W&&(this.W.destroy(),this.W=null,UX(this.player));this.C=!1;this.K&&(this.K.abort(),this.K=null);this.wd=!1;this.S={};this.J.hide();g.S2.prototype.unload.call(this);this.G.detach();this.B&&(this.player.removeEventListener("videodatachange",this.B),this.B=null)};
g.l.cJ=function(L){L===this.player.getVideoData().videoId&&(this.loaded?xJ0(this):this.load())};
g.l.JY=function(){var L;return((L=this.W)==null?void 0:L.isAvailable())||this.wd};
g.l.Tu=function(){return!!this.W&&this.W.G};
g.l.zW=function(L,m,n){m=m===void 0?!1:m;this.JY();this.W&&(L?n?no(this.W,n,m):no(this.W,"YOUTUBE_DRAWER_AUTO_OPEN",m):Co(this.W))};
g.l.JW=function(L,m){this.player.publish(L?"cardsteasershow":"cardsteaserhide",m)};
g.l.Go=function(){this.player.D().rd.unsubscribe("vast_info_card_add",this.cJ,this);g.N8(this.player.getRootNode(),g.J3.IV_DRAWER_OPEN);for(var L=this.Je,m=g.Ya,n=0,C=L.length;n<C;n++)m.z4(L[n]);this.Je.length=0;g.S2.prototype.Go.call(this)};
g.l.createElement=function(L){L=new g.H(L);g.h(this,L);return L.element};g.Md("annotations_module",uSF);g.Md("creatorendscreen",UQl);})(_yt_player);
