(function(g){var window=this;'use strict';var EX$=function(L,m,n){g.B(function(C){L.W=g.IT(m,n);g.gp(C)})},$M=function(L){L.isActive()||L.start()},XS$=function(L,m){return m?L.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},Nxp=function(L){return g.bB(L)||L.N("web_enable_caption_language_preference_stickiness")},TxF=function(L,m){var n=new g.d3;
n.languageCode=L.languageCode;n.languageName=L.languageName;n.name=L.name;n.displayName=L.displayName;n.kind=L.kind;n.isDefault=!1;n.W=L.W;n.isTranslateable=L.isTranslateable;n.vssId=L.vssId;n.url=L.url;n.translationLanguage=m;L.xtags&&(n.xtags=L.xtags);L.captionId&&(n.captionId=L.captionId);return n},VfJ=function(L,m){var n,C,Z;
return g.B(function(z){if(z.W==1)return n=L+"|"+m,g.U(z,g.y3(),2);if(z.W!=3){C=z.J;if(!C)throw g.lU("gct");return g.U(z,g.VP(C),3)}Z=z.J;return z.return(Z.get("captions",n))})},itp=function(L,m,n){VfJ(L,m).then(function(C){C&&n(C.trackData,new g.d3(C.metadata))})},q21=function(L){if(!$n0.test(L))throw Error("'"+L+"' is not a valid hex color");
L.length==4&&(L=L.replace(aIz,"#$1$1$2$2$3$3"));L=L.toLowerCase();L=parseInt(L.slice(1),16);return[L>>16,L>>8&255,L&255]},Dnf=function(){var L=void 0;
L=L===void 0?{}:L;var m="suggest_correction"in g.sL0?g.sL0.suggest_correction:"Edit caption";m=m||"";var n={},C;for(C in L){n={dL:n.dL};n.dL=C;var Z=function(z){return function(){return String(L[z.dL])}}(n);
m=m.replace(new RegExp("\\$\\{"+n.dL+"\\}","gi"),Z);m=m.replace(new RegExp("\\$"+n.dL,"gi"),Z)}return m},Otl=function(){return g.BW("yt-player-caption-display-settings")},aV=function(){this.segments=[]},lI0=function(L,m){var n=g.Y_(L.segments,m);
n>=0||n<0&&(-n-1)%2===1||(n=-n-1,n>0&&m-L.segments[n-1]===1&&n<L.segments.length&&L.segments[n]-m===1?(g.Ml(L.segments,n),g.Ml(L.segments,n-1)):n>0&&m-L.segments[n-1]===1?L.segments[n-1]=m:n<L.segments.length&&L.segments[n]-m===1?L.segments[n]=m:(g.rH(L.segments,n,0,m),g.rH(L.segments,n+1,0,m)))},RWH=function(L,m,n,C,Z,z){g.u.call(this);
this.policy=L;this.player=m;this.wd=n;this.C=C;this.K=Z;this.X=z;this.L=new aV;this.S=-1;this.J=this.G=this.W=null;this.Je=0;this.B=new g.jW(this.V4,1E3,this);this.events=new g.tC(this);g.h(this,this.B);g.h(this,this.events);this.events.j(m,"SEEK_COMPLETE",this.UQ);this.UQ();this.V4()},wSZ=function(L){return L.W&&L.W.S?L.W.S+L.player.lj()<L.player.getCurrentTime():!1},eWr=function(L,m){if(L.policy.yb&&L.player.M8()){var n=g.az(m,L.policy,{});
n.set("pot",L.player.M8());n=n.xO()}else n=g.az(m,L.policy,{}).xO();var C={format:"RAW",withCredentials:!0};if(L.policy.rd){C.method="POST";var Z=m.L;Z&&Object.keys(Z).length>0?C.postBody=g.jE(Z,g.ua):C.postBody=(0,g.W3)([120,0])}L.K&&(C.responseType="arraybuffer");var z=++L.Je,v=(0,g.SI)();L.J=g.t2(n,C,3,100,-1,function(X){X.errorCode==="net.timeout"&&L.player.kU("capnt",{rn:z++})}).then(function(X){if(L.policy.lf&&z%100===1){var N=(0,g.SI)();
L.player.kU("caprsp",{rn:z,ms:N-v,kb:(X.xhr.responseText.length/1024).toFixed()})}a:{X=X.xhr;L.FK();if(L.G){var T=!(L.K?X.response:X.responseText)||X.status>=400;if(N=g.OHd(X)){X=g.az(L.G,L.policy,{});L.G.gP(X,N);eWr(L,L.G);break a}if(T)L.player.kU("capfail",{status:X.status});else{var V;g.v8("fcb_r",(0,g.SI)(),((V=L.player.getVideoData())==null?void 0:V.wd)||"");V=L.G.XK[0];N=V.Nb;L.C!=null&&L.S!==N&&(L.K?L.C(X.response,(V.startTime+L.player.lj())*1E3):L.C(X.responseText,(V.startTime+L.player.lj())*
1E3),L.S=N)}}L.G=null;L.J=null}}).Cv(function(X){L.G=null;
L.J=null;var N;L.player.kU("capfail",{rn:z,status:(N=X.xhr)==null?void 0:N.status})});
L.G=m;lI0(L.L,L.G.XK[0].Nb)},qS=function(L,m){g.Jb.call(this,m);
this.W=L;this.U=m;this.L=null;this.S=!1;this.logger=new g.ST("caps");this.B=g.h52(this.U,this.W)},Mfl=function(L,m){var n=[],C;
for(C in L.W.W)if(L.W.W.hasOwnProperty(C)){var Z=L.W.W[C];if(g.b$(Z,m||null)){var z=Z.info.id,v=z,X="."+z,N="",T="";if(Z=Z.info.captionTrack)z=Z.languageCode,v=Z.displayName,X=Z.vssId,N=Z.kind,T=Z.id;else{Z=z;var V=g.vkr.get(Z);V==null&&(V=gXZ[Z]||gXZ[Z.replace(/-/g,"_")],g.vkr.set(Z,V));Z=V;v=Z||v}n.push(new g.d3({id:C,languageCode:z,languageName:v,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:X,kind:N,captionId:T}))}}return n},S20=function(L,m){return m!=null&&m in L.W.W?L.W.W[m]:null},
II0=function(L,m,n){var C=[],Z;
for(Z in L.W.W)if(L.W.W.hasOwnProperty(Z)){var z=L.W.W[Z];if(g.b$(z,n||null)){var v=z.info.captionTrack;v&&v.languageCode===m&&C.push(z)}}return C.length?C[0]:null},Di=function(L,m,n,C,Z,z,v,X,N,T){var V=T.isInline()&&!0,a={};
Object.assign(a,m);Object.assign(a,L.params);Object.assign(a,n);var q={};Object.assign(q,m.wu);L.params.wu&&Object.assign(q,L.params.wu);Object.assign(q,n.wu);V&&(a.windowOpacity=.6,q.backgroundOpacity=0);a.wu=q;var D=a.M1===1,O=[{Z:"span",T:"captions-text",Y:{style:"word-wrap: normal; display: block;"}}],e,I,t;(X=X.qb("caption_edit_on_hover")&&((e=T.getVideoData().getPlayerResponse())==null?void 0:(I=e.captions)==null?void 0:(t=I.playerCaptionsTracklistRenderer)==null?void 0:t.openTranscriptCommand))&&
O.unshift({Z:"button",T:"caption-edit",Y:{tabindex:"0","aria-label":Dnf()},V:[{Z:"svg",Y:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},V:[{Z:"path",Y:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.H.call(this,{Z:"div",T:"caption-window",Y:{id:"caption-window-"+L.id,dir:D?"rtl":"ltr",tabindex:"0",lang:a.lang},V:O});var b=
this;this.S=[];this.KI=!1;this.J=L;this.rd=this.SD=null;this.zX=z;this.J8=v;this.B=null;this.maxWidth=z*.96;this.maxHeight=v*.96;this.W=a;this.jk=n;this.Je=m;this.L=this.nI("captions-text");this.cD=this.L.style.getPropertyValue("box-decoration-break")!==""||this.L.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.Hv=JLr(C,Z,z,v);this.o4=N;X&&(this.K=this.nI("caption-edit"),this.j(this.K,"click",function(){b.o4()}));
this.type=0;this.YU=this.Hv*AL1(q);this.wx=V;L=new g.h8(this.element,!0);g.h(this,L);L.subscribe("dragstart",this.Rk,this);L.subscribe("dragmove",this.n3,this);L.subscribe("dragend",this.L3,this);this.fI=this.pI=this.WD=this.CI=0;L="";this.W.windowOpacity&&(L=q21(this.W.windowColor),L="rgba("+L[0]+","+L[1]+","+L[2]+","+this.W.windowOpacity+")");m={"background-color":L,display:this.W.isVisible===!1?"none":"","text-align":btD[this.W.textAlign]};this.cD&&(m["border-radius"]=L?this.YU/8+"px":"");(this.G=
this.J.params.M1===2||this.J.params.M1===3)&&tfl(this,this.element);g.GB(this.element,m);if(V){var P;(P=this.element.parentElement)==null||P.style.setProperty("--caption-window-color",L)}switch(this.W.OV){case 0:case 1:case 2:g.Ei(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Ei(this.element,"ytp-caption-window-bottom")}},tfl=function(L,m){var n="vertical-rl";
L.W.LP===1&&(n="vertical-lr");g.q8&&(n=n==="vertical-lr"?"tb-lr":"tb-rl");g.GB(m,"-o-writing-mode",n);g.GB(m,"-webkit-writing-mode",n);g.GB(m,"writing-mode",n);g.GB(m,"text-orientation","upright");g.Ei(m,"ytp-vertical-caption");L.J.params.M1===3&&(g.GB(m,"text-orientation",""),g.GB(m,"transform","rotate(180deg)"))},AL1=function(L){var m=1+.25*(L.fontSizeIncrement||0);
if(L.offset===0||L.offset===2)m*=.8;return m},fIF=function(L,m){var n={},C=m.background?m.background:L.W.wu.background;
if(m.backgroundOpacity!=null||m.background){var Z=m.backgroundOpacity!=null?m.backgroundOpacity:L.W.wu.backgroundOpacity;C=q21(C);n.background="rgba("+C[0]+","+C[1]+","+C[2]+","+Z+")";L.cD&&(n["box-decoration-break"]="clone",n["border-radius"]=L.YU/8+"px")}if(m.fontSizeIncrement!=null||m.offset!=null)n["font-size"]=L.Hv*AL1(m)+"px";C=1;Z=m.color||L.W.wu.color;if(m.color||m.textOpacity!=null)Z=q21(Z),C=m.textOpacity==null?L.W.wu.textOpacity:m.textOpacity,Z="rgba("+Z[0]+","+Z[1]+","+Z[2]+","+C+")",
n.color=Z,n.fill=Z;var z=m.charEdgeStyle;z===0&&(z=void 0);if(z){Z="rgba(34, 34, 34, "+C+")";var v="rgba(204, 204, 204, "+C+")";m.Rf&&(v=Z=m.Rf);var X=L.Hv/16/2,N=Math.max(X,1),T=Math.max(2*X,1),V=Math.max(3*X,1),a=Math.max(5*X,1);C=[];switch(z){case 4:for(;V<=a;V+=X)C.push(T+"px "+T+"px "+V+"px "+Z);break;case 1:T=window.devicePixelRatio>=2?.5:1;for(z=N;z<=V;z+=T)C.push(z+"px "+z+"px "+Z);break;case 2:C.push(N+"px "+N+"px "+v);C.push("-"+N+"px -"+N+"px "+Z);break;case 3:for(V=0;V<5;V++)C.push("0 0 "+
T+"px "+Z)}n["text-shadow"]=C.join(", ")}Z="";switch(m.fontFamily){case 1:Z='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:Z='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:Z='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:Z='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:Z='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:Z=g.W4()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:Z='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}Z&&(n["font-family"]=Z);Z=m.offset;Z==null&&(Z=L.W.wu.offset);switch(Z){case 0:n["vertical-align"]="sub";break;case 2:n["vertical-align"]="super"}m.fontFamily===7&&(n["font-variant"]="small-caps");m.bold&&(n["font-weight"]="bold");m.italic&&(n["font-style"]="italic");m.underline&&(n["text-decoration"]=
"underline");m.jx&&(n.visibility="hidden");m.w7===1&&L.G&&(n["text-combine-upright"]="all",n["text-orientation"]="mixed",Z=g.BM||g.DQ,L.J.params.M1===3?n.transform=Z?"rotate(90deg)":"rotate(180deg)":Z&&(n.transform="rotate(-90deg)"));if(m.textEmphasis===1||m.textEmphasis===2||m.textEmphasis===3||m.textEmphasis===4||m.textEmphasis===5)if(g.BM)n["font-weight"]="bold";else switch(n["text-emphasis-style"]="filled circle",n["text-emphasis-color"]="currentcolor",n["webkit-text-emphasis"]="filled circle",
m.textEmphasis){case 4:case 3:n["text-emphasis-position"]="under left";n["webkit-text-emphasis-position"]="under left";break;case 5:case 2:n["text-emphasis-position"]="over right",n["webkit-text-emphasis-position"]="over right"}return n},Oa=function(L){L=L.split("px");
return L.length>0?(L=Number(L[0]))?L:0:0},Un$=function(L){L.B=g.q4("SPAN");
g.GB(L.B,{display:"block"});g.Ei(L.B,"caption-visual-line");L.L.appendChild(L.B)},BxZ=function(L,m){var n=g.q4("SPAN");
g.GB(n,{display:"inline-block","white-space":"pre-wrap"});g.GB(n,fIF(L,m));n.classList.add("ytp-caption-segment");L.B.appendChild(n);n.previousElementSibling&&(g.GB(n.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.GB(n,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return n},P0F=function(L,m,n){L.KI=L.KI||!!n;
var C={};Object.assign(C,L.W.wu);Object.assign(C,n||m.W);Object.assign(C,L.jk.wu);(n=!L.B)&&Un$(L);for(var Z=L.SD&&L.rd&&g.qe(C,L.rd)?L.SD:BxZ(L,C),z=typeof m.text==="string",v=z?m.text.split("\n"):[m.text],X=0;X<v.length;X++){var N=X>0||!m.append,T=v[X];N&&!n?(Un$(L),Z=BxZ(L,C)):N&&n&&(n=!1);T&&(Z.appendChild(z?g.Da(T):T),z||T.tagName!=="RUBY"||T.childElementCount!==4||g.BM||!g.Km(T.children[2],"text-emphasis")||(N=L.G?"padding-right":"padding-top",g.Km(T.children[2],"text-emphasis-position")&&(N=
L.G?"padding-left":"padding-bottom"),g.Vc?g.GB(Z,N,"1em"):g.GB(Z,N,"0.5em")))}L.rd=C;L.SD=Z;L.S.push(m)},JLr=function(L,m,n,C){var Z=m/360*16;
m>=L&&(L=640,C>n*1.3&&(L=480),Z=n/L*16);return Z},QCl=function(){this.G=this.time=this.mode=this.J=0;
this.L=new sC$(this);this.K=new sC$(this);this.W=[];this.clear()},Fvp=function(L,m,n){if(L===255&&m===255||!L&&!m)return{K6:L,
nw:m,result:0};L=pSD[L];m=pSD[m];if(L&128){var C;if(C=!(m&128))C=m,C=n.v0()&&n.nw===C;if(C)return{K6:L,nw:m,result:1}}else if(m&128&&1<=L&&L<=31)return{K6:L,nw:m,result:2};return{K6:L,nw:m,result:3}},hW0=function(L,m,n,C){m===255&&n===255||!m&&!n?(++L.G===45&&L.reset(),L.L.J.clear(),L.K.J.clear()):(L.G=0,uff(L.L,m,n,C))},rLr=function(L,m){L.W.sort(function(Z,z){var v=Z.time-z.time;
return v===0?Z.order-z.order:v});
for(var n=g.M(L.W),C=n.next();!C.done;C=n.next())C=C.value,L.time=C.time,C.type===0?hW0(L,C.vU,C.oa,m):C.type===1&&L.J&496&&uff(L.K,C.vU,C.oa,m);L.W.length=0},lG=function(){this.type=0},RV=function(){this.state=this.nw=this.K6=0},k1J=function(){this.timestamp=this.W=0},w4=function(L){this.K=L;
this.G=[];this.W=this.J=this.row=0;this.style=new lG;for(L=this.L=0;L<=15;L++){this.G[L]=[];for(var m=0;m<=32;m++)this.G[L][m]=new k1J}},ee=function(L,m){if(L.style.type===3){for(var n=0,C=0,Z=L.K.time+0,z="",v="",X=Z,N=1;N<=15;++N){for(var T=!1,V=C?C:1;V<=32;++V){var a=L.G[N][V];
if(a.W!==0){n===0&&(n=N,C=V);T=String.fromCharCode(a.W);var q=a.timestamp;q<Z&&(Z=q);a.timestamp=X;v&&(z+=v,v="");z+=T;T=!0}if((a.W===0||V===32)&&T){v="\n";break}else if(C&&!T)break}if(n&&!T)break}z&&m.L(n,C,Z,X,z)}else for(C=n=0,z=Z=L.K.time+0,v=1;v<=15;++v)for(X="",N=1;N<=32;++N)if(V=L.G[v][N],a=V.W,a!==0&&(n===0&&(n=v,C=N),T=String.fromCharCode(a),q=V.timestamp,q<=Z&&(Z=q),X+=T,V.reset()),N===32||a===0)X&&m.L(n,C,Z,z,X),Z=z,X="",C=n=0},dnD=function(L,m){switch(L){case 0:return HtZ[(m&127)-32];
case 1:return Y2D[m&15];case 2:return WvH[m&31];case 3:return G1D[m&31]}return 0},g4=function(L){return L.G[L.row][L.J]},MS=function(L,m,n){m>=2&&L.J>1&&(--L.J,g4(L).W=0);
var C=g4(L);C.timestamp=L.K.time+0;C.W=dnD(m,n);L.J<32&&L.J++},Kvp=function(L,m,n,C){for(var Z=0;Z<C;Z++)for(var z=0;z<=32;z++){var v=L.G[m+Z][z],X=L.G[n+Z][z];
v.W=X.W;v.timestamp=X.timestamp}},Se=function(L,m,n){for(var C=0;C<n;C++)for(var Z=0;Z<=32;Z++)L.G[m+C][Z].reset()},xnw=function(L){L.row=L.W>0?L.W:1;
L.J=1;Se(L,0,15)},yLo=function(L){this.G=L;
this.K=0;this.style=new lG;this.S=new w4(this.G);this.B=new w4(this.G);this.text=new w4(this.G);this.J=this.S;this.L=this.B;this.W=this.J},jC$=function(L,m,n){var C=L.J,Z=!1;
switch(L.style.get()){case 4:case 1:case 2:L.style.get()===4&&C.W>0||(ee(C,n),xnw(L.J),xnw(L.L),C.row=15,C.W=m,Z=!0)}L.style.set(3);L.W=C;L.W.style=L.style;L.G.mode=1<<C.L;Z?C.J=1:C.W!==m&&(C.W>m?(ee(C,n),Se(C,C.row-C.W,m)):C.row<m&&(m=C.W),C.W=m)},oX$=function(L){L.style.set(1);
L.W=L.L;L.W.W=0;L.W.style=L.style;L.G.mode=1<<L.W.L},cLl=function(L){L.style.set(4);
L.W=L.text;L.W.style=L.style;L.G.mode=1<<L.W.L},sC$=function(L){this.W=L;
this.K=0;this.G=new yLo(this.W);this.S=new yLo(this.W);this.J=new RV;this.L=this.G},uff=function(L,m,n,C){L.J.update();
m=Fvp(m,n,L.J);switch(m.result){case 0:return;case 1:case 2:return}var Z=m.K6;n=m.nw;if(32<=Z||!Z)L.W.mode&L.W.J&&(m=Z,m&128&&(m=127),n&128&&(n=127),L=L.L.W,m&96&&MS(L,0,m),n&96&&MS(L,0,n),m!==0&&n!==0&&L.style.type===3&&ee(L,C));else if(Z&16)a:if(!L.J.matches(Z,n)&&(m=L.J,m.K6=Z,m.nw=n,m.state=2,m=Z&8?L.S:L.G,L.L=m,L.W.mode=1<<(L.K<<2)+(m.K<<1)+(m.style.type===4?1:0),(L.W.mode|1<<(L.K<<2)+(m.K<<1)+(m.style.type!==4?1:0))&L.W.J))if(n&64){C=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(Z&7)<<1|n>>5&1];
L=n&16?((n&14)>>1)*4:0;n=m.W;switch(m.style.get()){case 4:C=n.row;break;case 3:if(C!==n.row){if(C<n.W&&(C=n.W,C===n.row))break;var z=1+n.row-n.W,v=1+C-n.W;Kvp(n,v,z,n.W);m=z;Z=n.W;v<z?(z=v+Z-z,z>0&&(m+=z,Z-=z)):(z=z+Z-v,z>0&&(Z-=z));Se(n,m,Z)}}n.row=C;n.J=L+1}else switch(Z&7){case 1:switch(n&112){case 32:MS(m.W,0,32);break a;case 48:n===57?(C=m.W,g4(C).W=0,C.J<32&&C.J++):MS(m.W,1,n&15)}break;case 2:n&32&&MS(m.W,2,n&31);break;case 3:n&32&&MS(m.W,3,n&31);break;case 4:case 5:if(32<=n&&n<=47)switch(n){case 32:oX$(m);
break;case 33:C=m.W;C.J>1&&(--C.J,g4(C).W=0);break;case 36:C=m.W;m=g4(C);for(L=0;L<=15;L++)for(n=0;n<=32;n++)if(C.G[L][n]===m){for(;n<=32;n++)C.G[L][n].reset();break}break;case 37:jC$(m,2,C);break;case 38:jC$(m,3,C);break;case 39:jC$(m,4,C);break;case 40:MS(m.W,0,32);break;case 41:m.style.set(2);m.W=m.J;m.W.W=0;m.W.style=m.style;m.G.mode=1<<m.W.L;break;case 42:C=m.text;C.W=15;C.style.set(4);xnw(C);cLl(m);break;case 43:cLl(m);break;case 44:L=m.J;switch(m.style.get()){case 1:case 2:case 3:ee(L,C)}Se(L,
0,15);break;case 45:b:{L=m.W;switch(m.style.get()){default:case 2:case 1:break b;case 4:if(L.row<15){++L.row;L.J=1;break b}break;case 3:}L.W<2&&(L.W=2,L.row<L.W&&(L.row=L.W));m=L.row-L.W+1;ee(L,C);Kvp(L,m,m+1,L.W-1);Se(L,L.row,1)}break;case 46:Se(m.L,0,15);break;case 47:ee(m.J,C),m.L.updateTime(m.G.time+0),C=m.L,m.L=m.J,m.J=C,oX$(m)}break;case 7:switch(n){case 33:case 34:case 35:C=m.W,(C.J+=n&3)>32&&(C.J=32)}}},LiZ=function(){},IV=function(L,m,n,C,Z,z,v){z=z===void 0?!1:z;
v=v===void 0?null:v;g.oD.call(this,L,L+m,{priority:n,namespace:"captions"});this.windowId=C;this.text=Z;this.append=z;this.W=v},nUr=function(L,m,n,C,Z,z,v){var X=z[0],N=v[X.getAttribute("p")];
if(N.aJ===1){var T=z[1],V=z[2];z=z[3];X.getAttribute("t");T.getAttribute("t");V.getAttribute("t");z.getAttribute("t");X.getAttribute("p");T.getAttribute("p");z.getAttribute("p");v=v[V.getAttribute("p")];X=mwH(X.textContent,T.textContent,V.textContent,z.textContent,v);return new IV(L,m,Z,n,X,C,N)}switch(N.aJ){case 9:case 10:N.textEmphasis=1;break;case 11:N.textEmphasis=2;break;case 12:N.textEmphasis=3;break;case 13:N.textEmphasis=4;break;case 14:N.textEmphasis=5}return new IV(L,m,Z,n,X.textContent||
"",C,N)},mwH=function(L,m,n,C,Z){var z=g.W4(),v=z?g.q4("DIV"):g.q4("RUBY"),X=g.q4("SPAN");
X.textContent=L;v.appendChild(X);L=z?g.q4("DIV"):g.q4("RP");L.textContent=m;v.appendChild(L);m=z?g.q4("DIV"):g.q4("RT");m.textContent=n;v.appendChild(m);n=Z.aJ;if(n===10||n===11||n===12||n===13||n===14)if(g.GB(m,"text-emphasis-style","filled circle"),g.GB(m,"text-emphasis-color","currentcolor"),g.GB(m,"webkit-text-emphasis","filled circle"),Z.aJ===11||Z.aJ===13)g.GB(m,"webkit-text-emphasis-position","under left"),g.GB(m,"text-emphasis-position","under left");n=!0;if(Z.aJ===4||Z.aJ===7||Z.aJ===12||
Z.aJ===14)g.GB(v,"ruby-position","over"),g.GB(v,"-webkit-ruby-position","before");else if(Z.aJ===5||Z.aJ===6||Z.aJ===11||Z.aJ===13)g.GB(v,"ruby-position","under"),g.GB(v,"-webkit-ruby-position","after"),n=!1;Z=z?g.q4("DIV"):g.q4("RP");Z.textContent=C;v.appendChild(Z);z&&(C=n,g.GB(v,{display:"inline-block",position:"relative"}),z=v.firstElementChild.nextElementSibling,g.GB(z,"display","none"),z=z.nextElementSibling,g.GB(z,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.GB(v.lastElementChild,"display","none"),C?(g.GB(v,"padding-top","0.6em"),g.GB(z,"top","0")):(g.GB(v,"padding-bottom","0.6em"),g.GB(z,"bottom","0")));return v},Jv=function(){g.u.apply(this,arguments)},Av=function(L,m,n,C,Z){g.oD.call(this,L,L+m,{priority:n,
namespace:"captions"});this.id=C;this.params=Z;this.W=[]},C5H=function(L){var m="_"+bG++;
return new Av(0,0x8000000000000,0,m,L)},tv=function(L){Jv.call(this);
this.L=L;this.pens={};this.C={};this.X={};this.K="_"+bG++;this.B={};this.J=this.W=null;this.S=!0},fo=function(L,m){L=L.getAttribute(m);
if(L!=null)return Number(L)},Ua=function(L,m){L=L.getAttribute(m);
if(L!=null)return L==="1"},Bs=function(L,m){L=fo(L,m);
return L!==void 0?L:null},sa=function(L,m){L=L.getAttribute(m);
if(L!=null)return Ps.test(L),L},ZQF=function(L,m){var n={},C=m.getAttribute("ws");
Object.assign(n,C?L.X[C]:L.L);L=Bs(m,"mh");L!=null&&(n.Zn=L);L=Bs(m,"ju");L!=null&&(n.textAlign=L);L=Bs(m,"pd");L!=null&&(n.M1=L);L=Bs(m,"sd");L!=null&&(n.LP=L);L=sa(m,"wfc");L!=null&&(n.windowColor=L);m=fo(m,"wfo");m!==void 0&&(n.windowOpacity=m/255);return n},zM_=function(L,m){var n={},C=m.getAttribute("wp");
C&&Object.assign(n,L.C[C]);L=Bs(m,"ap");L!=null&&(n.OV=L);L=fo(m,"cc");L!=null&&(n.g3=L);L=fo(m,"ah");L!=null&&(n.rP=L);L=fo(m,"rc");L!=null&&(n.Pi=L);m=fo(m,"av");m!=null&&(n.LT=m);return n},vUo=function(L,m,n,C){var Z={};
Object.assign(Z,zM_(L,m));Object.assign(Z,ZQF(L,m));C?g.qe(Z,L.L)?(C=L.K,Z=L.L):C="_"+bG++:C=m.getAttribute("id")||"_"+bG++;L=fo(m,"t")+n;m=fo(m,"d")||0x8000000000000;if(Z.M1===2||Z.M1===3)n=Z.Pi,Z.Pi=Z.g3,Z.g3=n;return new Av(L,m,0,C,Z)},Qo=function(L){Jv.call(this);
this.S=L;this.W=new Map;this.L=new Map;this.K=new Map;this.J=new Map},po=function(L){L=g.kp(Math.round(L),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-L.length)+L},EUD=function(L,m,n,C,Z){C===0&&(C=0x8000000000000);
var z={};m.wpWinPosId&&Object.assign(z,L.L.get(m.wpWinPosId));m.wsWinStyleId&&Object.assign(z,L.K.get(m.wsWinStyleId));L=m.rcRowCount;L!==void 0&&(z.Pi=L);m=m.ccColCount;m!==void 0&&(z.g3=m);if(z.M1===2||z.M1===3)m=z.Pi,z.Pi=z.g3,z.g3=m;return new Av(n,C,0,Z,z)},F5=function(L,m,n){g.Jb.call(this,L);
this.videoData=m;this.audioTrack=n;this.K=m.QM},uG=function(L,m,n,C,Z,z,v,X,N,T){Di.call(this,L,m,n,C,Z,z,v,X,N,T);
this.type=1},hv=function(L,m,n){this.trackData=L;
this.S=n;this.version=this.K=this.G=this.byteOffset=0;this.J=[];this.W=new DataView(this.trackData)},r4=function(L){var m=L.byteOffset;
L.byteOffset+=1;return L.W.getUint8(m)},kM=function(L){var m=L.byteOffset;
L.byteOffset+=4;return L.W.getUint32(m)},Hs=function(L,m){Jv.call(this);
this.J=L;this.L=m;this.track=this.L.languageName==="CC3"?4:0;this.W=new QCl;this.W.J=1<<this.track},N6r=function(L){if(typeof L==="string")return!1;
L=new hv(L,8,0);return XfD(L)},XfD=function(L){if(!(L.byteOffset<L.W.byteLength)||kM(L)!==1380139777)return!1;
L.version=r4(L);if(L.version>1)return!1;r4(L);r4(L);r4(L);return!0},YM=function(L,m,n,C,Z,z,v,X,N,T){Di.call(this,L,m,n,C,Z,z,v,X,N,T);
var V=this;this.type=2;this.LI=[];this.wd=this.X=this.Qd=0;this.aj=NaN;this.bj=0;this.hQ=null;this.Lu=new g.jW(this.g0,433,this);this.K&&(T.createClientVe(this.K,this,167342),this.j(this.K,"click",function(){T.logClick(V.K)}),L=new g.h8(this.element,!0),g.h(this,L),L.subscribe("hoverstart",function(){T.logVisibility(V.K,!0)},this));
g.Ei(this.element,"ytp-caption-window-rollup");g.h(this,this.Lu);g.GB(this.element,"overflow","hidden")},T6o=function(L,m){if(!m)return"";
L.G&&L.J.params.LP!==1&&(m*=-1);return"translate"+(L.G?"X":"Y")+"("+m+"px)"},V4l=function(L){L.LI=Array.from(L.element.getElementsByClassName("caption-visual-line"));
for(var m=L.J.params.Pi,n=0,C=0,Z=L.LI.length-1;n<m&&Z>-1;){var z=L.LI[Z];C+=L.G?z.offsetWidth:z.offsetHeight;n++;Z--}L.X=C;m=Math;n=m.max;isNaN(L.aj)&&((C=L.W.g3)?(Z=g.q4("SPAN"),g.IL(Z,"\u2013".repeat(C)),g.GB(Z,fIF(L,L.W.wu)),L.L.appendChild(Z),L.aj=Z.offsetWidth,L.L.removeChild(Z)):L.aj=0);C=L.L;L.wd=n.call(m,L.aj,L.bj,(L.G?C.offsetHeight:C.offsetWidth)+1)},iQ_=function(L,m){V4l(L);
var n=L.LI.reduce(function(z,v){return(L.G?v.offsetWidth:v.offsetHeight)+z},0);
n=L.X-n;if(n!==L.Qd){var C=n>0&&L.Qd===0,Z=n<L.Qd;m||isNaN(n)||C||!Z||(g.Ei(L.element,"ytp-rollup-mode"),L.j(L.element,"transitionend",L.g0));g.GB(L.L,"transform",T6o(L,n));L.Qd=n}V4l(L)},$ww=function(L,m,n,C){var Z=this;
this.U=L;this.G=m;this.logger=n;this.QH=C;this.GX=[];this.T6=[];this.W=null;this.Xe={gbD:function(){return Z.W},
Yd:function(){return Z.GX}};
L=g.Ee(this.U.D().experiments,"html5_override_micro_discontinuities_threshold_ms");this.J=L>0?L:10},qwF=function(L,m){L.W=function(n,C){if(n.info.L){var Z=n;
if(L.T6.length>0){for(Z=L.T6.shift();L.T6.length>0;)Z=g.bo(Z,L.T6.shift());Z=g.bo(Z,n)}if(Z){n=Z;try{var z=g.ta(n)*1E3}catch(T){z=n.info.startTime*1E3}try{var v=g.XLZ(n)*1E3}catch(T){v=n.info.duration*1E3}if(z<0||v<0)z<0&&(z=n.info.startTime*1E3),v<0&&(v=n.info.duration*1E3);n.info.startTime=z/1E3;n.info.K=z/1E3;n.info.duration=v/1E3;n.info.C=v/1E3;z=L.RH(Z);v=z.Nb;z={formatId:z.formatId,startTimeMs:z.startTimeMs,durationMs:z.durationMs,O5:v,JP:v};v=app(L.GX,z.startTimeMs);var X=(n=v>=0?L.GX[v]:null)?
n.startTimeMs+n.durationMs:0,N=z.startTimeMs+z.durationMs;!n||z.startTimeMs-X>L.J?L.GX.splice(v+1,0,z):(n.durationMs=Math.max(X,N)-n.startTimeMs,n.JP=Math.max(n.JP,z.JP));C(L.GX);z=g.Aa(Z);C=L.G;z=z.buffer.slice(z.byteOffset,z.byteLength+z.byteOffset);Z=Z.info.K;C.S?C.L==null?g.Iz(C.logger,350058965,"Null loaded track meta data at captions data received"):m.lD(z,C.L,Z*1E3):g.Iz(C.logger,350058965,"Null Representation at captions data received")}else g.Iz(L.logger,350058965,"Empty slice")}else L.T6.push(n)};
L.U.addEventListener("sabrCaptionsDataLoaded",L.W)},app=function(L,m){L=g.Y_(L,{startTimeMs:m},function(n,C){return n.startTimeMs-C.startTimeMs});
return L>=0?L:-L-2},Ws=function(L,m){g.Jb.call(this,m);
this.W=L;this.U=m;this.logger=new g.ST("caps");this.L=this.S=null;this.B=new $ww(this.U,this,this.logger,this.W.QH)},DwZ=function(L,m){var n=[],C;
for(C in L.W.W)if(L.W.W.hasOwnProperty(C)){var Z=L.W.W[C];if(g.b$(Z,m||null)){var z=Z.info.id,v=z,X="."+z,N="",T="";if(Z=Z.info.captionTrack)z=Z.languageCode,v=Z.displayName,X=Z.vssId,N=Z.kind,T=Z.id;n.push(new g.d3({id:C,languageCode:z,languageName:v,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:X,kind:N,captionId:T}))}}return n},OQ1=function(L,m,n){var C=[],Z;
for(Z in L.W.W)if(L.W.W.hasOwnProperty(Z)){var z=L.W.W[Z];if(g.b$(z,n||null)){var v=z.info.captionTrack;v&&v.languageCode===m&&C.push(z)}}return C.length?C[0]:null},lp_=function(L,m){if(!g.E3J(L)||L.W!=null&&g.h52(m,L.W)&&L.W.W.rawcc!=null)return!1;
m=!!L.W&&L.W.isManifestless&&Object.values(L.W.W).some(function(n){return g.b$(n,"386")});
L=!!L.W&&!L.W.isManifestless&&g.euP(L.W);return m||L},RM0=function(){Jv.call(this)},eMH=function(L){var m=wf_.length;
if(L.byteLength<m)return!1;L=new Uint8Array(L,0,m);for(var n=0;n<m;n++)if(wf_[n]!==L[n])return!1;return!0},gUH=function(L,m,n,C,Z,z,v,X,N){switch(v.tagName){case "b":X.bold=!0;
break;case "i":X.italic=!0;break;case "u":X.underline=!0}for(var T=0;T<v.childNodes.length;T++){var V=v.childNodes[T];if(V.nodeType===3)V=new IV(m,n,C,Z.id,V.nodeValue,z||T>0,g.$T(X)?void 0:X),N.push(V),Z.W.push(V);else{var a={};Object.assign(a,X);gUH(L,m,n,C,Z,!0,V,a,N)}}},M4D=function(L){var m=L.split(":");
L=0;m=g.M(m);for(var n=m.next();!n.done;n=m.next())L=L*60+Number(n.value);return L*1E3},Sw$=function(L,m,n,C){C=Object.assign({Zn:0},C);
return new Av(L,m,n,"_"+bG++,C)},G_=function(L,m){g.u.call(this);
this.U=L;this.yd=m;this.W=null;this.J=this.U.Qb();this.logger=new g.ST("caps")},Jrr=function(L,m,n){if(typeof m==="string"||N6r(m))return[{trackData:m,
Ly:n}];if(typeof m==="string"&&m.substring(0,6)==="WEBVTT"||typeof m!=="string"&&eMH(m))return[{trackData:m,Ly:n}];var C=new DataView(m);if(C.byteLength<=8||C.getUint32(4)!==1718909296)return[];var Z=g.Tl_(C);if(L.J&&Z){var z=g.nIx(Z),v=g.Cax(Z);Z=Z.lT;z&&Z&&L.J.Us(Z,z,v)}L=g.Jl(C,1835295092);if(!L||!L.length||!L[0].size)return[];z=[];for(v=0;v<L.length;v++)Z=L[v],Z=new Uint8Array(m,Z.dataOffset,Z.size-(Z.dataOffset-Z.offset)),Z=g.ls(Z),z.push({trackData:Z,Ly:n+v*1E3});Ip1(C,z,n);return z=z.filter(function(X){return!!X.trackData})},
Ip1=function(L,m,n){var C=g.OH(L,0,1836476516),Z=9E4;
C&&(Z=g.l6(C)||9E4);C=0;for(var z=g.Jl(L,1836019558),v=0;v<z.length;v++){var X=z[v];v<m.length&&(X=g.OH(L,X.dataOffset,1953653094))&&(X=g.OH(L,X.dataOffset,1952867444))&&(X=g.Sk(X)/Z*1E3,v===0&&(C=X),m[v].Ly=X-C+n||n*v*1E3)}},Ar0=function(L,m,n){L.W||(L.W=new RM0);
L=L.W.G(m,n);Math.random()<.01&&g.U$(Error("Deprecated subtitles format in web player: WebVTT"));return L},bQl=function(L){var m={};
if(L=g.yd(L))m.lang=L,g.V8D.test(L)&&(m.M1=1);return m},Uw0=function(L){g.S2.call(this,L);
var m=this;this.U=L;this.SD=[];this.LI={};this.YU={};this.C=!1;this.L="NONE";this.W=this.X=this.wd=this.Hv=this.CI=null;this.Lu={TM:function(){m.TM()},
lD:function(z,v,X,N){m.lD(z,v,X,N)}};
this.J=null;this.yd=this.U.D();this.videoData=this.U.getVideoData();this.WD=this.U.u1();this.G={wu:{}};this.S={wu:{}};g.Ms(this.videoData)?this.L="OFFLINE":lp_(this.videoData,this.U)?this.L="SABR_LIVE":g.r0P(this.videoData,this.U)?this.L="LIVE":this.videoData.captionTracks.length?this.L="INNERTUBE":this.videoData.hw&&(this.L="TTS");this.pI=this.yd.controlsType==="3";this.fI=new G_(this.U,this.yd);this.KI=new g.tC(this);this.B=new g.H({Z:"div",T:"ytp-caption-window-container",Y:{id:"ytp-caption-window-container"}});
this.Je={top:0,right:0,bottom:0,left:0,width:1,height:1};var n=null,C=g.FX("yt-html5-player-modules::subtitlesModuleData");C&&(n=new g.bz(C));this.storage=n;var Z;this.wx=!((Z=L.pY())==null||!Z.bf());this.K=t4f(this);this.aj=!this.K&&this.pI&&this.wx&&(this.L==="LIVE"||this.L==="SABR_LIVE");g.h(this,this.fI);this.K?this.Qd=this.rd=null:(this.rd=new g.yv(this.EB,void 0,this),g.h(this,this.rd),this.Qd=new g.jW(this.XzK,2E3,this),g.h(this,this.Qd));g.h(this,this.KI);g.Zq(this.player,this.B.element,4);
g.h(this,this.B);this.K||this.KI.j(L,"resize",this.mL);(this.bj=g.iB(this.yd)&&!g.OG()&&!this.U.isFullscreen()&&!this.K&&!this.aj)&&this.KI.j(L,"resize",this.Wm3);this.KI.j(L,"onPlaybackAudioChange",this.ZuI);this.KI.j(L,g.La("captions"),function(z){m.onCueRangeEnter(z)});
this.KI.j(L,g.mM("captions"),function(z){m.onCueRangeExit(z)});
fpJ(this,Otl()||{});this.player.kO("onCaptionsModuleAvailable")},sjD=function(L){if(L.yd.Cf===1||L.videoData.wK===1||g.LK(L.videoData,"yt:cc")==="alwayson")return!0;
if(L.videoData.captionTracks.length)var m=L.getAudioTrack().J;if(L.yd.Cf===2){if(g.bB(L.yd))var n=B6$(L);else if(L.storage)try{n=L.storage.get("module-enabled")}catch(Z){L.storage.remove("module-enabled")}else n=null;if(n!=null)return!!n}n=XS$(L.player.getAudioTrack(),g.bB(L.yd));var C=g.LK(L.videoData,"yt:cc");if(P5p(L)===void 0){if(n==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return C?C==="on":!0;if(n==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return C==="on"}else return C==="on";return m==="ON"||
g.LK(L.videoData,"yt:cc")==="on"},d4=function(L,m){if(L.J&&(m===void 0||!m)||!L.videoData.captionTracks.length)return!1;
L=L.getAudioTrack();return!!L.W||L.J==="FORCED_ON"},P5p=function(L){var m=void 0,n=g.u3().Tm(65);
if(g.bB(L.yd)&&n!=null){if(B6$(L)!=null)return!1;m=!n}return m},xM=function(L,m){if(!L.W)return null;
if(L.X&&L.X.L)return L.X.L;m=Qjz(L,m);m=g.Cy(L.W.J,m);var n=null;if(Nxp(L.yd)){var C=L.U.isInline()?void 0:g.BW("yt-player-caption-sticky-language");for(var Z=[C,L.videoData.captionsLanguagePreference,L.yd.captionsLanguagePreference,g.LK(L.videoData,"yt:cc_default_lang")],z=!1,v=0;v<Z.length;v++){var X=Z[v];if(X){z=!0;for(var N=0;N<m.length;N++)if(g.yd(m[N])===X)return m[N];for(N=0;N<m.length;N++)if(g.yd(m[N]).split("-")[0]===X.split("-")[0])return m[N]}}if(z&&L.W&&(Z=L.W.K,Z.length))for(Z=g.M(Z),
z=Z.next();!z.done;z=Z.next())if(z=z.value,z.languageCode===C){n=z;break}}else for(C=[L.videoData.captionsLanguagePreference,L.yd.captionsLanguagePreference,g.LK(L.videoData,"yt:cc_default_lang")],Z=0;Z<C.length;Z++)for(z=0;z<m.length;z++)if(g.yd(m[z])===C[Z])return m[z];C=null;L.X&&L.X.G&&(C=L.X.G);C||(C=m.find(function(T){return T.isDefault})||null);
C||(C=m[0]||Ko(L));C&&n&&g.yd(C).split("-")[0]!==n.languageCode.split("-")[0]&&(C=TxF(C,n));return C},Ko=function(L){return L.X&&L.X.W},yo=function(L){var m=Ko(L);
return!!m&&L.J===m},pf1=function(L,m){var n=L.U.pY().Z0().textTracks;
L=L.J.toString();for(var C=0;C<n.length;C++){var Z=n[C];Z.id===L&&(m?Z.mode!=="showing"&&(Z.mode="showing"):Z.mode==="showing"&&(Z.mode="disabled"))}},cs=function(L,m,n){L.loaded&&L.unload();
n!=null&&(L.C=n,L.C&&(g.bB(L.yd)?je(L,!!m):oV(L,!!m)));m!==null||d4(L,!0)||L.l6(m,!!m,L.C?"m":"s");L.J=m;d4(L)&&(L.J=Ko(L));var C;Fiw(L,(C=L.J)!=null?C:void 0);L.load()},hMl=function(L,m){if(m instanceof Av){var n=L.LI[m.id];
n&&n.J!==m&&(n.dispose(),delete L.LI[m.id],n=null);n||(n=uQ$(L,m))&&(L.LI[m.id]=n)}else n=m.windowId,L.YU[n]||(L.YU[n]=[]),L.YU[n].push(m)},uQ$=function(L,m){var n=rrz(L);
if(!n)return null;var C=L.J?g.yd(L.J):null;C&&g.V8D.test(C)&&(m.params.M1=1);var Z=L.WD.getPlayerSize();C=Z.height*L.Je.height;Z=Z.width*L.Je.width;L.yd.playerStyle!=="google-live"||L.G.isDefault||Object.assign(m.params,L.G);switch(m.params.Zn!=null?m.params.Zn:m.W.length>1?1:0){case 1:return new uG(m,L.G,L.S,n.width,n.height,Z,C,L.yd.experiments,L.Ib.bind(L),L.U);case 2:return new YM(m,L.G,L.S,n.width,n.height,Z,C,L.yd.experiments,L.Ib.bind(L),L.U);default:return new Di(m,L.G,L.S,n.width,n.height,
Z,C,L.yd.experiments,L.Ib.bind(L),L.U)}},fpJ=function(L,m,n){n=n===void 0?!1:n;
var C=LE.wu;L.G={};Object.assign(L.G,LE);L.G.wu={};Object.assign(L.G.wu,C);L.S={wu:{}};var Z=m.backgroundOverride?L.S:L.G,z=m.background||C.background;Ps.test(z);Z.wu.background=z;Z=m.colorOverride?L.S:L.G;z=m.color||C.color;Ps.test(z);Z.wu.color=z;Z=m.windowColorOverride?L.S:L.G;z=m.windowColor||LE.windowColor;Ps.test(z);Z.windowColor=z;Z=m.backgroundOpacityOverride?L.S:L.G;z=m.backgroundOpacity;z==null&&(z=C.backgroundOpacity);Z.wu.backgroundOpacity=z;Z=m.fontSizeIncrementOverride?L.S:L.G;z=m.fontSizeIncrement;
z==null&&(z=C.fontSizeIncrement);Z.wu.fontSizeIncrement=z;z=m.fontStyleOverride?L.S:L.G;Z=m.fontStyle;Z==null&&(Z=C.bold&&C.italic?3:C.bold?1:C.italic?2:0);z=z.wu;switch(Z){case 1:z.bold=!0;delete z.italic;break;case 2:delete z.bold;z.italic=!0;break;case 3:z.bold=!0;z.italic=!0;break;default:delete z.bold,delete z.italic}Z=m.textOpacityOverride?L.S:L.G;z=m.textOpacity;z==null&&(z=C.textOpacity);Z.wu.textOpacity=z;Z=m.windowOpacityOverride?L.S:L.G;z=m.windowOpacity;z==null&&(z=LE.windowOpacity);Z.windowOpacity=
z;Z=m.charEdgeStyleOverride?L.S:L.G;z=m.charEdgeStyle;z==null&&(z=C.charEdgeStyle);Z.wu.charEdgeStyle=z;Z=m.fontFamilyOverride?L.S:L.G;z=m.fontFamily;z==null&&(z=C.fontFamily);Z.wu.fontFamily=z;L.loaded&&L.mL();n&&g.UG("yt-player-caption-display-settings",m,2592E3)},kir=function(L,m){if(!L.W)return{};
if(m){g.$T(m)||L.fh(m.vss_id,"m");if(L.K||!g.z0(m))return;if(g.$T(m)){cs(L,null,!0);return}for(var n,C=g.Cy(L.W.J,!0),Z=0;Z<C.length;Z++){var z=C[Z];z.languageCode!==m.languageCode||n&&(z.languageName!==m.languageName||(z.captionId||"")!==(m.captionId||"")||g.K4(z)!==m.displayName)||(n=m.translationLanguage?TxF(z,m.translationLanguage):z)}L.QQ(m.position);!n||n===L.J&&L.loaded||(m=g.SD(),C=g.yd(n),m.length&&C===m[m.length-1]||(m.push(C),g.UG("yt-player-caption-language-preferences",m)),Nxp(L.yd)&&
!L.U.isInline()&&g.UG("yt-player-caption-sticky-language",C,2592E3),cs(L,n,!0))}else return L.loaded&&L.J&&!yo(L)?g.xw(L.J):{};return""},Ywl=function(L,m,n){m&&!L.wd?(m=C5H({M1:0,
lang:"en-GB"}),L.wd=[m,new IV(m.start,m.end-m.start,0,m.id,n!=null?n:"Captions look like this")],L.player.Aw(L.wd)):!m&&L.wd&&(HQr(L,L.wd),L.wd=null)},HQr=function(L,m){L.player.vS(m);
m=g.M(m);for(var n=m.next();!n.done;n=m.next())g.SZ(L.SD,n.value);$M(L.rd)},Fiw=function(L,m){L.yd.N("html5_modify_caption_vss_logging")&&(L.videoData.HL=m)},rrz=function(L){var m=L.WD.getVideoContentRect(!0).height,n=L.WD.getVideoContentRect(!0).width;
if(!m||!n)return null;m*=L.Je.height;n*=L.Je.width;return{width:n,height:m}},oV=function(L,m){if(L.storage)try{L.storage.set("module-enabled",m)}catch(n){}},je=function(L,m){L.U.isInline()||g.UG("yt-player-sticky-caption",m,2592E3)},B6$=function(L){if(!L.U.isInline())return g.BW("yt-player-sticky-caption")},t4f=function(L){var m,n=!((m=L.U.pY())==null||!m.GB());
return L.pI&&n&&L.L!=="LIVE"&&L.L!=="SABR_LIVE"},Qjz=function(L,m){g.$B(L.videoData)&&(m=!0);
m||(m=L.L==="TTS"?!1:L.L==="INNERTUBE"?!1:!0);return m||L.yd.N("web_deprecate_always_includes_asr_setting")&&g.bB(L.yd)?!0:!!g.u3().Tm(66)};
g.Jb.prototype.DW=g.za(71,function(){return!1});
g.Jb.prototype.yB=g.za(70,function(){});
g.Ab.prototype.yB=g.za(69,function(L,m,n){var C=this;this.FK();m=this.pw(L,m);var Z=this.Pv.D().N("html5_report_captions_ctmp_qoe"),z=(0,g.SI)();this.nT();EX$(this,m,{format:"RAW",onSuccess:function(v){C.W=null;if(Z){var X=(v.responseText.length/1024).toFixed(),N=(0,g.SI)();C.videoData.kU("capresp",{ms:N-z,kb:X})}n.lD(v.responseText,L)},
onError:Z?function(v){var X;v=(X=v==null?void 0:v.status)!=null?X:0;C.videoData.kU("capfail",{status:v})}:void 0,
withCredentials:!0})});
g.tb.prototype.yB=g.za(68,function(L,m,n){var C=this;this.FK();m=this.pw(L,m);this.nT();this.W=g.IT(m,{format:"RAW",onSuccess:function(Z){C.W=null;n.lD(Z.responseText,L)},
withCredentials:!0})});
g.K$.prototype.Bs=g.za(67,function(){for(var L=g.XE(document,"track",void 0,this.W),m=0;m<L.length;m++)g.wr(L[m])});
g.Hp.prototype.Bs=g.za(66,function(){this.mediaElement.Bs()});
g.K$.prototype.bf=g.za(65,function(){return!(!this.W.textTracks||!this.W.textTracks.addEventListener)});
g.Hp.prototype.bf=g.za(64,function(){return this.mediaElement.bf()});
g.K$.prototype.GB=g.za(63,function(){return!!this.W.textTracks});
g.Hp.prototype.GB=g.za(62,function(){return this.mediaElement.GB()});
g.K$.prototype.kf=g.za(61,function(L){for(var m=0;m<L.length;m++)this.W.appendChild(L[m])});
g.Hp.prototype.kf=g.za(60,function(L){this.mediaElement.kf(L)});
g.Nx.prototype.Us=g.za(59,function(L,m,n){this.M6.Us(L,m,n)});
g.nv.prototype.Us=g.za(58,function(L,m,n){this.J.set(L,{f6:m,xG:n})});
g.Cv.prototype.Us=g.za(57,function(L,m,n){this.Je.Us(L,m,n)});
g.Nx.prototype.wL=g.za(56,function(L){return this.M6.wL(L)});
g.Cv.prototype.wL=g.za(55,function(L){var m=2;this.K.has(L)?m=0:g.x2d(this,L)&&(m=1);return m});
g.yE.prototype.t0=g.za(43,function(L){var m=this.app.S9({playerType:void 0});return m?m.t0(L):!1});
g.TT.prototype.t0=g.za(42,function(L){return this.Wv.kd.t0(L)});
g.so.prototype.t0=g.za(41,function(L){return this.M3().some(function(m){return m.namespace===L})});
g.Kg.prototype.t0=g.za(40,function(){return!1});
g.yE.prototype.fh=g.za(38,function(L,m){this.app.jD().fh(L,m)});
g.TT.prototype.fh=g.za(37,function(L,m){this.Wv.fh(L,m)});
g.mC.prototype.fh=g.za(36,function(L,m){L=[L,m];g.L2(this,g.C2(this.provider),"cfi",L)});
g.Be.prototype.fh=g.za(35,function(L,m){this.qoe&&this.qoe.fh(L,m)});
g.Zx.prototype.fh=g.za(34,function(L,m){this.HD.fh(L,m)});
g.Kg.prototype.fh=g.za(33,function(){});
g.yE.prototype.l6=g.za(32,function(L,m,n){this.app.jD().l6(L,m,n)});
g.TT.prototype.l6=g.za(31,function(L,m,n){this.Wv.l6(L,m,n)});
g.mC.prototype.l6=g.za(30,function(L,m,n){if(this.rd!==L||this.o4!==m)m=m==="rawcc"?"":m,n=[L,m,this.rd,n],g.L2(this,g.C2(this.provider),"cfs",n),this.rd=L,this.o4=m});
g.Be.prototype.l6=g.za(29,function(L,m,n){this.qoe&&this.qoe.l6(L,m,n)});
g.Zx.prototype.l6=g.za(28,function(L,m,n){this.HD.l6(L,m,n)});
g.Kg.prototype.l6=g.za(27,function(){});
g.Xj.prototype.N4=g.za(12,function(){return this.C});
g.RY.prototype.N4=g.za(11,function(){return this.jD().Qb()});
g.yE.prototype.Qb=g.za(10,function(){return this.app.N4()});
g.TT.prototype.Qb=g.za(9,function(){return this.Wv.Qb()});
g.Zx.prototype.Qb=g.za(8,function(){var L;return((L=this.loader)==null?void 0:L.N4())||null});
g.Kg.prototype.Qb=g.za(7,function(){return null});
g.ZS.prototype.Xs=g.za(1,function(L){return(L=this.Uw(L))?L.W:0});
g.PJ.prototype.Xs=g.za(0,function(){return 0});
var aIz=/#(.)(.)(.)/,$n0=/^#(?:[0-9a-f]{3}){1,2}$/i,gXZ={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};aV.prototype.contains=function(L){L=g.Y_(this.segments,L);return L>=0||L<0&&(-L-1)%2===1};
aV.prototype.length=function(){return this.segments.length/2};
g.R(RWH,g.u);g.l=RWH.prototype;g.l.Go=function(){g.u.prototype.Go.call(this);this.J&&this.J.cancel()};
g.l.UQ=function(){this.seekTo(this.player.getCurrentTime())};
g.l.seekTo=function(L){L-=this.player.lj();var m=this.W;this.W=g.lp(this.wd.Yu(L).XK);m!==this.W&&this.X&&this.X()};
g.l.reset=function(){this.L=new aV;this.S=-1;this.J&&(this.J.cancel(),this.J=null)};
g.l.V4=function(){this.FK();var L;if(L=this.W!=null)L=this.W,L=L.W.w3(L);if(L&&!this.J&&!(this.W&&this.W.startTime-this.player.getCurrentTime()>30)){L=this.W;L=L.W.x9(L);var m=L.XK[0],n;if((n=this.player.getVideoData())==null?0:n.enableServerStitchedDai)if(n=this.player.Qb()){var C=m.W.info.id,Z=m.Nb,z=L.XK[0].K;if(this.policy.rd){if(n=n.tq(z,Z,C,3))L.L=n}else if(C=n.J$(z,Z,C,3))if(n=n.wL(Z),n===0)C&&(L.W=new g.yB(C));else if(n===2){this.B.start();wSZ(this)&&this.seekTo(this.player.getCurrentTime());
return}}m.W.index.B_(m.Nb)?(this.L.contains(L.XK[0].Nb)||eWr(this,L),this.W=g.lp(L.XK)):wSZ(this)&&this.seekTo(this.player.getCurrentTime())}this.B.start()};
g.R(qS,g.Jb);g.l=qS.prototype;g.l.yB=function(L,m,n){var C=this;this.nT();m=S20(this,L.getId());m||(m=L.languageCode,m=this.W.isManifestless?II0(this,m,"386"):II0(this,m));if(m){var Z=(m.index.Xs(m.index.FM())-m.index.getStartTime(m.index.FM()))*1E3,z=new g.YZF(this.U.D());this.L=new RWH(z,this.U,m,function(v,X){n.lD(v,L,X,Z)},this.B||g.mN(m.info),function(){C.L&&C.L.reset();
C.S=!0})}};
g.l.DW=function(){var L=this.S;this.S=!1;return L};
g.l.ez=function(L){var m=this.U.D().N("html5_fallback_if_rawcc_missing");var n=this.W.W.rawcc!=null;if(!this.B||!n&&m)m=this.W.isManifestless?Mfl(this,"386"):Mfl(this);else{if(!n){g.Iz(this.logger,386248249,"rawcc used but unavailable");return}m=[new g.d3({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.d3({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}m=g.M(m);
for(n=m.next();!n.done;n=m.next())g.Il(this.J,n.value);L.TM()};
g.l.nT=function(){this.L&&(this.L.dispose(),this.L=null)};
g.l.pw=function(){return""};
var Ps=/^#(?:[0-9a-f]{3}){1,2}$/i;var btD=["left","right","center","justify"];g.R(Di,g.H);g.l=Di.prototype;g.l.Rk=function(L,m){this.pI=L;this.fI=m;var n=g.m5(this.element,this.element.parentElement);this.CI=L-n.x;this.WD=m-n.y};
g.l.n3=function(L,m){if(L!==this.pI||m!==this.fI){g.vu(this.element,"ytp-dragging")||g.Ei(this.element,"ytp-dragging");var n=g.C6(this.element);L=L-this.CI-.02*this.zX;var C=m-this.WD-.02*this.J8,Z=(L+n.width/2)/this.maxWidth*3;Z=Math.floor(g.kp(Z,0,2));var z=(C+n.height/2)/this.maxHeight*3;z=Math.floor(g.kp(z,0,2));m=Z+z*3;L=(L+Z/2*n.width)/this.maxWidth;L=g.kp(L,0,1)*100;n=(C+z/2*n.height)/this.maxHeight;n=g.kp(n,0,1)*100;this.J.params.OV=m;this.J.params.LT=n;this.J.params.rP=L;this.J.params.isDefault=
!1;this.W.OV=m;this.W.LT=n;this.W.rP=L;this.W.isDefault=!1;this.Je.OV=m;this.Je.LT=n;this.Je.rP=L;this.Je.isDefault=!1;this.Jp()}};
g.l.L3=function(){g.N8(this.element,"ytp-dragging")};
g.l.Jp=function(){this.Zr(this.S)};
g.l.Zr=function(L){var m=this.wx?0:Math.min(this.JZ(),this.maxWidth),n=this.Ol(),C=this.wx;if(C){var Z=getComputedStyle(this.L.parentNode);Z=Oa(Z.borderLeftWidth)+Oa(Z.borderRightWidth)+Oa(Z.paddingLeft)+Oa(Z.paddingRight)}else Z=0;var z=Z;Z="";this.J.params.M1===3&&(Z="rotate(180deg)");var v=C?"calc(96% - "+z+"px)":"96%";g.GB(this.element,{top:0,left:0,right:"",bottom:"",width:m?m+"px":"",height:n?n+"px":"","max-width":v,"max-height":v,margin:"",transform:""});this.d_(L);Z={transform:Z,top:"",left:"",
width:m?m+"px":"",height:n?n+"px":"","max-width":"","max-height":""};var X=this.W.rP*.96+2;v=this.W.OV;switch(v){case 0:case 3:case 6:(C=this.W.wu.fontSizeIncrement)&&C>0&&this.W.M1!==2&&this.W.M1!==3&&(X=Math.max(X/(1+C*2),2));Z.left=X+"%";break;case 1:case 4:case 7:Z.left=X+"%";X=this.L.offsetWidth;m||X?(m=m||X+1,Z.width=m+"px",Z["margin-left"]=C?m/-2-z/2+"px":m/-2+"px"):Z.transform+=" translateX(-50%)";break;case 2:case 5:case 8:Z.right=100-X+"%"}C=this.W.LT*.96+2;switch(v){case 0:case 1:case 2:Z.top=
C+"%";break;case 3:case 4:case 5:Z.top=C+"%";(n=n||this.element.clientHeight)?(Z.height=n+"px",Z["margin-top"]=n/-2+"px"):Z.transform+=" translateY(-50%)";break;case 6:case 7:case 8:Z.bottom=100-C+"%"}g.GB(this.element,Z);if(this.K){n=this.L.offsetHeight;C=1;for(m=0;m<L.length;m++)Z=L[m],typeof Z.text==="string"&&(C+=Z.text.split("\n").length-1,Z.append||m===0||C++);n/=C;this.K.style.height=n+"px";this.K.style.width=n+"px";this.element.style.paddingLeft=n+5+"px";this.element.style.paddingRight=n+
5+"px";L=Number(this.element.style.marginLeft.replace("px",""))-n-5;n=Number(this.element.style.marginRight.replace("px",""))-n-5;this.element.style.marginLeft=L+"px";this.element.style.marginRight=n+"px"}};
g.l.d_=function(L){var m;for(m=0;m<L.length&&L[m]===this.S[m];m++);if(this.KI||this.S.length>m)m=0,this.KI=!1,this.S=[],this.B=this.rd=this.SD=null,g.lF(this.L);for(;m<L.length;m++)P0F(this,L[m])};
g.l.JZ=function(){return 0};
g.l.Ol=function(){return 0};
g.l.toString=function(){return g.H.prototype.toString.call(this)};QCl.prototype.clear=function(){this.G=this.time=this.mode=0;this.W=[];this.reset()};
QCl.prototype.reset=function(){this.mode=0;this.L.reset(0);this.K.reset(1)};
var pSD=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];lG.prototype.set=function(L){this.type=L};
lG.prototype.get=function(){return this.type};
RV.prototype.clear=function(){this.state=0};
RV.prototype.update=function(){this.state=this.state===2?1:0};
RV.prototype.v0=function(){return this.state!==0};
RV.prototype.matches=function(L,m){return this.v0()&&L===this.K6&&m===this.nw};
k1J.prototype.reset=function(){this.timestamp=this.W=0};
w4.prototype.updateTime=function(L){for(var m=1;m<=15;++m)for(var n=1;n<=32;++n)this.G[m][n].timestamp=L};
w4.prototype.debugString=function(){for(var L="\n",m=1;m<=15;++m){for(var n=1;n<=32;++n){var C=this.G[m][n];L=C.W===0?L+"_":L+String.fromCharCode(C.W)}L+="\n"}return L};
w4.prototype.reset=function(L){for(var m=0;m<=15;m++)for(var n=0;n<=32;n++)this.G[m][n].reset();this.L=L;this.W=0;this.J=this.row=1};
var HtZ=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Y2D=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],WvH=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],G1D=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];yLo.prototype.reset=function(L,m){this.K=m;this.style.set(2);this.J=this.S;this.L=this.B;this.W=this.J;var n=(L<<2)+(m<<1);this.S.reset(n);this.B.reset(n);this.text.reset((L<<2)+(m<<1)+1)};
sC$.prototype.reset=function(L){this.K=L;this.J.clear();this.L=this.G;this.G.reset(L,0);this.S.reset(L,1)};LiZ.prototype.L=function(){};g.R(IV,g.oD);IV.prototype.toString=function(){return g.oD.prototype.toString.call(this)};g.R(Jv,g.u);Jv.prototype.reset=function(){};g.R(Av,g.oD);Av.prototype.toString=function(){return g.oD.prototype.toString.call(this)};
var bG=0;g.R(tv,Jv);tv.prototype.reset=function(){this.B={};this.J=this.W=null;this.S=!0};
tv.prototype.G=function(L,m){L=L.firstChild;L.getAttribute("format");m=m||0;Number.isFinite(m);L=Array.from(L.childNodes);L=g.M(L);for(var n=L.next();!n.done;n=L.next())if(n=n.value,n.nodeType===1)switch(n.tagName){case "head":var C=n;break;case "body":var Z=n}if(C)for(C=Array.from(C.childNodes),C=g.M(C),L=C.next();!L.done;L=C.next())if(L=L.value,L.nodeType===1)switch(L.tagName){case "pen":n=L.getAttribute("id");var z=this.pens,v={},X=L.getAttribute("p");X&&Object.assign(v,this.pens[X]);X=Ua(L,"b");
X!=null&&(v.bold=X);X=Ua(L,"i");X!=null&&(v.italic=X);X=Ua(L,"u");X!=null&&(v.underline=X);X=Bs(L,"et");X!=null&&(v.charEdgeStyle=X);X=Bs(L,"of");X!=null&&(v.offset=X);X=sa(L,"bc");X!=null&&(v.background=X);X=sa(L,"ec");X!=null&&(v.Rf=X);X=sa(L,"fc");X!=null&&(v.color=X);X=Bs(L,"fs");X!=null&&X!==0&&(v.fontFamily=X);X=fo(L,"sz");X!==void 0&&(v.fontSizeIncrement=X/100-1);X=fo(L,"bo");X!==void 0&&(v.backgroundOpacity=X/255);X=fo(L,"fo");X!==void 0&&(v.textOpacity=X/255);X=Bs(L,"rb");X!=null&&X!==10&&
X!==0&&(v.aJ=X>10?X-1:X);L=Bs(L,"hg");L!=null&&(v.w7=L);z[n]=v;break;case "ws":n=L.getAttribute("id");this.X[n]=ZQF(this,L);break;case "wp":n=L.getAttribute("id"),this.C[n]=zM_(this,L)}if(Z){C=[];Z=Array.from(Z.childNodes);Z=g.M(Z);for(L=Z.next();!L.done;L=Z.next())if(L=L.value,L.nodeType===1)switch(L.tagName){case "w":this.W=vUo(this,L,m,!1);(L=this.B[this.W.id])&&L.end>this.W.start&&(L.end=this.W.start);this.B[this.W.id]=this.W;C.push(this.W);break;case "p":var N=L;X=m;n=[];z=N.getAttribute("w")||
this.K;v=!!Ua(N,"a");X=(fo(N,"t")||0)+X;var T=fo(N,"d")||5E3;v||(!this.S&&this.J&&this.J.windowId===z&&this.J.end>X&&(this.J.end=X),this.J&&this.J.text==="\n"&&(this.J.text=""));var V=v?6:5,a=N.getAttribute("p");a=a?this.pens[a]:null;var q=Array.from(N.childNodes);q.length&&(this.S=N.getAttribute("d")!=null);for(N=0;N<q.length;N++){var D=q[N],O=void 0;N>0&&(v=!0);var e=void 0;D.nodeType===1&&(e=D);if(e&&e.tagName==="s"){if((D=(D=e.getAttribute("p"))?this.pens[D]:null)&&D.aJ&&(D.aJ===1?(D=q.slice(N,
N+4),D.length===4&&(O=nUr(X,T,z,v,V,D,this.pens),N+=3)):O=nUr(X,T,z,v,V,[e],this.pens)),!O){var I=e;O=X;e=T;D=z;var t=v,b=V,P=I.textContent?I.textContent:"",F=I.getAttribute("p");F=F?this.pens[F]:null;I=fo(I,"t")||0;O=new IV(O+I,e-I,b,D,P,t,F)}}else O=new IV(X,T,V,z,D.textContent||"",v,a);n.push(O);this.J=O}if(n.length>0)for(n[0].windowId===this.K&&(this.W=vUo(this,L,m,!0),C.push(this.W)),L=g.M(n),n=L.next();!n.done;n=L.next())n=n.value,n.windowId=this.W.id,this.W.W.push(n),C.push(n)}m=C}else m=[];
return m};var Wiz=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.R(Qo,Jv);Qo.prototype.reset=function(){this.J.clear()};
Qo.prototype.G=function(L,m){var n=JSON.parse(L);if(!n)return[];if(n.pens){L=0;for(var C=g.M(n.pens),Z=C.next();!Z.done;Z=C.next()){Z=Z.value;var z={},v=Z.pParentId;v&&Object.assign(z,this.W.get(v));Z.bAttr&&(z.bold=!0);Z.iAttr&&(z.italic=!0);Z.uAttr&&(z.underline=!0);v=Z.ofOffset;v!=null&&(z.offset=v);Z.szPenSize!==void 0&&(z.fontSizeIncrement=Z.szPenSize/100-1);v=Z.etEdgeType;v!=null&&(z.charEdgeStyle=v);Z.ecEdgeColor!==void 0&&(z.Rf=po(Z.ecEdgeColor));v=Z.fsFontStyle;v!=null&&v!==0&&(z.fontFamily=
v);Z.fcForeColor!==void 0&&(z.color=po(Z.fcForeColor));Z.foForeAlpha!==void 0&&(z.textOpacity=Z.foForeAlpha/255);Z.bcBackColor!==void 0&&(z.background=po(Z.bcBackColor));Z.boBackAlpha!==void 0&&(z.backgroundOpacity=Z.boBackAlpha/255);(v=Z.rbRuby)&&v!==10&&(z.aJ=v>10?v-1:v,z.textEmphasis=Wiz.get(z.aJ));Z.hgHorizGroup&&(z.w7=Z.hgHorizGroup);this.W.set(L++,z)}}if(n.wsWinStyles)for(L=0,C=g.M(n.wsWinStyles),Z=C.next();!Z.done;Z=C.next())Z=Z.value,z={},(v=Z.wsParentId)?Object.assign(z,this.K.get(v)):Object.assign(z,
this.S),Z.mhModeHint!==void 0&&(z.Zn=Z.mhModeHint),Z.juJustifCode!==void 0&&(z.textAlign=Z.juJustifCode),Z.pdPrintDir!==void 0&&(z.M1=Z.pdPrintDir),Z.sdScrollDir!==void 0&&(z.LP=Z.sdScrollDir),Z.wfcWinFillColor!==void 0&&(z.windowColor=po(Z.wfcWinFillColor)),Z.wfoWinFillAlpha!==void 0&&(z.windowOpacity=Z.wfoWinFillAlpha/255),this.K.set(L++,z);if(n.wpWinPositions)for(L=0,C=g.M(n.wpWinPositions),Z=C.next();!Z.done;Z=C.next())Z=Z.value,z={},(v=Z.wpParentId)&&Object.assign(z,this.L.get(v)),Z.ahHorPos!==
void 0&&(z.rP=Z.ahHorPos),Z.apPoint!==void 0&&(z.OV=Z.apPoint),Z.avVerPos!==void 0&&(z.LT=Z.avVerPos),Z.ccCols!==void 0&&(z.g3=Z.ccCols),Z.rcRows!==void 0&&(z.Pi=Z.rcRows),this.L.set(L++,z);if(n.events){L=[];n=g.M(n.events);for(C=n.next();!C.done;C=n.next()){var X=C.value;Z=(X.tStartMs||0)+m;z=X.dDurationMs||0;if(X.id)v=String(X.id),C=EUD(this,X,Z,z,v),L.push(C),this.J.set(v,C);else{X.wWinId?v=X.wWinId.toString():(v="_"+bG++,C=EUD(this,X,Z,z,v),L.push(C),this.J.set(v,C));C=L;var N=X;z===0&&(z=5E3);
X=this.J.get(v);var T=!!N.aAppend,V=T?6:5,a=N.segs,q=null;N.pPenId&&(q=this.W.get(N.pPenId));for(N=0;N<a.length;N++){var D=a[N],O=D.utf8;if(O){var e=D.tOffsetMs||0,I=null;D.pPenId&&(I=this.W.get(D.pPenId));if((X.params.Zn!=null?X.params.Zn:X.W.length>1?1:0)===2&&T&&O==="\n")continue;D=null;var t=[],b;if(b=I&&I.aJ===1){b=a;var P=N;if(P+3>=b.length||!b[P+1].pPenId||!b[P+2].pPenId||!b[P+3].pPenId)b=!1;else{var F=b[P+1].pPenId;(F=this.W.get(F))&&F.aJ&&F.aJ===2?(F=b[P+2].pPenId,F=this.W.get(F),!F||!F.aJ||
F.aJ<3?b=!1:(F=b[P+3].pPenId,b=(F=this.W.get(F))&&F.aJ&&F.aJ===2?!0:!1)):b=!1}}if(b)e=a[N+1].utf8,D=a[N+3].utf8,b=a[N+2].utf8,P=this.W.get(a[N+2].pPenId),O=mwH(O,e,b,D,P),D=new IV(Z,z,V,v,O,T,I),N+=3;else{if(O.indexOf("<")>-1){var r=void 0;t=I;b=q;P=Z;F=z;var x=e,Y=V,Ed=T,N3=[],ZF=g.cB("<html>"+O+"</html>");if(!ZF.getElementsByTagName("parsererror").length&&((r=ZF.firstChild)==null?0:r.childNodes.length))for(r=g.M(ZF.firstChild.childNodes),ZF=r.next();!ZF.done;ZF=r.next()){ZF=ZF.value;var $P=void 0,
mZ=void 0,J_=(mZ=($P=ZF.textContent)==null?void 0:$P.replace(/\n/g,""))!=null?mZ:"";if(ZF.nodeType!==3||J_&&J_.match(/^ *$/)==null){$P={};Object.assign($P,t||b);mZ=void 0;switch((mZ=ZF)==null?void 0:mZ.tagName){case "b":$P.bold=!0;break;case "i":$P.italic=!0;break;case "u":$P.underline=!0}N3.push(new IV(P+x,F-x,Y,X.id,J_,Ed,$P))}}t=N3}t.length||(t=[new IV(Z+e,z-e,V,X.id,O,T,I||q)])}if(t.length)for(T=g.M(t),I=T.next();!I.done;I=T.next())I=I.value,C.push(I),X.W.push(I);else D&&(C.push(D),X.W.push(D))}T=
!0}}}m=L}else m=[];return m};g.R(F5,g.Jb);F5.prototype.yB=function(L,m,n){itp(this.videoData.videoId,L.vssId,n.lD)};
F5.prototype.ez=function(L){if(this.audioTrack)for(var m=g.M(this.audioTrack.captionTracks),n=m.next();!n.done;n=m.next())g.Il(this.J,n.value);L.TM()};g.R(uG,Di);uG.prototype.d_=function(L){var m=this.J.W;Di.prototype.d_.call(this,L);for(L=L.length;L<m.length;L++){var n=m[L];if(z&&n.W===Z)var C=z;else{C={};Object.assign(C,n.W);Object.assign(C,Gif);var Z=n.W;var z=C}P0F(this,n,C)}};
var Gif={jx:!0};g.R(hv,LiZ);hv.prototype.L=function(L,m,n,C,Z){if(n<C){var z="_"+bG++;n=n/1E3-this.S;C=C/1E3-this.S;L=new Av(n,C-n,5,z,{textAlign:0,OV:0,rP:m*2.5,LT:L*5.33});Z=new IV(n,C-n,5,z,Z);this.J.push(L);this.J.push(Z)}};
g.R(Hs,Jv);Hs.prototype.G=function(L){L=new hv(L,L.byteLength,this.J);if(XfD(L)){for(;L.byteOffset<L.W.byteLength;)for(L.version===0?L.G=kM(L)*(1E3/45):L.version===1&&(L.G=kM(L)*4294967296+kM(L)),L.K=r4(L);L.K>0;L.K--){var m=r4(L),n=r4(L),C=r4(L);m&4&&(m&3)===this.track&&(this.track===0||this.track===1)&&(m=this.W,m.W.push({time:L.G,type:this.track,vU:n,oa:C,order:m.W.length}))}rLr(this.W,L);return L.J}return[]};
Hs.prototype.reset=function(){this.W.clear()};g.R(YM,Di);g.l=YM.prototype;g.l.Jp=function(){g.cO(this.Lu)};
g.l.g0=function(){this.element.removeEventListener("transitionend",this.g0,!1);g.N8(this.element,"ytp-rollup-mode");this.Zr(this.hQ,!0)};
g.l.Ol=function(){return this.G?this.wd:this.X};
g.l.JZ=function(){return this.G?this.X:this.wd};
g.l.Zr=function(L,m){this.hQ=L;if(this.J.params.Pi){for(var n=0,C=0;C<this.S.length&&n<L.length;C++)this.S[C]===L[n]&&n++;n>0&&n<L.length&&(L=this.S.concat(L.slice(n)));this.bj=this.wd;this.X=this.wd=0;Di.prototype.Zr.call(this,L);iQ_(this,m)}Di.prototype.Zr.call(this,L)};$ww.prototype.unload=function(){this.W!=null&&(this.U.removeEventListener("sabrCaptionsDataLoaded",this.W),this.W=null);this.GX=[];this.U.publish("sabrCaptionsBufferedRangesUpdated",this.GX)};
$ww.prototype.RH=function(L){return{formatId:g.CH(L.info.W.info,this.QH),Nb:L.info.Nb+(this.QH?0:1),startTimeMs:L.info.K*1E3,durationMs:L.info.C*1E3}};g.R(Ws,g.Jb);Ws.prototype.yB=function(L,m,n){this.nT();m=L.getId();m=m!=null&&m in this.W.W?this.W.W[m]:null;m||(m=L.languageCode,m=this.W.isManifestless?OQ1(this,m,"386"):OQ1(this,m));m&&(this.L=L,this.S=m,qwF(this.B,n),this.U.publish("sabrCaptionsTrackChanged",g.CH(m.info,this.W.QH)))};
Ws.prototype.ez=function(L){var m=this.W.isManifestless?DwZ(this,"386"):DwZ(this);m=g.M(m);for(var n=m.next();!n.done;n=m.next())g.Il(this.J,n.value);L.TM()};
Ws.prototype.nT=function(){this.L&&(this.L=this.S=null,this.B.unload(),this.U.publish("sabrCaptionsTrackChanged",null))};
Ws.prototype.pw=function(){return""};var wf_="WEBVTT".split("").map(function(L){return L.charCodeAt(0)});
g.R(RM0,Jv);
RM0.prototype.G=function(L,m){L instanceof ArrayBuffer&&(L=g.ls(new Uint8Array(L)));var n=[];L=L.split(dwF);for(var C=1;C<L.length;C++){var Z=L[C],z=m;if(Z!==""&&!Kiw.test(Z)){var v=xw_.exec(Z);if(v&&v.length>=4){var X=M4D(v[1]),N=M4D(v[2])-X;X+=z;var T=(v=v[3])?v.split(" "):[];v={};var V=null;var a="";var q=null,D="";T=g.M(T);for(var O=T.next();!O.done;O=T.next())if(O=O.value.split(":"),O.length===2){var e=O[1];switch(O[0]){case "line":O=e.split(",");O[0].endsWith("%")&&(V=O[0],v.LT=Number.parseInt(V,
10),O.length===2&&(a=O[1].trim()));break;case "position":O=e.split(",");q=O[0];v.rP=Number.parseInt(q,10);O.length===2&&(D=O[1].trim());break;case "align":switch(e){case "start":v.textAlign=0;break;case "middle":v.textAlign=2;break;case "end":v.textAlign=1}}}V||a||(a="end");if(!q)switch(v.textAlign){case 0:v.rP=0;break;case 1:v.rP=100;break;case 2:v.rP=50}if(v.textAlign!=null){V=0;switch(a){case "center":V+=3;break;case "end":V+=6;break;default:V+=0}switch(D){case "line-left":V+=0;break;case "center":V+=
1;break;case "line-right":V+=2;break;default:switch(v.textAlign){case 0:V+=0;break;case 2:V+=1;break;case 1:V+=2}}a=V<0||V>8?7:V;v.OV=a}Z=Z.substring(xw_.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");D=v;v=Z;Z={};if(v.indexOf("<")<0&&v.indexOf("&")<0)z=Sw$(X,N,5,D),N=new IV(X,N,5,z.id,v,!1,g.$T(Z)?void 0:Z),n.push(z),n.push(N),z.W.push(N);else for(a=v.split(yr$),a.length===1?(v=5,D=Sw$(X,N,v,D)):(V=v=6,D=Object.assign({g3:32},D),D=new Av(X,N,V,"_"+bG++,D)),n.push(D),V=X,q=0;q<a.length;q++)T=a[q],
q%2===0?(O=g.cB("<html>"+T+"</html>"),O.getElementsByTagName("parsererror").length?(e=O.createElement("span"),e.appendChild(O.createTextNode(T))):e=O.firstChild,gUH(this,V,N-(V-X),v,D,q>0,e,Z,n)):V=M4D(T)+z}xw_.lastIndex=0}}return n};
var Kiw=/^NOTE/,dwF=/(?:\r\n|\r|\n){2,}/,xw_=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),yr$=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.R(G_,g.u);G_.prototype.clear=function(){this.W&&this.W.dispose();this.W=null};
G_.prototype.reset=function(){this.W&&this.W.reset()};
G_.prototype.Go=function(){g.u.prototype.Go.call(this);this.clear()};var LE={windowColor:"#080808",windowOpacity:0,textAlign:2,OV:7,rP:50,LT:100,isDefault:!0,wu:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.R(Uw0,g.S2);g.l=Uw0.prototype;g.l.Go=function(){if(this.K||this.aj){var L=this.U.pY();L&&!L.FK()&&L.Bs()}else Ywl(this,!1);g.S2.prototype.Go.call(this)};
g.l.jR=function(){return this.yd.N("html5_honor_caption_availabilities_in_audio_track")&&this.L!=="LIVE"&&this.L!=="SABR_LIVE"};
g.l.fF=function(){if(this.pI)return this.K||this.aj;var L=this.getAudioTrack();if(this.jR()){if(!L.captionTracks.length)return!1;if(!this.W)return!0}L=XS$(L,g.bB(this.yd));return L==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:L==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?d4(this):P5p(this)||d4(this)?!0:sjD(this)};
g.l.load=function(){g.S2.prototype.load.call(this);this.X=this.getAudioTrack();if(this.W)this.J&&(this.fI.clear(),this.K?pf1(this,!0):this.player.getPresentingPlayerType()!==3&&this.W.yB(this.J,"json3",this.Lu),this.K||this.aj||yo(this)||this.player.kO("captionschanged",g.xw(this.J)));else{var L;this.L==="OFFLINE"?L=new F5(this.player,this.videoData,this.getAudioTrack()):this.L==="SABR_LIVE"?L=new Ws(this.videoData.W,this.player):this.L==="LIVE"?L=new qS(this.videoData.W,this.player):this.L==="INNERTUBE"?
L=new g.Ab(this.player,this.videoData,this.getAudioTrack()):L=new g.tb(this.player,this.videoData.hw,this.videoData.videoId,g.TfU(this.videoData),this.videoData.u2,this.videoData.eventId);this.W=L;g.h(this,this.W);this.W.ez(this.Lu)}};
g.l.unload=function(){this.K&&this.J?pf1(this,!1):(this.Qd&&g.LM(this.Qd),this.player.H0("captions"),this.SD=[],this.W&&this.W.nT(),this.fI.clear(),this.wd&&this.player.Aw(this.wd),this.mL());g.S2.prototype.unload.call(this);this.player.dC();this.player.kO("captionschanged",{})};
g.l.create=function(){this.fF()&&this.load();var L;a:{var m,n,C;if(this.yd.N("web_player_nitrate_promo_tooltip")&&((m=this.videoData.getPlayerResponse())==null?0:(n=m.captions)==null?0:(C=n.playerCaptionsTracklistRenderer)==null?0:C.enableTouchCaptionsNitrate)){var Z,z;if(m=(L=this.videoData.getPlayerResponse())==null?void 0:(Z=L.captions)==null?void 0:(z=Z.playerCaptionsTracklistRenderer)==null?void 0:z.captionTracks)for(L=g.M(m),Z=L.next();!Z.done;Z=L.next())if(Z=Z.value,Z.kind==="asr"&&Z.languageCode===
"en"){L=!0;break a}}L=!1}L&&this.U.publish("showpromotooltip",this.B.element)};
g.l.TM=function(){var L=XS$(this.player.getAudioTrack(),g.bB(this.yd));var m=L==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?xM(this,this.C):L==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&d4(this)?Ko(this):P5p(this)||this.C||sjD(this)?xM(this,this.C):d4(this)?Ko(this):null;if(this.K||this.aj){var n=g.Cy(this.W.J,!0);L=[];for(var C=0;C<n.length;C++){var Z=n[C],z=g.q4("TRACK");z.setAttribute("kind","subtitles");z.setAttribute("label",g.K4(Z));z.setAttribute("srclang",g.yd(Z));z.setAttribute("id",Z.toString());
this.aj||z.setAttribute("src",this.W.pw(Z,"vtt"));Z===m&&z.setAttribute("default","1");L.push(z)}m=this.U.pY();m.kf(L);L=m.Z0();this.wx&&this.KI.j(L.textTracks,"change",this.uFU)}else!this.J&&m&&cs(this,m),this.player.kO("onCaptionsTrackListChanged"),this.player.Mv("onApiChange")};
g.l.uFU=function(){for(var L=this.U.pY().Z0().textTracks,m=null,n=0;n<L.length;n++)if(L[n].mode==="showing")a:{m=g.Cy(this.W.J,!0);for(var C=0;C<m.length;C++)if(m[C].toString()===L[n].id){m=m[C];break a}m=null}(this.loaded?this.J:null)!==m&&cs(this,m,!0)};
g.l.Qgb=function(){!this.J&&this.K||this.unload()};
g.l.lD=function(L,m,n,C){if(L){var Z;Fiw(this,(Z=this.J)!=null?Z:void 0);this.W.DW()&&(this.SD=[],this.U.H0("captions"),$M(this.rd),this.fI.reset());a:{Z=this.fI;C=C||0;n=Jrr(Z,L,n||0);L=[];try{for(var z=g.M(n),v=z.next();!v.done;v=z.next()){var X=v.value,N=X.trackData,T=X.Ly,V=Z.yd.N("safari_live_drm_captions_fix");if(typeof N!=="string"){n=L;var a=n.concat;if(V&&eMH(N))var q=Ar0(Z,N,T);else{var D=Z,O=m,e=N,I=T,t=C;if(!N6r(e))throw Error("Invalid binary caption track data");D.W||(D.W=new Hs(t,O));
q=D.W.G(e,I)}var b=a.call(n,q)}else{if(N.substring(0,6)==="WEBVTT")var P=L.concat(Ar0(Z,N,T));else{n=L;var F=n.concat;b:{O=D=void 0;e=Z;I=m;if(N[0]==="{")try{e.W||(e.W=new Qo(bQl(I)));var r=O=e.W.G(N,T);break b}catch(mZ){g.fp(mZ);r=[];break b}var x=g.cB(N);if(!x||!x.firstChild){var Y=Error("Invalid caption track data");Y.params=N;throw Y;}if(x.firstChild.tagName==="timedtext"){if(Number(x.firstChild.getAttribute("format"))===3){e.W||(e.W=new tv(bQl(I),e.yd));r=D=e.W.G(x,T);break b}var Ed=Error("Unsupported subtitles format in web player (Format2)");
Ed.params=N;throw Ed;}if(x.firstChild.tagName==="transcript"){var N3=Error("Unsupported subtitles format in web player (Format1)");N3.params=N;throw N3;}var ZF=Error("Invalid caption track data");ZF.params=N;throw ZF;}P=F.call(n,r)}b=P}L=b}var $P=L;break a}catch(mZ){g.Iz(Z.logger,187101178,"Captions parsing failed: "+mZ.message+". ");Z.clear();$P=[];break a}$P=void 0}m=$P;m.length>0&&($P=this.J,this.l6($P,!!$P,yo(this)?"g":this.C?"m":"s"));this.player.Aw(m,void 0,this.L==="LIVE"||this.L==="SABR_LIVE");
!this.C||this.aj||yo(this)||g.ea(this.yd)||g.aZ(this.yd)||g.p5(this.yd)||this.yd.KI==="shortspage"||this.player.isInline()||(g.LM(this.Qd),m=C5H({OV:0,rP:5,LT:5,Pi:2,textAlign:0,M1:0,lang:"en-GB"}),this.Hv=[m],$P=["Click "," for settings"],this.CI||(z=new g.ES(g.bl()),g.h(this,z),this.CI=z.element),z=m.end-m.start,(v=g.K4(this.J))&&this.Hv.push(new IV(m.start,z,0,m.id,v)),this.Hv.push(new IV(m.start,z,0,m.id,$P[0]),new IV(m.start,z,0,m.id,this.CI,!0),new IV(m.start,z,0,m.id,$P[1],!0)),this.player.Aw(this.Hv),
g.oa(this.Qd));!this.C||this.aj||yo(this)||(g.bB(this.yd)?je(this,!0):oV(this,!0),this.X&&(this.X.L=this.J),this.player.dC());this.C=!1}};
g.l.onCueRangeEnter=function(L){this.SD.push(L);$M(this.rd)};
g.l.onCueRangeExit=function(L){g.SZ(this.SD,L);this.W instanceof qS&&this.W.B&&this.player.vS([L]);$M(this.rd)};
g.l.getCaptionWindowContainerId=function(){return this.B.element.id};
g.l.XzK=function(){HQr(this,this.Hv);this.Hv=null};
g.l.EB=function(){var L=this;if(!this.bj||!this.K){this.rd.stop();g.sUZ(this.YU);this.SD.sort(g.cZ);var m=this.SD;if(this.wd){var n=g.f7(m,function(z){return this.wd.indexOf(z)===-1},this);
n.length&&(m=n)}m=g.M(m);for(n=m.next();!n.done;n=m.next())hMl(this,n.value);m=g.M(Object.entries(this.LI));var C=m.next();for(n={};!C.done;n={h$:void 0,Mc:void 0},C=m.next()){var Z=g.M(C.value);C=Z.next().value;Z=Z.next().value;n.h$=C;n.Mc=Z;this.YU[n.h$]?(n.Mc.element.parentNode||(n.Mc instanceof YM||n.Mc instanceof uG||g.CX(this.LI,function(z){return function(v,X){X!==z.h$&&v.J.params.OV===z.Mc.J.params.OV&&v.J.params.rP===z.Mc.J.params.rP&&v.J.params.LT===z.Mc.J.params.LT&&(v.dispose(),delete L.LI[X]);
return X===z.h$}}(n),this),this.B.element.appendChild(n.Mc.element)),n.Mc.Zr(this.YU[n.h$])):(n.Mc.dispose(),delete this.LI[n.h$])}}};
g.l.OLI=function(){fpJ(this,{},!0);this.player.kO("captionssettingschanged")};
g.l.Cn=function(){var L=LE.wu;L={background:L.background,backgroundOpacity:L.backgroundOpacity,charEdgeStyle:L.charEdgeStyle,color:L.color,fontFamily:L.fontFamily,fontSizeIncrement:L.fontSizeIncrement,fontStyle:L.bold&&L.italic?3:L.bold?1:L.italic?2:0,textOpacity:L.textOpacity,windowColor:LE.windowColor,windowOpacity:LE.windowOpacity};var m=Otl()||{};m.background!=null&&(L.background=m.background);m.backgroundOverride!=null&&(L.backgroundOverride=m.backgroundOverride);m.backgroundOpacity!=null&&(L.backgroundOpacity=
m.backgroundOpacity);m.backgroundOpacityOverride!=null&&(L.backgroundOpacityOverride=m.backgroundOpacityOverride);m.charEdgeStyle!=null&&(L.charEdgeStyle=m.charEdgeStyle);m.charEdgeStyleOverride!=null&&(L.charEdgeStyleOverride=m.charEdgeStyleOverride);m.color!=null&&(L.color=m.color);m.colorOverride!=null&&(L.colorOverride=m.colorOverride);m.fontFamily!=null&&(L.fontFamily=m.fontFamily);m.fontFamilyOverride!=null&&(L.fontFamilyOverride=m.fontFamilyOverride);m.fontSizeIncrement!=null&&(L.fontSizeIncrement=
m.fontSizeIncrement);m.fontSizeIncrementOverride!=null&&(L.fontSizeIncrementOverride=m.fontSizeIncrementOverride);m.fontStyle!=null&&(L.fontStyle=m.fontStyle);m.fontStyleOverride!=null&&(L.fontStyleOverride=m.fontStyleOverride);m.textOpacity!=null&&(L.textOpacity=m.textOpacity);m.textOpacityOverride!=null&&(L.textOpacityOverride=m.textOpacityOverride);m.windowColor!=null&&(L.windowColor=m.windowColor);m.windowColorOverride!=null&&(L.windowColorOverride=m.windowColorOverride);m.windowOpacity!=null&&
(L.windowOpacity=m.windowOpacity);m.windowOpacityOverride!=null&&(L.windowOpacityOverride=m.windowOpacityOverride);return L};
g.l.Cq=function(L,m){var n={};Object.assign(n,Otl());Object.assign(n,L);fpJ(this,n,m);this.player.kO("captionssettingschanged")};
g.l.mL=function(){!this.K&&this.loaded&&(g.cz(this.LI,function(L,m){L.dispose();delete this.LI[m]},this),this.EB())};
g.l.Ch=function(L,m){switch(L){case "fontSize":if(isNaN(m))break;L=g.kp(m,-2,4);this.Cq({fontSizeIncrement:L});return L;case "reload":m&&!this.K&&cs(this,this.J,!0);break;case "stickyLoading":m!==void 0&&this.yd.C&&(g.bB(this.yd)?je(this,!!m):oV(this,!!m));break;case "track":return kir(this,m);case "tracklist":return this.W?g.lu(g.Cy(this.W.J,!(!m||!m.includeAsr)),function(n){return g.xw(n)}):[];
case "translationLanguages":return this.W?this.W.K.map(function(n){return Object.assign({},n)}):[];
case "sampleSubtitles":this.K||m===void 0||Ywl(this,!!m);break;case "sampleSubtitlesCustomized":this.K||Ywl(this,!!m,m);break;case "recommendedTranslationLanguages":return g.SD();case "defaultTranslationSourceTrackIndices":return this.W?this.W.C:[]}};
g.l.getOptions=function(){var L="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.yd.C&&L.push("stickyLoading");return L};
g.l.lw=function(){var L=this.J;if(this.U.t0("captions")){if(this.yd.N("html5_modify_caption_vss_logging")){var m;return(L=(m=this.videoData.HL)!=null?m:null)?{cc:g.UbZ(L)}:{}}if(L)return m=L.vssId,L.translationLanguage&&m&&(m="t"+m+"."+g.yd(L)),{cc:m}}return{}};
g.l.nNU=function(){this.isSubtitlesOn()?(g.bB(this.yd)?je(this,!1):oV(this,!1),Fiw(this),cs(this,null,!0)):this.Kq()};
g.l.Kq=function(){var L=yo(this)||!this.J?xM(this,!0):this.J;L&&this.fh(L.vssId,"m");this.isSubtitlesOn()||cs(this,yo(this)||!this.J?xM(this,!0):this.J,!0)};
g.l.isSubtitlesOn=function(){return!!this.loaded&&!!this.J&&!yo(this)};
g.l.ZuI=function(){var L=yo(this);d4(this,L)?cs(this,this.getAudioTrack().W,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.jR()&&(this.C=!1,this.J=null,this.W&&(this.W.dispose(),this.W=null)),this.fF()&&(L?cs(this,xM(this,!1),!1):this.load()))};
g.l.QQ=function(L){L&&(this.Je={top:L.top,right:L.right,bottom:L.bottom,left:L.left,width:1-L.left-L.right,height:1-L.top-L.bottom},this.B.element.style.top=this.Je.top*100+"%",this.B.element.style.left=this.Je.left*100+"%",this.B.element.style.width=this.Je.width*100+"%",this.B.element.style.height=this.Je.height*100+"%",this.B.element.style.position="absolute",L=rrz(this))&&(this.B.element.style.width=L.width+"px",this.B.element.style.height=L.height+"px")};
g.l.onVideoDataChange=function(L,m){L==="newdata"&&(this.videoData=m,this.loaded&&this.unload(),this.C=!1,this.J=null,this.W&&(this.W.dispose(),this.W=null,this.player.kO("captionschanged",{})),this.fF()&&this.load())};
g.l.getAudioTrack=function(){return this.player.getAudioTrack()};
g.l.Wm3=function(){var L=this.U.pY();L&&!L.FK()&&L.Bs();this.U.isFullscreen()?(this.K=this.pI=!0,this.loaded&&this.TM()):(this.pI=this.yd.controlsType==="3",this.K=t4f(this));cs(this,this.J)};
g.l.Ib=function(){var L,m,n,C=(L=this.videoData.getPlayerResponse())==null?void 0:(m=L.captions)==null?void 0:(n=m.playerCaptionsTracklistRenderer)==null?void 0:n.openTranscriptCommand;C&&this.player.Vd("innertubeCommand",C)};
g.l.l6=function(L,m,n){var C=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,Z="";L&&(Z=L.vssId,Z=Z.replace(C,""));var z="";L&&L.getId()&&(z=L.getId()||"");L&&L.getXtags()&&(L=L.getXtags(),L=L.replace(C,""),z=z.concat(";"+L));this.U.l6(m?Z:"",m?z:"",n)};
g.l.fh=function(L,m){L=(L||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");L.length>0&&this.U.fh(L,m)};g.Md("captions",Uw0);})(_yt_player);
