(function(g){var window=this;'use strict';var eNF=function(L){L.publish("autonavvisibility")},gm_=function(L,m){L.Vd("onAutonavCoundownStarted",m)},Mil=function(L){var m,n,C;
return L==null?void 0:(m=L.playerOverlays)==null?void 0:(n=m.playerOverlayRenderer)==null?void 0:(C=n.autoplay)==null?void 0:C.playerOverlayAutoplayRenderer},Xz=function(L){var m=L.D(),n=m.L;
g.H.call(this,{Z:"a",T:"ytp-autonav-suggestion-card",Y:{href:"{{url}}",target:n?m.X:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{Z:"div",xU:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],Y:{style:"{{background}}"},V:[{Z:"div",Y:{"aria-label":"{{timestamp}}"},xU:["ytp-autonav-timestamp"],zo:"{{duration}}"},{Z:"div",xU:["ytp-autonav-live-stamp"],zo:"Live"},{Z:"div",
xU:["ytp-autonav-upcoming-stamp"],zo:"Upcoming"},{Z:"div",T:"ytp-autonav-list-overlay",V:[{Z:"div",T:"ytp-autonav-mix-text",zo:"Mix"},{Z:"div",T:"ytp-autonav-mix-icon"}]}]},{Z:"div",xU:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],zo:"{{title}}"},{Z:"div",xU:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],zo:"{{author}}"},{Z:"div",xU:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],zo:"{{views_and_publish_time}}"}]});this.U=L;this.suggestion=
null;this.W=n;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},N0=function(L,m){m=m===void 0?!1:m;
g.H.call(this,{Z:"div",T:"ytp-autonav-endscreen-countdown-overlay"});var n=this;this.S=m;this.cancelCommand=this.K=void 0;this.G=0;this.container=new g.H({Z:"div",T:"ytp-autonav-endscreen-countdown-container"});g.h(this,this.container);this.container.sN(this.element);m=L.D();var C=m.L;this.U=L;this.suggestion=null;this.onVideoDataChange("newdata",this.U.getVideoData());this.j(L,"videodatachange",this.onVideoDataChange);this.W=new g.H({Z:"div",T:"ytp-autonav-endscreen-upnext-container",Y:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{Z:"div",T:"ytp-autonav-endscreen-upnext-header"},{Z:"div",T:"ytp-autonav-endscreen-upnext-alternative-header",zo:"{{autoplayAlternativeHeader}}"},{Z:"a",T:"ytp-autonav-endscreen-link-container",Y:{href:"{{url}}",target:C?m.X:""},V:[{Z:"div",T:"ytp-autonav-endscreen-upnext-thumbnail",Y:{style:"{{background}}"},V:[{Z:"div",Y:{"aria-label":"{{timestamp}}"},xU:["ytp-autonav-timestamp"],
zo:"{{duration}}"},{Z:"div",xU:["ytp-autonav-live-stamp"],zo:"Live"},{Z:"div",xU:["ytp-autonav-upcoming-stamp"],zo:"Upcoming"}]},{Z:"div",T:"ytp-autonav-endscreen-video-info",V:[{Z:"div",T:"ytp-autonav-endscreen-premium-badge"},{Z:"div",T:"ytp-autonav-endscreen-upnext-title",zo:"{{title}}"},{Z:"div",T:"ytp-autonav-endscreen-upnext-author",zo:"{{author}}"},{Z:"div",T:"ytp-autonav-view-and-date",zo:"{{views_and_publish_time}}"},{Z:"div",T:"ytp-autonav-author-and-view",zo:"{{author_and_views}}"}]}]}]});
g.h(this,this.W);this.W.sN(this.container.element);C||this.j(this.W.nI("ytp-autonav-endscreen-link-container"),"click",this.Kg);this.U.createClientVe(this.container.element,this,115127);this.U.createClientVe(this.W.nI("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.H({Z:"div",T:"ytp-autonav-overlay"});g.h(this,this.overlay);this.overlay.sN(this.container.element);this.J=new g.H({Z:"div",T:"ytp-autonav-endscreen-button-container"});g.h(this,this.J);this.J.sN(this.container.element);
this.cancelButton=new g.H({Z:"button",xU:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",m.N("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Y:{"aria-label":"Cancel auto-play"},zo:"Cancel"});g.h(this,this.cancelButton);this.cancelButton.sN(this.J.element);this.cancelButton.listen("click",this.cY,this);this.U.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.H({Z:"a",xU:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
m.N("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Y:{href:"{{url}}",role:"button","aria-label":"Play next video"},zo:"Play now"});g.h(this,this.playButton);this.playButton.sN(this.J.element);this.playButton.listen("click",this.Kg,this);this.U.createServerVe(this.playButton.element,this.playButton,!0);(m=this.U.getVideoData())&&S1f(this,m);this.L=new g.jW(function(){Ir0(n)},500);
g.h(this,this.L);this.ZY();this.j(L,"autonavvisibility",this.ZY);this.U.N("web_autonav_color_transition")&&(this.j(L,"autonavchange",this.gH),this.j(L,"onAutonavCoundownStarted",this.KY1))},TM=function(L){var m=L.U.s1(!0,L.U.isFullscreen());
g.VR(L.container.element,"ytp-autonav-endscreen-small-mode",L.d$(m));g.VR(L.container.element,"ytp-autonav-endscreen-is-premium",!!L.suggestion&&!!L.suggestion.fgv);g.VR(L.U.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!L.U.aU());g.VR(L.U.getRootNode(),"countdown-running",L.sW());g.VR(L.container.element,"ytp-player-content",L.U.aU());g.GB(L.overlay.element,{width:m.width+"px"});if(!L.sW()){L.U.aU()?Jsw(L,Math.round(AsZ(L)/1E3)):Jsw(L);m=!!L.suggestion&&!!L.suggestion.iE;var n=L.U.aU()||
!m;g.VR(L.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!n&&m);g.VR(L.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",n&&!m);L.J.fu(L.U.aU());g.VR(L.element,"ytp-enable-w2w-color-transitions",b7l(L))}},Ir0=function(L){var m=AsZ(L),n=Math,C=n.min;
var Z=L.G?Date.now()-L.G:0;n=C.call(n,Z,m);Jsw(L,Math.ceil((m-n)/1E3));m-n<=500&&L.sW()?L.select(!0):L.sW()&&L.L.start()},AsZ=function(L){if(L.U.isFullscreen()){var m;
L=(m=L.U.getVideoData())==null?void 0:m.wO;return L===-1||L===void 0?8E3:L}return L.U.BK()>=0?L.U.BK():g.Ee(L.U.D().experiments,"autoplay_time")||1E4},S1f=function(L,m){m=m.getWatchNextResponse();
var n,C;m=(n=Mil(m))==null?void 0:(C=n.nextButton)==null?void 0:C.buttonRenderer;L.K=m==null?void 0:m.navigationEndpoint;n=m==null?void 0:m.trackingParams;L.playButton&&n&&L.U.setTrackingParams(L.playButton.element,n)},b7l=function(L){var m;
return!((m=L.U.getVideoData())==null||!m.watchToWatchTransitionRenderer)},Jsw=function(L,m){m=m===void 0?-1:m;
L=L.W.nI("ytp-autonav-endscreen-upnext-header");g.lF(L);if(m>=0){m=String(m);var n="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],C="Up next in $SECONDS".indexOf(n);if(C>=0){L.appendChild(g.Da("Up next in $SECONDS".slice(0,C)));var Z=g.q4("span");g.z2(Z,"ytp-autonav-endscreen-upnext-header-countdown-number");g.IL(Z,m);L.appendChild(Z);L.appendChild(g.Da("Up next in $SECONDS".slice(C+n.length)));return}}g.IL(L,"Up next")},VV=function(L,m){g.H.call(this,{Z:"div",
xU:["html5-endscreen","ytp-player-content",m||"base-endscreen"]});this.created=!1;this.player=L},i1=function(L){g.H.call(this,{Z:"div",
xU:["ytp-upnext","ytp-player-content"],Y:{"aria-label":"{{aria_label}}"},V:[{Z:"div",T:"ytp-cued-thumbnail-overlay-image",Y:{style:"{{background}}"}},{Z:"span",T:"ytp-upnext-top",V:[{Z:"span",T:"ytp-upnext-header",zo:"Up Next"},{Z:"span",T:"ytp-upnext-title",zo:"{{title}}"},{Z:"span",T:"ytp-upnext-author",zo:"{{author}}"}]},{Z:"a",T:"ytp-upnext-autoplay-icon",Y:{role:"button",href:"{{url}}","aria-label":"Play next video"},V:[{Z:"svg",Y:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
V:[{Z:"circle",T:"ytp-svg-autoplay-circle",Y:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{Z:"circle",T:"ytp-svg-autoplay-ring",Y:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{Z:"path",T:"ytp-svg-fill",Y:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{Z:"span",T:"ytp-upnext-bottom",V:[{Z:"span",T:"ytp-upnext-cancel"},{Z:"span",T:"ytp-upnext-paused",
zo:"Auto-play is paused"}]}]});this.api=L;this.cancelButton=null;this.K=this.nI("ytp-svg-autoplay-ring");this.G=this.notification=this.W=this.suggestion=null;this.L=new g.jW(this.IK,5E3,this);this.J=0;var m=this.nI("ytp-upnext-cancel");this.cancelButton=new g.H({Z:"button",xU:["ytp-upnext-cancel-button","ytp-button"],Y:{tabindex:"0","aria-label":"Cancel auto-play"},zo:"Cancel"});g.h(this,this.cancelButton);this.cancelButton.listen("click",this.sL,this);this.cancelButton.sN(m);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.h(this,this.L);this.api.createClientVe(this.element,this,18788);m=this.nI("ytp-upnext-autoplay-icon");this.j(m,"click",this.UL);this.api.createClientVe(m,this,115130);this.gi();this.j(L,"autonavvisibility",this.gi);this.j(L,"mdxnowautoplaying",this.wcj);this.j(L,"mdxautoplaycanceled",this.OYd);g.VR(this.element,"ytp-upnext-mobile",this.api.D().J)},tiD=function(L,m){if(m)return m;
if(L.api.isFullscreen()){var n;L=(n=L.api.getVideoData())==null?void 0:n.wO;return L===-1||L===void 0?8E3:L}return L.api.BK()>=0?L.api.BK():g.Ee(L.api.D().experiments,"autoplay_time")||1E4},fr1=function(L,m){m=tiD(L,m);
var n=Math,C=n.min;var Z=(0,g.SI)()-L.J;n=C.call(n,Z,m);m=m===0?1:Math.min(n/m,1);L.K.setAttribute("stroke-dashoffset",""+-211*(m+1));m>=1&&L.sW()&&L.api.getPresentingPlayerType()!==3?L.select(!0):L.sW()&&L.W.start()},$$=function(L){VV.call(this,L,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.H({Z:"div",T:"ytp-suggestion-panel",V:[{Z:"div",xU:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],zo:"More videos"}]});this.B=new g.H({Z:"div",T:"ytp-suggestions-container"});this.videos=[];this.G=null;this.K=this.S=!1;this.J=new N0(this.player);g.h(this,this.J);this.J.sN(this.element);L.getVideoData().Bc?this.W=this.J:(this.W=new i1(L),g.Zq(this.player,this.W.element,4),g.h(this,this.W));this.overlay=new g.H({Z:"div",
T:"ytp-autonav-overlay-cancelled-state"});g.h(this,this.overlay);this.overlay.sN(this.element);this.L=new g.tC(this);g.h(this,this.L);g.h(this,this.table);this.table.sN(this.element);this.table.show();g.h(this,this.B);this.B.sN(this.table.element);this.hide()},a2=function(L){var m=L.aU();
m!==L.K&&(L.K=m,eNF(L.player),L.K?(L.J!==L.W&&L.J.hide(),L.table.hide()):(L.J!==L.W&&L.J.show(),L.table.show()))},UB0=function(L){VV.call(this,L,"videowall-endscreen");
var m=this;this.U=L;this.stills=[];this.G=this.videoData=null;this.L=this.S=!1;this.B=null;g.Ei(this.element,"modern-videowall-endscreen");this.J=new g.tC(this);g.h(this,this.J);this.K=new g.jW(function(){g.Ei(m.element,"ytp-show-tiles")},0);
g.h(this,this.K);this.table=new g.ES({Z:"div",T:"ytp-modern-endscreen-content"});g.h(this,this.table);this.table.sN(this.element);L.getVideoData().Bc?this.W=new N0(L,!0):this.W=new i1(L);g.h(this,this.W);g.Zq(this.player,this.W.element,4);L.createClientVe(this.element,this,158789);this.hide()},q0=function(L){return g.zT(L.player)&&L.Z4()&&!L.G},Ds=function(L){var m=L.aU();
m!==L.S&&(L.S=m,eNF(L.player))},BUH=function(L){VV.call(this,L,"subscribecard-endscreen");
this.W=new g.H({Z:"div",T:"ytp-subscribe-card",V:[{Z:"img",T:"ytp-author-image",Y:{src:"{{profilePicture}}"}},{Z:"div",T:"ytp-subscribe-card-right",V:[{Z:"div",T:"ytp-author-name",zo:"{{author}}"},{Z:"div",T:"html5-subscribe-button-container"}]}]});g.h(this,this.W);this.W.sN(this.element);var m=L.getVideoData();this.subscribeButton=new g.zm("Subscribe",null,"Unsubscribe",null,!0,!1,m.D_,m.subscribed,"trailer-endscreen",null,L,!1);g.h(this,this.subscribeButton);this.subscribeButton.sN(this.W.nI("html5-subscribe-button-container"));
this.j(L,"videodatachange",this.Bv);this.Bv();this.hide()},ON=function(L){var m=L.D(),n=g.I8||g.ze?{style:"will-change: opacity"}:void 0,C=m.L,Z=["ytp-videowall-still"];
m.J&&Z.push("ytp-videowall-show-text");g.H.call(this,{Z:"a",xU:Z,Y:{href:"{{url}}",target:C?m.X:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},V:[{Z:"div",T:"ytp-videowall-still-image",Y:{style:"{{background}}"}},{Z:"span",T:"ytp-videowall-still-info",Y:{"aria-hidden":"true"},V:[{Z:"span",T:"ytp-videowall-still-info-bg",V:[{Z:"span",T:"ytp-videowall-still-info-content",Y:n,V:[{Z:"span",T:"ytp-videowall-still-info-title",zo:"{{title}}"},
{Z:"span",T:"ytp-videowall-still-info-author",zo:"{{author_and_views}}"},{Z:"span",T:"ytp-videowall-still-info-live",zo:"Live"},{Z:"span",T:"ytp-videowall-still-info-duration",zo:"{{duration}}"}]}]}]},{Z:"span",xU:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],Y:{"aria-hidden":"true"},V:[{Z:"span",T:"ytp-videowall-still-listlabel-icon"},"Playlist",{Z:"span",T:"ytp-videowall-still-listlabel-length",V:[" (",{Z:"span",zo:"{{playlist_length}}"},")"]}]},{Z:"span",xU:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],Y:{"aria-hidden":"true"},V:[{Z:"span",T:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{Z:"span",T:"ytp-videowall-still-listlabel-length",zo:" (50+)"}]}]});this.suggestion=null;this.J=C;this.api=L;this.W=new g.tC(this);g.h(this,this.W);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.W.j(L,"videodatachange",this.onVideoDataChange);L.createServerVe(this.element,this);this.onVideoDataChange()},l1=function(L){VV.call(this,L,"videowall-endscreen");
var m=this;this.U=L;this.G=0;this.stills=[];this.L=this.videoData=null;this.K=this.B=!1;this.X=null;this.J=new g.tC(this);g.h(this,this.J);this.S=new g.jW(function(){g.Ei(m.element,"ytp-show-tiles")},0);
g.h(this,this.S);var n=new g.H({Z:"button",xU:["ytp-button","ytp-endscreen-previous"],Y:{"aria-label":"Previous"},V:[g.D9()]});g.h(this,n);n.sN(this.element);n.listen("click",this.F_,this);this.table=new g.ES({Z:"div",T:"ytp-endscreen-content"});g.h(this,this.table);this.table.sN(this.element);n=new g.H({Z:"button",xU:["ytp-button","ytp-endscreen-next"],Y:{"aria-label":"Next"},V:[g.OS()]});g.h(this,n);n.sN(this.element);n.listen("click",this.SK,this);L.getVideoData().Bc?this.W=new N0(L,!0):this.W=
new i1(L);g.h(this,this.W);g.Zq(this.player,this.W.element,4);L.createClientVe(this.element,this,158789);this.hide()},R2=function(L){return g.zT(L.player)&&L.Z4()&&!L.L},wk=function(L){var m=L.aU();
m!==L.B&&(L.B=m,eNF(L.player))},PC_=function(L,m){g.H.call(this,{Z:"button",
xU:["ytp-watch-on-youtube-button","ytp-button"],zo:"{{content}}"});this.U=L;this.buttonType=this.buttonType=m;this.Qo();this.buttonType===2&&g.Ei(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.Qo);this.fu(!0)},ej=function(L){VV.call(this,L,"watch-again-on-youtube-endscreen");
this.watchButton=new PC_(L,1);g.h(this,this.watchButton);this.watchButton.sN(this.element);g.aoZ(L)&&(this.W=new g.mF(L),g.h(this,this.W),this.J=new g.H({Z:"div",xU:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],Y:{tabIndex:"-1"},V:[this.W]}),g.h(this,this.J),this.W.sN(this.J.element),this.J.sN(this.element));L.createClientVe(this.element,this,156914);this.hide()},FQ0=function(L){g.S2.call(this,L);
var m=this;this.endScreen=null;this.W=this.J=this.G=!1;this.listeners=new g.tC(this);g.h(this,this.listeners);var n=L.D();L.isEmbedsShortsMode()?this.endScreen=new ej(L):spZ(L)?(this.G=!0,QpZ(this),this.W?this.endScreen=new $$(L):n.N("delhi_modern_endscreen")?this.endScreen=new UB0(L):this.endScreen=new l1(L)):n.Ox?this.endScreen=new BUH(L):this.endScreen=new VV(L);g.h(this,this.endScreen);g.Zq(L,this.endScreen.element,4);pyF(this);this.listeners.j(L,"videodatachange",this.onVideoDataChange,this);
this.listeners.j(L,g.La("endscreen"),function(C){m.onCueRangeEnter(C)});
this.listeners.j(L,g.mM("endscreen"),function(C){m.onCueRangeExit(C)})},QpZ=function(L){var m=L.player.getVideoData();
if(!m||L.W===m.qg&&L.J===m.Bc)return!1;L.W=m.qg;L.J=m.Bc;return!0},spZ=function(L){L=L.D();
return L.N6&&!L.Ox&&!L.disableOrganicUi},pyF=function(L){L.player.H0("endscreen");
var m=L.player.getVideoData();m=new g.oD(Math.max((m.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var n=new g.oD(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});L.player.Aw([m,n])};
g.yE.prototype.BK=g.za(6,function(){return this.app.BK()});
g.RY.prototype.BK=g.za(5,function(){return this.getVideoData().KR});
g.Gd.prototype.LK=g.za(4,function(L){this.U5().LK(L)});
g.ol.prototype.LK=g.za(3,function(L){this.MG!==L&&(this.MG=L,this.tF())});
g.R(Xz,g.H);Xz.prototype.select=function(){this.U.CF(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.dK||void 0)&&this.U.logClick(this.element)};
Xz.prototype.onClick=function(L){g.tg(L,this.U,this.W,this.suggestion.sessionData||void 0)&&this.select()};
Xz.prototype.onKeyPress=function(L){switch(L.keyCode){case 13:case 32:L.defaultPrevented||(this.select(),L.preventDefault())}};g.R(N0,g.H);g.l=N0.prototype;g.l.G9=function(L){this.suggestion!==L&&(this.suggestion=L,g.Nd(this.W,L),this.playButton.updateValue("url",this.suggestion.F2()),TM(this))};
g.l.sW=function(){return this.G>0};
g.l.kQ=function(){this.sW()||(this.G=Date.now(),Ir0(this),gm_(this.U,AsZ(this)),g.VR(this.U.getRootNode(),"countdown-running",this.sW()))};
g.l.Hb=function(){this.O0();Ir0(this);var L=this.W.nI("ytp-autonav-endscreen-upnext-header");L&&g.IL(L,"Up next")};
g.l.O0=function(){this.sW()&&(this.L.stop(),this.G=0)};
g.l.select=function(L){this.U.nextVideo(!1,L===void 0?!1:L);this.O0()};
g.l.Kg=function(L){g.tg(L,this.U)&&(L.currentTarget===this.playButton.element?this.U.logClick(this.playButton.element):L.currentTarget===this.W.nI("ytp-autonav-endscreen-link-container")&&(L=this.W.nI("ytp-autonav-endscreen-link-container"),this.U.logVisibility(L,!0),this.U.logClick(L)),this.K?(this.U.Vd("innertubeCommand",this.K),this.O0()):this.select())};
g.l.cY=function(){this.U.logClick(this.cancelButton.element);g.oo(this.U,!0);this.cancelCommand&&this.U.Vd("innertubeCommand",this.cancelCommand)};
g.l.onVideoDataChange=function(L,m){S1f(this,m);L=m.getWatchNextResponse();var n,C;L=(n=Mil(L))==null?void 0:(C=n.cancelButton)==null?void 0:C.buttonRenderer;this.cancelCommand=L==null?void 0:L.command};
g.l.KY1=function(L){if(b7l(this)){var m=this.U.getVideoData().watchToWatchTransitionRenderer,n=m==null?void 0:m.fromColorPaletteDark;m=m==null?void 0:m.toColorPaletteDark;if(n&&m){var C=this.element;C.style.setProperty("--w2w-start-background-color",g.Fv(n.surgeColor));C.style.setProperty("--w2w-start-primary-text-color",g.Fv(n.primaryTitleColor));C.style.setProperty("--w2w-start-secondary-text-color",g.Fv(n.secondaryTitleColor));C.style.setProperty("--w2w-end-background-color",g.Fv(m.surgeColor));
C.style.setProperty("--w2w-end-primary-text-color",g.Fv(m.primaryTitleColor));C.style.setProperty("--w2w-end-secondary-text-color",g.Fv(m.secondaryTitleColor));C.style.setProperty("--w2w-animation-duration",L+"ms")}g.VR(this.element,"ytp-w2w-animate",!0)}};
g.l.gH=function(L){this.U.N("web_autonav_color_transition")&&L!==2&&g.VR(this.element,"ytp-w2w-animate",!1)};
g.l.ZY=function(){var L=this.U.aU();this.S&&this.ij!==L&&this.fu(L);TM(this);this.U.logVisibility(this.container.element,L);this.U.logVisibility(this.cancelButton.element,L);this.U.logVisibility(this.W.nI("ytp-autonav-endscreen-link-container"),L);this.U.logVisibility(this.playButton.element,L)};
g.l.d$=function(L){return L.width<400||L.height<459};g.R(VV,g.H);g.l=VV.prototype;g.l.create=function(){this.created=!0};
g.l.destroy=function(){this.created=!1};
g.l.Z4=function(){return!1};
g.l.aU=function(){return!1};
g.l.qk=function(){return!1};g.R(i1,g.H);g.l=i1.prototype;g.l.IK=function(){this.notification&&(this.L.stop(),this.rV(this.G),this.G=null,this.notification.close(),this.notification=null)};
g.l.G9=function(L){this.suggestion=L;g.Nd(this,L,"hqdefault.jpg")};
g.l.gi=function(){this.fu(this.api.aU());this.api.logVisibility(this.element,this.api.aU());this.api.logVisibility(this.nI("ytp-upnext-autoplay-icon"),this.api.aU());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.aU())};
g.l.iYv=function(){window.focus();this.IK()};
g.l.kQ=function(L){var m=this;this.sW()||(g.zy("a11y-announce","Up Next "+this.suggestion.title),this.J=(0,g.SI)(),this.W=new g.jW(function(){fr1(m,L)},25),fr1(this,L),gm_(this.api,tiD(this,L)));
g.N8(this.element,"ytp-upnext-autoplay-paused")};
g.l.hide=function(){g.H.prototype.hide.call(this)};
g.l.sW=function(){return!!this.W};
g.l.Hb=function(){this.O0();this.J=(0,g.SI)();fr1(this);g.Ei(this.element,"ytp-upnext-autoplay-paused")};
g.l.O0=function(){this.sW()&&(this.W.dispose(),this.W=null)};
g.l.select=function(L){L=L===void 0?!1:L;if(this.api.D().N("autonav_notifications")&&L&&window.Notification&&typeof document.hasFocus==="function"){var m=Notification.permission;m==="default"?Notification.requestPermission():m!=="granted"||document.hasFocus()||(this.IK(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.Qf()}),this.G=this.j(this.notification,"click",this.iYv),this.L.start())}this.O0();this.api.nextVideo(!1,L)};
g.l.UL=function(L){!g.Sy(this.cancelButton.element,L.target)&&g.tg(L,this.api)&&(this.api.aU()&&this.api.logClick(this.nI("ytp-upnext-autoplay-icon")),this.select())};
g.l.sL=function(){this.api.aU()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.oo(this.api,!0)};
g.l.wcj=function(L){this.api.getPresentingPlayerType();this.show();this.kQ(L)};
g.l.OYd=function(){this.api.getPresentingPlayerType();this.O0();this.hide()};
g.l.Go=function(){this.O0();this.IK();g.H.prototype.Go.call(this)};g.R($$,VV);g.l=$$.prototype;g.l.create=function(){VV.prototype.create.call(this);this.L.j(this.player,"appresize",this.z9);this.L.j(this.player,"onVideoAreaChange",this.z9);this.L.j(this.player,"videodatachange",this.onVideoDataChange);this.L.j(this.player,"autonavchange",this.cP);this.L.j(this.player,"onAutonavCancelled",this.x8);this.onVideoDataChange()};
g.l.show=function(){VV.prototype.show.call(this);(this.S||this.G&&this.G!==this.videoData.clientPlaybackNonce)&&g.oo(this.player,!1);g.zT(this.player)&&this.Z4()&&!this.G?(a2(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.W.select(!0):this.W.kQ():this.videoData.autonavState===3&&this.W.Hb()):(g.oo(this.player,!0),a2(this));this.z9()};
g.l.hide=function(){VV.prototype.hide.call(this);this.W.Hb();a2(this)};
g.l.z9=function(){var L=this.player.s1(!0,this.player.isFullscreen());a2(this);TM(this.J);g.VR(this.element,"ytp-autonav-cancelled-small-mode",this.d$(L));g.VR(this.element,"ytp-autonav-cancelled-tiny-mode",this.Mi(L));g.VR(this.element,"ytp-autonav-cancelled-mini-mode",L.width<=400||L.height<=360);this.overlay&&g.GB(this.overlay.element,{width:L.width+"px"});if(!this.K)for(L=0;L<this.videos.length;L++)g.VR(this.videos[L].element,"ytp-suggestion-card-with-margin",L%2===1)};
g.l.onVideoDataChange=function(){var L=this.player.getVideoData();if(this.videoData!==L&&L){this.videoData=L;if((L=this.videoData.suggestions)&&L.length||this.player.N("web_player_autonav_empty_suggestions_fix")){var m=g.fz(this.videoData);m&&(this.W.G9(m),this.W!==this.J&&this.J.G9(m))}if(L&&L.length)for(m=0;m<uk$.length;++m){var n=uk$[m];if(L&&L[n]){this.videos[m]=new Xz(this.player);var C=this.videos[m];n=L[n];C.suggestion!==n&&(C.suggestion=n,g.Nd(C,n));g.h(this,this.videos[m]);this.videos[m].sN(this.B.element)}}this.z9()}};
g.l.cP=function(L){L===1?(this.S=!1,this.G=this.videoData.clientPlaybackNonce,this.W.O0(),this.ij&&this.z9()):(this.S=!0,this.aU()&&(L===2?this.W.kQ():L===3&&this.W.Hb()))};
g.l.x8=function(L){L?this.cP(1):(this.G=null,this.S=!1)};
g.l.Z4=function(){return this.videoData.autonavState!==1};
g.l.d$=function(L){return(L.width<910||L.height<459)&&!this.Mi(L)&&!(L.width<=400||L.height<=360)};
g.l.Mi=function(L){return L.width<800&&!(L.width<=400||L.height<=360)};
g.l.aU=function(){return this.ij&&g.zT(this.player)&&this.Z4()&&!this.G};
var uk$=[1,3,2,4];g.R(UB0,VV);g.l=UB0.prototype;g.l.create=function(){VV.prototype.create.call(this);var L=this.player.getVideoData();L&&(this.videoData=L);this.MI();this.J.j(this.player,"appresize",this.MI);this.J.j(this.player,"onVideoAreaChange",this.MI);this.J.j(this.player,"videodatachange",this.onVideoDataChange);this.J.j(this.player,"autonavchange",this.yX);this.J.j(this.player,"onAutonavCancelled",this.rH);L=this.videoData.autonavState;L!==this.B&&this.yX(L);this.J.j(this.element,"transitionend",this.Nh)};
g.l.destroy=function(){g.tT(this.J);g.vy(this.stills);this.stills=[];VV.prototype.destroy.call(this);g.N8(this.element,"ytp-show-tiles");this.K.stop();this.B=this.videoData.autonavState};
g.l.Z4=function(){return this.videoData.autonavState!==1};
g.l.show=function(){var L=this.ij;VV.prototype.show.call(this);g.N8(this.element,"ytp-show-tiles");this.player.D().J?g.cO(this.K):this.K.start();(this.L||this.G&&this.G!==this.videoData.clientPlaybackNonce)&&g.oo(this.player,!1);q0(this)?(Ds(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.W.select(!0):this.W.kQ():this.videoData.autonavState===3&&this.W.Hb()):(g.oo(this.player,!0),Ds(this));L!==this.ij&&this.player.logVisibility(this.element,!0)};
g.l.hide=function(){var L=this.ij;VV.prototype.hide.call(this);this.W.Hb();Ds(this);L!==this.ij&&this.player.logVisibility(this.element,!1)};
g.l.Nh=function(L){L.target===this.element&&this.MI()};
g.l.MI=function(){var L,m,n,C;var Z=((L=this.videoData)==null?0:(m=L.suggestions)==null?0:m.length)?(n=this.videoData)==null?void 0:n.suggestions:[(C=this.videoData)==null?void 0:g.fz(C)];if(Z.length){m=this.U.s1(!0,this.U.isFullscreen());L=Math.floor((m.width-64+16)/(g.kp(m.width*.27,250,450)+16));m=Math.min(3,Math.floor((m.height-64)/((m.width-64-(L-1)*16)/L*.5625+70)));g.T2(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.Ei(this.element,"ytp-modern-endscreen-limit-rows-"+m);g.VR(this.element,"ytp-modern-endscreen-single-item",L===1);g.VR(this.element,"ytp-modern-endscreen-row-0",m===0);L=this.table.element;L.ariaLive="polite";this.W.G9(g.fz(this.videoData));this.W instanceof N0&&TM(this.W);g.VR(this.element,"ytp-endscreen-takeover",q0(this));Ds(this);m=0;L.ariaBusy="true";n=Z.length;for(C=0;C<n;C++){var z=C%n,v=this.stills[C];v||(v=new g.Tx(this.player),this.stills[C]=v,L.appendChild(v.element));g.qm2(v,Z[z]);m++}this.stills.length=
m}};
g.l.onVideoDataChange=function(){var L=this.player.getVideoData(1);this.videoData!==L&&(L!=null&&g.fz(L)?(this.videoData=L,this.MI()):this.player.kU("missg",{vid:(L==null?void 0:L.videoId)||"",cpn:(L==null?void 0:L.clientPlaybackNonce)||""}))};
g.l.qk=function(){return this.W.sW()};
g.l.yX=function(L){L===1?(this.L=!1,this.G=this.videoData.clientPlaybackNonce,this.W.O0(),this.ij&&this.MI()):(this.L=!0,this.ij&&q0(this)&&(L===2?this.W.kQ():L===3&&this.W.Hb()))};
g.l.rH=function(L){if(L){for(L=0;L<this.stills.length;L++)this.U.logVisibility(this.stills[L].element,!0);this.yX(1)}else this.G=null,this.L=!1;this.MI()};
g.l.aU=function(){return this.ij&&q0(this)};g.R(BUH,VV);BUH.prototype.Bv=function(){var L=this.player.getVideoData();this.W.update({profilePicture:L.profilePicture,author:L.author});this.subscribeButton.channelId=L.D_;var m=this.subscribeButton;L.subscribed?m.W():m.J()};g.R(ON,g.H);ON.prototype.select=function(){this.api.CF(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.dK||void 0)&&this.api.logClick(this.element)};
ON.prototype.onClick=function(L){if(g.EI(this.api.D())&&this.api.N("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var m=this.suggestion.F2(),n={};g.my(this.api,n);m=g.Rj(m,n);g.fW(m,this.api,L)}else g.tg(L,this.api,this.J,this.suggestion.sessionData||void 0)&&this.select()};
ON.prototype.onKeyPress=function(L){switch(L.keyCode){case 13:case 32:L.defaultPrevented||(this.select(),L.preventDefault())}};
ON.prototype.onVideoDataChange=function(){var L=this.api.getVideoData(),m=this.api.D();this.J=L.IL?!1:m.L};g.R(l1,VV);g.l=l1.prototype;g.l.create=function(){VV.prototype.create.call(this);var L=this.player.getVideoData();L&&(this.videoData=L);this.ZL();this.J.j(this.player,"appresize",this.ZL);this.J.j(this.player,"onVideoAreaChange",this.ZL);this.J.j(this.player,"videodatachange",this.onVideoDataChange);this.J.j(this.player,"autonavchange",this.W9);this.J.j(this.player,"onAutonavCancelled",this.mC);L=this.videoData.autonavState;L!==this.X&&this.W9(L);this.J.j(this.element,"transitionend",this.QF)};
g.l.destroy=function(){g.tT(this.J);g.vy(this.stills);this.stills=[];VV.prototype.destroy.call(this);g.N8(this.element,"ytp-show-tiles");this.S.stop();this.X=this.videoData.autonavState};
g.l.Z4=function(){return this.videoData.autonavState!==1};
g.l.show=function(){var L=this.ij;VV.prototype.show.call(this);g.N8(this.element,"ytp-show-tiles");this.player.D().J?g.cO(this.S):this.S.start();(this.K||this.L&&this.L!==this.videoData.clientPlaybackNonce)&&g.oo(this.player,!1);R2(this)?(wk(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.W.select(!0):this.W.kQ():this.videoData.autonavState===3&&this.W.Hb()):(g.oo(this.player,!0),wk(this));L!==this.ij&&this.player.logVisibility(this.element,!0)};
g.l.hide=function(){var L=this.ij;VV.prototype.hide.call(this);this.W.Hb();wk(this);L!==this.ij&&this.player.logVisibility(this.element,!1)};
g.l.QF=function(L){L.target===this.element&&this.ZL()};
g.l.ZL=function(){var L,m,n,C;var Z=((L=this.videoData)==null?0:(m=L.suggestions)==null?0:m.length)?(n=this.videoData)==null?void 0:n.suggestions:[(C=this.videoData)==null?void 0:g.fz(C)];if(Z.length){g.Ei(this.element,"ytp-endscreen-paginate");var z=this.U.s1(!0,this.U.isFullscreen());if(L=g.r_(this.U))L=L.i6()?48:32,z.width-=L*2;var v=z.width/z.height;C=96/54;m=L=2;var X=Math.max(z.width/96,2),N=Math.max(z.height/54,2);n=Z.length;var T=n*4;for(T-=4;T>0&&(L<X||m<N);){var V=L/2,a=m/2,q=L<=X-2&&T>=
a*4,D=m<=N-2&&T>=V*4;if((V+1)/a*C/v>v/(V/(a+1)*C)&&D)T-=V*4,m+=2;else if(q)T-=a*4,L+=2;else if(D)T-=V*4,m+=2;else break}C=!1;T>=12&&n*4-T<=6&&(m>=4||L>=4)&&(C=!0);T=L*96;X=m*54;v=T/X<v?z.height/X:z.width/T;v=Math.min(v,2);T=Math.floor(Math.min(z.width,T*v));X=Math.floor(Math.min(z.height,X*v));z=this.table.element;z.ariaLive="polite";g.n6(z,T,X);g.GB(z,{marginLeft:T/-2+"px",marginTop:X/-2+"px"});this.W.G9(g.fz(this.videoData));this.W instanceof N0&&TM(this.W);g.VR(this.element,"ytp-endscreen-takeover",
R2(this));wk(this);T+=4;X+=4;v=0;z.ariaBusy="true";for(N=0;N<L;N++)for(V=0;V<m;V++)if(a=v,D=0,C&&N>=L-2&&V>=m-2?D=1:V%2===0&&N%2===0&&(V<2&&N<2?V===0&&N===0&&(D=2):D=2),a=g.Hr(a+this.G,n),D!==0){q=this.stills[v];q||(q=new ON(this.player),this.stills[v]=q,z.appendChild(q.element));var O=Math.floor(X*V/m),e=Math.floor(T*N/L),I=Math.floor(X*(V+D)/m)-O-4,t=Math.floor(T*(N+D)/L)-e-4;g.oL(q.element,e,O);g.n6(q.element,t,I);g.GB(q.element,"transitionDelay",(V+N)/20+"s");g.VR(q.element,"ytp-videowall-still-mini",
D===1);g.VR(q.element,"ytp-videowall-still-large",D>2);D=Math.max(t,I);g.VR(q.element,"ytp-videowall-still-round-large",D>=256);g.VR(q.element,"ytp-videowall-still-round-medium",D>96&&D<256);g.VR(q.element,"ytp-videowall-still-round-small",D<=96);a=Z[a];q.suggestion!==a&&(q.suggestion=a,D=q.api.D(),O=g.vu(q.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.Nd(q,a,O),g.EI(D)&&!q.api.N("web_player_log_click_before_generating_ve_conversion_params")&&(D=a.F2(),O={},g.QE(q.api,"addEmbedsConversionTrackingParams",
[O]),D=g.Rj(D,O),q.updateValue("url",D)),(a=(a=a.sessionData)&&a.itct)&&q.api.setTrackingParams(q.element,a));v++}z.ariaBusy="false";g.VR(this.element,"ytp-endscreen-paginate",v<n);for(Z=this.stills.length-1;Z>=v;Z--)L=this.stills[Z],g.wr(L.element),g.zG(L);this.stills.length=v}};
g.l.onVideoDataChange=function(){var L=this.player.getVideoData(1);this.videoData!==L&&(L!=null&&g.fz(L)?(this.G=0,this.videoData=L,this.ZL()):this.player.kU("missg",{vid:(L==null?void 0:L.videoId)||"",cpn:(L==null?void 0:L.clientPlaybackNonce)||""}))};
g.l.SK=function(){this.G+=this.stills.length;this.ZL()};
g.l.F_=function(){this.G-=this.stills.length;this.ZL()};
g.l.qk=function(){return this.W.sW()};
g.l.W9=function(L){L===1?(this.K=!1,this.L=this.videoData.clientPlaybackNonce,this.W.O0(),this.ij&&this.ZL()):(this.K=!0,this.ij&&R2(this)&&(L===2?this.W.kQ():L===3&&this.W.Hb()))};
g.l.mC=function(L){if(L){for(L=0;L<this.stills.length;L++)this.U.logVisibility(this.stills[L].element,!0);this.W9(1)}else this.L=null,this.K=!1;this.ZL()};
g.l.aU=function(){return this.ij&&R2(this)};g.R(PC_,g.H);g.l=PC_.prototype;g.l.Qo=function(){switch(this.buttonType){case 1:var L="Watch again on YouTube";var m=156915;break;case 2:L="Continue watching on YouTube";m=156942;break;default:L="Continue watching on YouTube",m=156942}this.update({content:L});this.U.hasVe(this.element)&&this.U.destroyVe(this.element);this.U.createClientVe(this.element,this,m)};
g.l.onClick=function(L){this.U.N("web_player_log_click_before_generating_ve_conversion_params")&&this.U.logClick(this.element);g.fW(this.getVideoUrl(),this.U,L);this.U.N("web_player_log_click_before_generating_ve_conversion_params")||this.U.logClick(this.element)};
g.l.getVideoUrl=function(){var L=!0;switch(this.buttonType){case 1:L=!0;break;case 2:L=!1}L=this.U.getVideoUrl(L,!1,!1,!0);var m=this.U.D();if(g.EI(m)){var n={};g.EI(m)&&g.QE(this.U,"addEmbedsConversionTrackingParams",[n]);L=g.Rj(L,n)}return L};
g.l.logVisibility=function(){this.U.logVisibility(this.element,this.ij&&this.C)};
g.l.show=function(){g.H.prototype.show.call(this);this.logVisibility()};
g.l.hide=function(){g.H.prototype.hide.call(this);this.logVisibility()};
g.l.t8=function(L){g.H.prototype.t8.call(this,L);this.logVisibility()};g.R(ej,VV);ej.prototype.hasSuggestions=function(){var L;return(L=this.W)==null?void 0:L.hasSuggestions()};
ej.prototype.show=function(){if(this.player.getPlayerState()!==3){VV.prototype.show.call(this);var L=this.J;if(L){var m=this.W.hasSuggestions();g.VR(this.element,"ytp-shorts-branded-ui",m);m?L.show():L.hide()}var n;(n=g.r_(this.player))==null||n.LK(!0);this.player.logVisibility(this.element,!0);this.watchButton.t8(!0)}};
ej.prototype.hide=function(){VV.prototype.hide.call(this);var L;(L=g.r_(this.player))==null||L.LK(!1);this.player.logVisibility(this.element,!1);this.watchButton.t8(!1)};g.R(FQ0,g.S2);g.l=FQ0.prototype;g.l.fF=function(){var L=this.player.getVideoData(),m=L.mutedAutoplay&&(L.limitedPlaybackDurationInSeconds>0||L.endSeconds>0||L.mutedAutoplayDurationMode!==2);if(this.player.isEmbedsShortsMode()&&!m)return!0;var n;var C=!!((L==null?0:g.fz(L))||(L==null?0:(n=L.suggestions)==null?0:n.length));C=!spZ(this.player)||C;L=L.ov;n=this.player.y8();return C&&!L&&!n&&!m};
g.l.aU=function(){return this.endScreen.aU()};
g.l.tDZ=function(){return this.aU()?this.endScreen.qk():!1};
g.l.Go=function(){this.player.H0("endscreen");g.S2.prototype.Go.call(this)};
g.l.load=function(){var L=this.player.getVideoData();var m=L.transitionEndpointAtEndOfStream;if(m&&m.videoId){var n=this.player.UK().qX.get("heartbeat"),C=g.fz(L);!C||m.videoId!==C.videoId||L.Te?(this.player.CF(m.videoId,void 0,void 0,!0,!0,m),n&&n.D7("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),L=!0):L=!1}else L=!1;L||(g.S2.prototype.load.call(this),this.endScreen.show())};
g.l.unload=function(){g.S2.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.l.onCueRangeEnter=function(L){this.fF()&&(this.endScreen.created||this.endScreen.create(),L.getId()==="load"&&this.load())};
g.l.onCueRangeExit=function(L){L.getId()==="load"&&this.loaded&&this.unload()};
g.l.onVideoDataChange=function(){pyF(this);this.G&&QpZ(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.W?this.endScreen=new $$(this.player):this.endScreen=new l1(this.player),g.h(this,this.endScreen),g.Zq(this.player,this.endScreen.element,4))};g.Md("endscreen",FQ0);})(_yt_player);
